### ISSUE TITLE
mssql-conf fails to run as python isn't installed

### ISSUE THREAD

**Issue by LuisBosquez** [Microsoft/mssql-docker#1]
Python isn't installed by default, so running the mssql-conf configuration tool isn't supported out of the box.

**Comment by twright-msft** [comment]
We are going to include python in the next release of the mssql-server-linux image.

**Comment by twright-msft** [comment]
This issue should be resolved with the new CTP 1.2 image that was released to Docker Hub today.  For anybody that has had this problem, please docker rmi microsoft/mssql-server-linux and then docker pull microsoft/msssql-server-linux and verify that things are working as you would expect.
