### ISSUE TITLE
Container just exists when using the example run statement

### ISSUE THREAD

**Issue by fallenidol** [Microsoft/mssql-docker#100]
using the example run command as specified on docker hub, the container just immediately exists back to the cmd prompt. DOCKER PS reveals that indeed nothing is running

docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux

**Comment by Koubek** [comment]
Your command seems to be OK because it will create a new container with a new name so there should not be any conflict on the name level.

Anyway, you should use `docker ps -a` to show all containers even those not running. This is especially useful when using `--name` flag.

**Comment by fallenidol** [comment]
Sorry, just realised it's due it insufficient memory being allocated to the docker process.
