### ISSUE TITLE
MDF Compatability

### ISSUE THREAD

**Issue by genifycom** [Microsoft/mssql-docker#102]
If we are running mssql in a Linux Docker container, can we attach a host system Windows MDF file?

That is, are the files binary compatible for mssql between windows and linux?

I really do not want to have to backup and restore the Windows MDF into the Linux container in order to use it.

**Comment by twright-msft** [comment]
Yes, .bak and .mdf/.ldf are binary compatible between SQL Server on Windows and Linux.  Note: you will need to use WITH MOVE if you are moving from one OS to the other because the file path syntax is different.
Here's an example:
https://github.com/twright-msft/mssql-test-scripts/blob/master/BackupRestore/RestoreWideWorldImporters.sql

**Comment by genifycom** [comment]
Thank you for that information.

Just to clarify.

If my MDF is in C:\Data on the Windows host system and I have shared C with the Linux Docker container.

Can I then attach the Linux mssql directory to the Host MDF without moving/restoring the database?

**Comment by genifycom** [comment]
So I mapped as per the document https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-docker

Mount a host directory as data volume
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<YourStrong!Passw0rd>' -p 1433:1433 -v <host directory>:/var/opt/mssql -d microsoft/mssql-server-linux

I am using C:/Data

When I go to attach, I see the host mdf listed in /var/opt/mssql/. I select it and the database details shows the Data and Log. However, when I click OK, I get "Attach database failed...". "A file activation error occurred. The physical file name of \var\opt\mssql\mydatabase.mdf may be incorrect".

Notice that the / became a \ in the Error message.

**Comment by cbmcvey** [comment]
I wrestled with this for a bit, then found this blog post, and following that worked for me for this:
https://mathaywardhill.com/2017/05/08/how-to-attach-a-sql-server-database-in-a-linux-docker-container/

**Comment by perrysk-msft** [comment]
Thanks @cbmcvey! 

@genifycom - Please reopen if you are still having issues with this.

**Comment by saulyt** [comment]
Just had the issue myself. In case any one else comes across this, the solution is to change the backslashes (from the attach script generated by SSMS) to forwarded slashes:
`
USE [master]
GO
CREATE DATABASE [DatabaseName] ON 
( FILENAME = N'/sql/NameOfMDFFile.mdf' ),
( FILENAME = N'/sql/NameOfLogFile.ldf' )
 FOR ATTACH
GO
`
In the above example I have /sql mounted as a folder on my host Windows machine machine
