### ISSUE TITLE
sql windows container in docker-compose

### ISSUE THREAD

**Issue by girishgouda** [Microsoft/mssql-docker#105]
we are planning to use db conatiner "microsoft/mssql-server-windows-express" in a docker-compose file.
How to specify the connection string so that ASP.NET MVC application use this connection string from another image

**Comment by bizmate** [comment]
If the apprication is provisioned within docker then you can just use the name of the service. Similar example with the full server 
`version: '2'
services:
  mssql:
    image: microsoft/mssql-server-linux
    user: $UID
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password1
    ports:
      - 1433:1433
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:`

Then you need to connect to `mssql:1433` or your localhost/ip:1433

**Comment by perrysk-msft** [comment]
Thanks @bizmate! 

@girishgouda - Let us know if you are still having issues connecting to the sql container from your ASP.NET MVP app?
