### ISSUE TITLE
docker compose is getting hung up on step: " Attempting to load library 'xplog70.dll'"

### ISSUE THREAD

**Issue by rupeshtech** [Microsoft/mssql-docker#106]
I have Docker windows container with following versions
Client:
 Version:      17.06.0-ce-rc2
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   402dd4a
 Built:        Wed Jun  7 10:01:32 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce-rc2
 API version:  1.30 (minimum version 1.
 Go version:   go1.8.3
 Git commit:   402dd4a
 Built:        Wed Jun  7 10:03:57 2017
 OS/Arch:      windows/amd64
 Experimental: true

Following is Docker Compose

version: '3.2'

services:
  docker-demo-db:
    image: microsoft/mssql-server-windows
    ports:
      - "1533:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=xxxxxxx
    networks:
      - app-net

  docker-demo-web:
    image: docker-demo-web
    ports:
      - "85:80"
    environment:
      - DB_CONNECTION_STRING=Server=docker-demo-db;User Id=sa;Password=xxxxxxx;
    depends_on:
      - docker-demo-db
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat

when running docker-compose up getting stuck on step:Attempting to load library 'xplog70.dll'

Following is the log

xxxxxxxx   | VERBOSE: Starting SQL Server
xxxxxxxx   | VERBOSE: Changing SA login credentials
xxxxxxxx   | VERBOSE: Started SQL Server.
xxxxxxxx   |
xxxxxxxx   | TimeGenerated          EntryType Message
xxxxxxxx   | -------------          --------- -------
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Recovery is complete. This is an informatio...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Service Broker manager has started.
xxxxxxxx   | 6/10/2017 8:57:51 PM Information The Database Mirroring endpoint is in disab...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information The Service Broker endpoint is in disabled ...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information The tempdb database has 2 data file(s).
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Starting up database 'tempdb'.
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Parallel redo is shutdown for database 'Dem...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information 0 transactions rolled back in database 'Dem...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information 62 transactions rolled forward in database ...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Clearing tempdb database.
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Polybase feature disabled.
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Parallel redo is started for database 'Demo...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Always On: The availability replica manager...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information The SQL Server Network Interface library co...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information The SQL Server Network Interface library co...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information SQL Server is attempting to register a Serv...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Starting up database 'DemoDocker.Db.Product...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information SQL Server is now ready for client connecti...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Always On: The availability replica manager...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Dedicated admin connection support was esta...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Server is listening on [ 127.0.0.1 <ipv4> 1...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Server is listening on [ ::1 <ipv6> 1434].
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Starting up database 'model'.
xxxxxxxx   | 6/10/2017 8:57:51 PM Information The resource database build version is 14.0...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Starting up database 'mssqlsystemresource'.
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Starting up database 'msdb'.
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Server local connection provider is ready t...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Server local connection provider is ready t...
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Server is listening on [ 'any' <ipv4> 1433].
xxxxxxxx   | 6/10/2017 8:57:51 PM Information Server is listening on [ 'any' <ipv6> 1433].
xxxxxxxx   | 6/10/2017 9:03:05 PM Information None
xxxxxxxx   | 6/10/2017 9:03:48 PM Information Using 'xplog70.dll' version '2017.140.600' ...
xxxxxxxx   | 6/10/2017 9:03:48 PM Information Attempting to load library 'xplog70.dll' in...

Thanks in advance for help....

**Comment by rupeshtech** [comment]
found a work around.. running a "docker-compose up -d" works fine..

**Comment by perrysk-msft** [comment]
Thanks @rupeshtech!
