### ISSUE TITLE
Invoke-Sqlcmd non-deterministically fails when run from a setup script

### ISSUE THREAD

**Issue by Sean-Brown** [Microsoft/mssql-docker#107]
OS: Windows 10 Enterprise, Version 1607
`docker version` output:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

I created a [Github repo](https://github.com/Sean-Brown/docker-mssql-express) demonstrating the behavior. Essentially, I have a powershell script that:
  1. spins up a new Microsoft SQL Server Express container
  2. obtains the new container's IP address
  3. waits for the SQL service to be running in the container
  4. runs a database setup SQL script via the Invoke-Sqlcmd powershell commandlet

The strangeness I've observed is that the script usually fails (it sometimes does succeed) when it runs the Invoke-Sqlcmd command, but if I run the Invoke-Sqlcmd command manually it succeeds.

**Comment by Sean-Brown** [comment]
bump

**Comment by perrysk-msft** [comment]
Thanks @Sean-Brown for reporting this! This issue is already in our backlog. 
As a workaround, could you use sqlcmd with a -Q or -i flag (depending on your input) instead of Invoke-Sqlcmd?

**Comment by Sean-Brown** [comment]
Thanks for the reply @perrysk-msft. If the backlog is public, could you please link me to the corresponding backlog item? Also I tried your suggestion for changing `Invoke-Sqlcmd` to `sqlcmd` and it gives essentially the same error as before:
![image](https://user-images.githubusercontent.com/1503131/28023165-12a00a6c-655b-11e7-9e74-b9ff61a6afce.png)
Is the issue understood a by the team? Could I avoid this error by adding an artificial wait (say, 5 seconds) before running the SQL command?

**Comment by perrysk-msft** [comment]
Hi @Sean-Brown, 

Sorry but I think I have mistaken this issue with an another Invoke-Sqlcmd issue related to the latest SQL vNext CTP where we had to replace Invoke-Sqlcmd with sqlcmd. As you mentioned, I believe you can avoid this issue by adding an artificial wait before running the SQL command. Please let me know if the wait resolves this issue, otherwise we'll investigate further.

Thanks,
Perry

**Comment by Sean-Brown** [comment]
I added an artificial wait of 5 seconds and it succeeded 3/3 times.

**Comment by perrysk-msft** [comment]
Thanks @Sean-Brown!
