### ISSUE TITLE
:latest and Dockerfile do not match.

### ISSUE THREAD

**Issue by Ariwari** [Microsoft/mssql-docker#108]
The Dockerfile found at https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-express/dockerfile does not build to same container image as the container image that is received by running a container with "microsoft/mssql-server-windows-express".

The containers that use the Dockerfile container image start up and stop after a few seconds. The containers using a pull "microsoft/mssql-server-windows-express" container image stay alive.

**Comment by perrysk-msft** [comment]
Thanks @Ariwari! 

We are currently looking into reproducing this behavior on our end so we can understand and resolve the issue.

**Comment by Ariwari** [comment]
Thanks for the quick response @perrysk-msft! 

Something that I noticed is that the 2 containers I'm now running (from the 2 different container images) have a different Args when using docker iinspect <container>

The "microsoft/mssql-server-windows-express" containerimage has the following
"Args": [
"/S" 
"/C"
"powershell ./start -sa_password %sa_password% -ACCEPT_EULA %ACCEPT_EULA% -attach_dbs \\\"%attach_dbs%\\\" -Verbose"
]

The containerimage built with the linked Dockerfile has:
"Args": [
    "-Command",
    "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
    ".\\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \\\"$env:attach_dbs\\\" -Verbose"
]'

**Comment by perrysk-msft** [comment]
:latest and Dockerfile now match.
