### ISSUE TITLE
sqlservr: This program requires a machine with at least 3250 megabytes of memory.

### ISSUE THREAD

**Issue by tareqkabani** [Microsoft/mssql-docker#114]
after install container this message show to me

**Comment by vin-yu** [comment]
you need to set docker preference with computing resources of at least 3.5GB in order to run SQL Server today. if youre on a mac, click on the docker icon>preferences>advanced to set the memory

**Comment by twright-msft** [comment]
Same is true if you are using Docker for Windows.

**Comment by thiagolunardi** [comment]
I just followed what @vin-yu  said.

![image](https://user-images.githubusercontent.com/5428523/27728844-bebd6ac2-5d83-11e7-8fbf-5b8cc42c58fb.png)

**Comment by thiagolunardi** [comment]
Here is the documentation:

https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-docker#a-idrequirementsa-requirements-for-docker

> **Important**
> 
> The default on Docker for Mac and Docker for Windows is 2 GB for the Moby VM, so you must change it to 4 GB.
> 
> **Docker for Mac procedure**
> 
> -  Click the Docker logo on the top status bar.
> - Select Preferences.
> - Move the memory indicator to 4 GB or more.
> - Click the restart button at the button of the screen.
> 
> **Docker for Windows procedure**
> 
> - Right-click on the Docker icon from the task bar.
> - Click Settings under that menu.
> - Click the Advanced Tab.
> - Move the memory indicator to 4 GB or more.
> - Click the Apply button.
> 
>

**Comment by twright-msft** [comment]
We are investigating removing/lowering the memory requirement, but for now this is how to configure things to work with the current memory requirements.

**Comment by chrismcv** [comment]
@twright-msft any update on lowering this requirement? We currently run multiple instances per host, and this is effectively a show-stopper for us.

**Comment by twright-msft** [comment]
Yes, we are going to lower it to 2 GB in an upcoming cumulative update (CU).  Can't remember if it is CU1 or CU2.  Within the next two months though for sure.  Is 2 GB low enough for your use case @chrismcv?

**Comment by chrismcv** [comment]
@twright-msft- thanks for the quick response. Sadly its not, we currently run 40 instances of SQL Express on a 12GB Windows Server, each with about a 250MB footprint. Appreciate our use-case isn't mainstream, but separate instances allow us to firewall each port individually.

**Comment by bleissem** [comment]
@twright-msft 
I have a VM that has only 1 GB Ram (only for development use). 
So how about reducing the limit down to 1 GB Ram or less ? 
Or use temp storage even if it is very slow. It's only for dev purpose.

**Comment by kspearrin** [comment]
@twright-msft That's great news. The lower memory requirement the better for us as well. Right now it's a bit ridiculous.

**Comment by kspearrin** [comment]
@twright-msft I am guessing this wasn't reduced in CU1. Will it be in CU2? Any ETA?

**Comment by twright-msft** [comment]
Yes, in CU2.  First part of Dec.

**Comment by kspearrin** [comment]
@twright-msft I see CU2 has now landed. What are the new minimum RAM requirements? DockerHub still says 3.25 gb.

**Comment by twright-msft** [comment]
Docker Hub is updated now.  I've sent in a request to have the Microsoft docs updated as well.

**Comment by galvesribeiro** [comment]
@twright-msft please not that there are no such thing as RAM settings if you are using Linux containers on Windows:
![image](https://user-images.githubusercontent.com/4714040/34497757-006f4022-efe6-11e7-93d7-7955629a276b.png)

That means we are running linux containers **directly** on Windows and not thru that Hyper-V VM... How can we workaround that?

Thanks

**Comment by twright-msft** [comment]
Hmm... that's interesting. I still see mem and cpu settings in my Docker settings.  I dont see that Enable Linux containers checkbox though.  What version are you using?
This is what my Docker About says: Version 17.09.1-ce-win42 (14687)

**Comment by galvesribeiro** [comment]
![image](https://user-images.githubusercontent.com/4714040/34498206-bf2f85a2-efe7-11e7-9aa0-406e33b0f499.png)
Too old I guess

**Comment by twright-msft** [comment]
Can you change the memory in the Moby Linux VM via Hyper-V?

**Comment by galvesribeiro** [comment]
@twright-msft That is what I'm trying to say. When running on `Linux container for Windows` we don't have a Hyper-V VM anymore. This new mode allow Linux containers to run _natively_ on Windows so no VMs whatsoever.

**Comment by twright-msft** [comment]
OK I understand now.  Sorry, I dont normally run my Linux containers on Windows.  I use Mac for that.  I'm all upgraded to 1709 + the latest Docker edge version like you have and I confirm I have the same problem.  Looks like this is a known limitation of Linux Container on Windows (LCOW).

https://github.com/docker/for-win/issues/1357
https://github.com/Microsoft/opengcs/issues/145

It sounds like it is in the backlog but I dont know when it will be available yet.

If you need to do this for now I suggest reverting back to the Stable build of Docker for Windows with the configurable Moby VM.

**Comment by andriysavin** [comment]
Hi everyone. 2GB is nice, but I believe you can do better! It's too high requirement for SQLExpress edition, which for some applications can be run on a much lower amount of RAM (e.g. on a Synology NAS with total 1 GB of RAM). For Express, there should be no artificial limitations, 512MB seems to be more than enough for many small-scale scenarios. Any hope for this?

**Comment by twright-msft** [comment]
We will keep working on reducing the minimum requirements over time.

**Comment by opencoder92** [comment]
@twright-msft 
Hi, Why does SQL server require 2 GB of physical ram to run in linux? Why is there such a limit? I can have a small development server with only 1 GB physical ram + 2 GB or more of swap and I would be OK with some lags and slowness. Doesn't it make sense to take both physical ram + swap memory into account?

**Comment by pccruiser** [comment]
My frustration is the inability to run a container above 2GB of RAM on the Windows side.  As part of a development workflow it would be wonderful to have a container running SQL (SQL Linux via LCOW) and then you can run your ASP.Net applications that requires Windows running as well.

As it stands this very needed workflow is not possible simply because of a memory limitation on the container itself. I have 32GB of RAM so I can allocate plenty - if it would just let me!

If I switch to Linux containers I can change the RAM in the Docker Settings or via Hyper-V Manager. But on the Windows side I'm SOL.

**Comment by Rainmaker52** [comment]
It seems there is no way to influence the amount of memory that gets allocated. Not even with the -m switch. At least, not while running Windows containers:

> PS C:\> docker run --platform=linux -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=MyPasswordIsSafe" `
> >>    -p 1433:1433 -m 4g `
> >>    -i mcr.microsoft.com/mssql/server
> sqlservr: This program requires a machine with at least 2000 megabytes of memory.
> PS C:\>

Would it be a good idea to have an environment variable to skip the check in its entirety? Something like -e "YesIKnowPerformanceWillSuckButYourMemoryDetectionIsOff=Y"

**Comment by twright-msft** [comment]
There is a -e UseMoreThan2MeaslyGBofRAM=Y thing in the works. :)  I've talked to the LCOW team about it and it is in internal preview now.  Just to be clear - this is an LCOW problem not a SQL problem.  The underlying VM that LCOW creates that the SQL container runs in cannot be bigger than 2GB right now.

**Comment by jphellemons** [comment]
> 
> 
> We will keep working on reducing the minimum requirements over time.

It would be epic if we could run it from a docker container on a Raspberry pi 3 (1 gb ram)
People suspect that the Raspberry pi 4 might have 2gb of ram https://technofizi.net/raspberry-pi-4-release-date-specs-rumours/

**Comment by justin2004** [comment]
why can't sqlservr just use swap space if it is available?

i have 1G physical RAM and 7G swap space but sqlserver still says:
"sqlservr: This program requires a machine with at least 2000 megabytes of memory."

and we can see what it is doing:
...
sysinfo({uptime=3532, loads=[20512, 54240, 90400], totalram=1037512704, freeram=308752384, sharedram=0, bufferram=0, totalswap=7516188672, freeswap=7420506112, procs=165, totalhigh=0, freehigh=0, mem_unit=1}) = 0
...

so it doesn't just try to malloc and fail or something but rather it looks for physical ram (using the sysinfo system call) and makes a value judgement for me. e.g. "your swap space isn't good enough for me."

**Comment by justin2004** [comment]
I made a docker image that works around this memory limitation (policy):
https://github.com/justin2004/mssql_server_tiny

**Comment by dnzhnshn** [comment]
ı waste lots of time about this issue and ı couldnt find any solution. maybe  @justin2004 ' image can solve this problem .. Does anyone try this ?

**Comment by benbendemo** [comment]
I just have a 2GB physical memory machine with centos 7.7, while I am install SQL Server 2019, i got this "sqlservr: This program requires a machine with at least 2000 megabytes of memory.
/opt/mssql/bin/sqlservr: This program requires a machine with at least 2000 megabytes of memory." How can i get this figured?

**Comment by justin2004** [comment]
@benbendemo 
did you try https://github.com/justin2004/mssql_server_tiny ?

**Comment by luilver** [comment]
In my case without Docker CE installed but Docker Quickstart Terminal + VirtualBox it was within VirtualBox Manager where I had to increase RAM size as shown:
![imagen](https://user-images.githubusercontent.com/681020/68652658-91eacb00-04ef-11ea-8443-74b1a5eeafc5.png)
Hope this could be helpful for someone with the same problem I had.

**Comment by watfordgnf** [comment]
@twright-msft any updates?

**Comment by jaddie** [comment]
This certainly needs to have something in it to override such an OTT check, people who in theory should be dealing with a piece of software at this level should be able to understand the risks of ignoring the 2GB requirement. To not have the ability especially on Linux to override it is as said earlier as ridiculous as a 2GB check. I've just had to turn dynamic memory off on a hyper-v VM & set the ram to 2GB to pass the check & now I shall go & revert it back to dynamic etc, this is an opportunity for mssql to compete with mysql and mariadb for once, a stupid check like this would be an instant show stopper.

**Comment by keber** [comment]
This limit sees to be per instance, so having 3 sqlservr instances in the same vm requires at least 2 GB so each can validate required memory amount. I'm running a postgres in the same machine and the 4 all together are using no more than 512 MB, so wasting 5.5 GB otherwise available is painful but 'required'.
