### ISSUE TITLE
Support for Analysis Services in SQL 2016 Windows container

### ISSUE THREAD

**Issue by Hugoberry** [Microsoft/mssql-docker#118]
Wasn't quite sure how to enable SSAS feature in the mssql-server-windows-developer container. The documentation for [SQL2016 on Windows Core](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-on-server-core) says that it's available.

**Comment by perrysk-msft** [comment]
@Hugoberry, Although SSAS are supported in Windows Server core are not currently supported in Windows Server containers. We'll have to update that page to include a section with SQL Server in Windows containers supported features.

**Comment by david-garcia-garcia** [comment]
I prepared a dockerfile to build a Windows Container that exposes SSAS through HTTP: 

https://github.com/david-garcia-garcia/windowscontainers/tree/master/sqlserver2022as
