### ISSUE TITLE
Visual Studio 2017 - An incompatible SQL Server version was detected

### ISSUE THREAD

**Issue by kemelinux** [Microsoft/mssql-docker#119]
When I try to add the **Linux based SQL server 2017 from Microsoft** to the list of SQL Servers in the **SQL Server Object Explorer** then Visual Studio returns the error  **An incompatible SQL Server version was detected**.

Steps to reproduce: 

1. In the SQL Server Objet Explorer : enter the connection parameters of the database.
   The list of possible databases is found !
<img width="447" alt="screen shot 2017-07-07 at 13 01 44" src="https://user-images.githubusercontent.com/16566312/27955329-9678732c-6314-11e7-9213-e95f1123d599.png">

2. Select a database and press the **Connect** button.

Now the error is thrown.

But I can connect to the database via **Tools > Connect to database...**
And I can also connect to the database with **SQL Server Management Studio v17.1**.

I have already tried installing the latest version of:
- SQL Server Data Tools 17.1
- Data-tier Application Framework 17.1

Executing the statement SELECT @@VERSION on the database returns me: 
Microsoft SQL Server 2017 (CTP2.1) - 14.0.600.250 (X64)   May 10 2017 12:21:23   Copyright (C) 2017 Microsoft Corporation. All rights reserved.  Developer Edition (64-bit) on Linux (Ubuntu 16.04.2 LTS)

I am running Visual Studio 2017 on a Windows 10 64-bit.

**Comment by scottkon** [comment]
I checked and VS2017 does not yet support SQL 2017 CTP or RC builds.  The support is being worked on and should roll out in a VS preview release later this month and an update within a couple months.

**Comment by ooples** [comment]
Where can I read more information on this issue?

**Comment by kemelinux** [comment]
The only information from Microsoft that I found on this is confirming that it does not yet support SQL 2017 : https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt#use-ssdt-in-visual-studio-2017. I guess we will have to wait a couple of months. I will close the issue here as it is not a Docker issue.
