### ISSUE TITLE
Enable SQL Server 2017 Agent on docker

### ISSUE THREAD

**Issue by ashwanipnd10** [Microsoft/mssql-docker#124]
Hi Team, I want to know whether Microsoft has launched image of MS-SQL Server 2017 Agent's image for docker or not. If not, what is the realize date? IF yes, can you send me the link, where I can find the installation steps.

**Comment by twright-msft** [comment]
Current thinking is that we will not have an image with Agent pre-built into it.  Please see/contribute to the discussion on this issue:  https://github.com/Microsoft/mssql-docker/issues/27
Note: that discussion is re: Agent, full text search, etc. on a Linux container.  If you are interested in SQL Server Agent in a Windows container, we know there are some issues with that and we don't have an ETA in the next six months to fix that.  We recommend using the Linux containers for now.
