### ISSUE TITLE
Special Character Password for Windows:  Personal Path of Tears LOL

### ISSUE THREAD

**Issue by marktab** [Microsoft/mssql-docker#129]
Silly me for trying out both SQL Server 2017 in Linux and Windows on my work machine.  Sure, I had to update to Windows 10 Creators (Anniversary) edition as a prerequisite.

However, while the Linux version takes my password's leading ampersand, the Windows version did not:  leading me into an alternative universe.  Being a newbie to Docker, I simply went through the troubleshooting guide, even experimenting with data volume containers (which almost worked):  but all too late for my discover of the log message, since all the previous experiments messed up my installation and landed me with the blue screen of death.  I refreshed with a Docker factory reset.

IMO this issue is easily reproducible -- and a solution would have a consistent methodology for interpreting password characters whether Linux or Windows.

So, what type of initiation currently works?

`docker run -e "ACCEPT_EULA=Y" -e "sa_password=NoAmpersandForYou" -e 'MSSQL_PID=Developer' -p 1402:1433 -d microsoft/mssql-server-windows`

**Comment by uc-msft** [comment]
Special characters in Windows command-line can be escaped using ^. So try: "^&mypassword".

**Comment by marktab** [comment]
Thanks UC:  I will make a note should I need that option in the future.
