### ISSUE TITLE
SQLPackage on windows not publishing to SQL Docker on linux

### ISSUE THREAD

**Issue by jbful** [Microsoft/mssql-docker#132]
I am trying to automate deployment to mssql-docker on linux.

I understand in RC1, sqlpackage was removed, so  I am using sqlpackage on my physical windows machine to attempt to publish to msssql-docker (linux) running RC1.

I have tried both connecting to an existing database and trying to have it create a new database, both are giving me the same error.

Here is the the script I am running:

c:\Program Files (x86)\Microsoft SQL Server\130\DAC\bin>sqlpackage /Action:publish /SourceFile:"c:\DACPAC\DEVDB01\MyDB.dacpac" /tsn:192.168.56.101 /tu:sa /tp:***** /tdn:MyDB /p:CreateNewDatabase=TRUE

Here is the error i get in /var/opt/mssql/log/ 
_Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'MyDB'_

This same error is received whether I am updating an existing or trying to create a new DB from a dacpac.

**Comment by jbful** [comment]
Nevermind, when i upgrade to latest tools, the deploy works.

**Comment by ben-biddington** [comment]
Hmm, I am getting this on Windows 10 with Windows image, errors like:

```
08/22/2017 12:09:06,Logon,Unknown,Error: 18456<c/> Severity: 14<c/> State: 38.
08/22/2017 12:08:56,Logon,Unknown,Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Archive'. [CLIENT: 172.21.64.1]
```

Tried both publishing from source (MSBuild) and dacpac (SqlPackage)
