### ISSUE TITLE
next milestone?

### ISSUE THREAD

**Issue by mi-hol** [Microsoft/mssql-docker#134]
For the community knowing the planned milestone(s) is very usefull.
Only an outdated milestone is published for this repository currently :(
'SQL Server vNext CTP 2.0
 Past due by 3 months   Last updated 4 months ago
Release target date: mid April 2017'

Would it be feasible to update it?

**Comment by twright-msft** [comment]
Sure!  We'll do our best to keep things updated.  I added the next couple of milestones.  I'll add more once I can disclose more of the roadmap publicly.
