### ISSUE TITLE
License issue for linux

### ISSUE THREAD

**Issue by miguelrod** [Microsoft/mssql-docker#137]
Hi,

I've been testing mssql-docker for linux as a solution for development and Codeship continuous integration.
I've read a lot about the topic and from what I gathered, this image is not a developer or express edition so needs a paid license to be used for more than N days. There are images of the developer/express but only for windows.
So, my questions are:
- Am I correct in assuming that I need a licence?
- Do I need a licence for every developer or the same is valid for 10 devs?
- Are there express / developer containers for linux? Will there be in the future?

Thanks in advance.
Miguel R.

**Comment by adamtester** [comment]
You can use `-e 'MSSQL_PID=Developer'` to remove the warning, obviously for developer use.

**Comment by vkynchev** [comment]
@adamtester On my dev machine mssql logs `This is an evaluation version.  There are [xxx] days left in the evaluation period.` even with `MSSQL_PID=Developer` set... Any ideas?

**Comment by twright-msft** [comment]
Every edition is timebombed up until the GA release.  When you upgrade to the GA release only Evaluation Edition will be timebombed.  Developer will no longer be timebombed.

**Comment by vkynchev** [comment]
@twright-msft Thanks! So this counter counts to the GA release or a short period after it?

**Comment by twright-msft** [comment]
It counts down from 180 days from the **build** date of that release (CTP2.0, RC2, etc).  The idea is to encourage people to keep upgrading through the CTP/RC process and not lag behind on old builds.

**Comment by vkynchev** [comment]
Okay... Thanks for the support & fast replies!

**Comment by twright-msft** [comment]
Now that GA is out, you should be good to go!  Please be sure to pull/run the :2017-GA or newer tag. Also, note that you can specify the edition that you want to use by passing the env var MSSQL_PID=<edition name>.  Example: -e MSSQL_PID=Express.
Closing out this issue.
