### ISSUE TITLE
Auto-mount attach_dbs

### ISSUE THREAD

**Issue by riker09** [Microsoft/mssql-docker#138]
I have a project with lots of databases. Like, a lot. Is there a way to auto-mount every *.mdf (and *.ldf) file that can be found in attach_db, maybe some kind of wildcard? Could the dbName be derived from the filename?

I have something like this in mind:
```
attach_db="{ 'auto': true, path: 'C:\\path\\to\\volume\\'}"
```

**Comment by perrysk-msft** [comment]
@riker09 Currently, this is not supported. 

Maybe you could map the host directory that contains all the db files to a sql container volume and then write a custom PS script to loop through and attach each db.
