### ISSUE TITLE
docker.io/microsoft/mssql-server-linux fails to start in Openshift when Persistent Storage volume is added

### ISSUE THREAD

**Issue by jplanganla** [Microsoft/mssql-docker#145]
We have been trying to test with the linux docker image on Red Hat Openshift.  we can pull the image and start a container with no storage, but when we add a Persistent Volume is crashes with error 87.  The Persistent volume is provisioned from NFS.

I have attached startup logs from a bad startup and a good startup of the same container for reference.

[mssql_cntr_bad_with_storage.txt](https://github.com/Microsoft/mssql-docker/files/1211743/mssql_cntr_bad_with_storage.txt)
[mssql_cntr_good_no_storage.txt](https://github.com/Microsoft/mssql-docker/files/1211744/mssql_cntr_good_no_storage.txt)

Thanks! any help is appreciated.

**Comment by twright-msft** [comment]
This is a known issue with NFS/Samba in RC1 and RC2 that is fixed in post-RC2 releases.  The next public release will resolve this issue.  Please use local storage for now.  Sorry for the inconvenience.

**Comment by jplanganla** [comment]
Thank you so much!

**Comment by twright-msft** [comment]
Alternatively, you can use the imaged tagged as :ctp1-4.  That was an image created before the bug was introduced.
