### ISSUE TITLE
Localdb inside docker

### ISSUE THREAD

**Issue by Ducatel** [Microsoft/mssql-docker#146]
Hi everybody,

I'm trying to use `localdb` under my linux host (try to replace SQLite database).

According to the [Release note](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes), `localdb` seems to be supported inside linux env. (`localdb` is not present in the list of "Unsupported features and services" ).

But I cannot found anywhere the executable `sqllocaldb` (which I should use to start a `localdb` instance) in the official docker image.
And also, didn't found how install it in debian or ubuntu.

So is it possible to run localdb instance under linu_x host ?
If yes, how I can install it ?

Thanks in advance for your help

**Comment by twright-msft** [comment]
Localdb is really just a lightweight way to run SQL Server on a Windows PC/dev machine.  The rough equivalent of that is to run SQL Server in a Linux container.  So - there isnt a localdb option on Linux.  It's just SQL Server.  In a container.  :) . If you are looking for a lightweight, _installable_, free option you can install SQL Server and set it to Express Edition.

**Comment by Ducatel** [comment]
Ah, ok, localdb will be implemented for linux in the future ? 

I search to replace SQLite (because it cannot allow multithread write) and for me deploy an SQLServer it's like killing a fly with a bazooka :laughing:

**Comment by twright-msft** [comment]
No, we dont have any plans to make a localdb version of SQL Server for Linux.  SQL Server on Linux is about as small as SQL Server can get.  The package size is pretty small.  The container image size is pretty small.  The space on disk is small.  We are working on lowering the minimum required HW specs.  Express Edition is free.  We broke out the engine into its own package that doesn't include optional components like full text search, agent, HA, etc.  So, what you see on Linux is about as small as we can get.  It's like killing a fly with a shotgun.  Probably still overkill, but not as big as a bazooka. :)

**Comment by Ducatel** [comment]
Ok thanks for your explanation :D
I will try to use the shotgun without making a lot of damage 😆
