### ISSUE TITLE
Password: Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Login failed for user 'sa'..

### ISSUE THREAD

**Issue by ryandisaskara** [Microsoft/mssql-docker#15]
i've start the instance by run the  following command
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=mystrongpassword' -p 1433:1433 -d microsoft/mssql-server-linux
 
but after several attempt to connect it keept throw error 
Password: Sqlcmd: Error: Microsoft ODBC Driver 11 for SQL Server : Login failed for user 'sa'..

 checked the log in kinematic 

Error: 18456, Severity: 14, State: 7.
2017-01-13 14:09:30.60 Logon       Login failed for user 'sa'. Reason: An error occurred while evaluating the password. [CLIENT: 192.168.99.1]

i try to connect using this command 
sqlcmd -S 192.168.99.100 -U sa -P 'mystrongpassword'
any help?

**Comment by ryandisaskara** [comment]
turn out the password not strong enough
after changed the SA password  and restart the container i can login to the server.

**Comment by morontt** [comment]
thanks!
