### ISSUE TITLE
Server Collation for Windows Container

### ISSUE THREAD

**Issue by mac2000** [Microsoft/mssql-docker#156]
What is a "right" way to change server collation?

At moment it seems that only possible way is to create own image from scratch defining collation while installing SQL Server

Trying to bypass issue with [this instruction](https://www.mssqltips.com/sqlservertip/3519/changing-sql-server-collation-after-installation/) but unfortunately `sqlservr` wont exit when it is done

May be there is a chance that base image will have already downloaded and extracted installation media, so we will be able to at least start from it and install SQL Server with required parameters, two more gigs on this image probably wont be a deal breaker or it might be separate image for enthusiasts who need this so will be able to get always fresh version for dev needs

Thanks in advance

**Comment by twright-msft** [comment]
One way is to use the Dockerfile we've made available on GitHub to build your own image and pass in the command line parameter you want. 
https://github.com/Microsoft/mssql-docker/tree/master/windows
The SQLCOLLATION command line parameter needs to be passed to setup.exe.
More info:
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-2016-from-the-command-prompt

**Comment by twright-msft** [comment]
Just for completeness.... On the Linux side we have an env var to set this at docker run time.  MSSQL_COLLATION

**Comment by mac2000** [comment]
Yep, I can confirm that, `MSSQL_COLLATION` works as expected on Linux containers and is awesome (hope somewhere in future to see such thing in windows containers)!

For anyone else fighting with collations - you need to build your own image by at least add `/SQLCOLLATION=Cyrillic_General_CI_AS` to setup.exe but if you are one journey of discovering building your own images I bed you will not stop on that :)

Thanks for response, at least know that I'm going in a right direction, closing issue

BTW: Hope to see some descriptions in repo readme for people like who also need to do such things
