### ISSUE TITLE
Use ServiceMonitor instead of infinite loop

### ISSUE THREAD

**Issue by dermeister0** [Microsoft/mssql-docker#16]
Use ServiceMonitor utility to replace the code

    Write-Verbose "Started SQL Server."
    while ($true) { Start-Sleep -Seconds 3600 }

to this:

    ENTRYPOINT ["C:\\ServiceMonitor.exe", "MSSQL$SQLEXPRESS"]

Example:
https://github.com/Microsoft/iis-docker/blob/master/windowsservercore/Dockerfile

Don't use *CMD* statement, use *RUN* instead. It'll allow to execute custom scripts after SQL Server start (to create DB, for example).

**Comment by dermeister0** [comment]
https://github.com/Microsoft/mssql-docker/issues/2
https://github.com/Microsoft/mssql-docker/issues/11

**Comment by dermeister0** [comment]
Why is it closed? The issues are not fixed.

1. Docker container does not die if SQL Server service is stopped.
2. The script is still executed in CMD statement, it does not allow custom command to run.

**Comment by jelster** [comment]
@dermeister0 - according to https://github.com/Microsoft/iis-docker/issues/1 work to make servicemonitor.exe source available seems to still be ongoing. TBH, I'd never heard of `ServiceMonitor.exe` until I read your OP.

regarding:
