### ISSUE TITLE
The OLE DB provider "OraOLEDB.Oracle" has not been registered.

### ISSUE THREAD

**Issue by guibaldissera** [Microsoft/mssql-docker#160]
When I use mssql-docker, is there any way to use Database Link with Oracle?
In default, the OLE DB provider for Oracle isn't avaliable because Client or ODAC need to be installed as well.
How we can resolve this?

**Comment by twright-msft** [comment]
Are you using the mssql-server-linux image?  If so, this is a limitation of SQL Server on Linux right now.  We dont have a way to load these kinds of DLLs into the SQL PAL.

**Comment by guibaldissera** [comment]
Yes, mssql-server-linux. 
So, and in mssql-server-windows (developer or express), this is possible?
Thank you!

**Comment by twright-msft** [comment]
It might be possible in Windows, but we havent tested it yet.

**Comment by guibaldissera** [comment]
Ok, thank you!
