### ISSUE TITLE
Please list tags on docker hubpage

### ISSUE THREAD

**Issue by zippy1981** [Microsoft/mssql-docker#167]
Most docker hub pages have a supported tags section up top. Example, [mysql](https://hub.docker.com/_/mysql/).

![image](https://user-images.githubusercontent.com/146930/31101828-55b1c1e0-a79d-11e7-9f9f-8333c327c6e9.png)

Microsoft SQL Server docker images should use this convention.

**Comment by twright-msft** [comment]
Great suggestion.  Done!
