### ISSUE TITLE
Latest SQLServer Image (2017) is not connecting outside of container

### ISSUE THREAD

**Issue by shahzadmasud** [Microsoft/mssql-docker#169]
I am unable to connect my newly created SQL Server 2017 instance from outside docker instance. I have tried to look into this problem using other blogs & issues, but no luck. I am trying to access SQL server from MySQL Workbench or other sql explorers. Event sql command line is also not working.

https://github.com/Microsoft/msphpsql/issues/302

**Comment by bizmate** [comment]
What do you mean ? 'I am unable to create my newly created SQL Server 2017 instance from outside docker instance.' Have you created it or not. Do you have an instance running somewhere? Also why using a mysql tool for mssql. Use an mssql client and if you need help please add all the details of what you have tried to do and what the error is

**Comment by amrlafi** [comment]
MySQL Workbench will only work with MySQL database. This container use SQL server. You can use [SSMS](https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-ssms) instead.

**Comment by shahzadmasud** [comment]
@bizmate I want to connect to this newly created instance on my macbook, but it is only accessible from the command line inside the container, while not accessible to any application on other dockers. 
@amrlafi There is a migration wizard, that help in connecting with any database. I wanted to use that one for inter database connectivity.

**Comment by twright-msft** [comment]
did  you docker run .... -p 1433:1433?

**Comment by shahzadmasud** [comment]
docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=P@ssw0rd' -e 'MSSQL_PID=Developer' -p 1401:1433 --name sql1 -d microsoft/mssql-server-linux:2017-latest

**Comment by bizmate** [comment]
@shahzadmasud when you open a ticket you should really add as much info as possible. How do you spin other containers? Are you using docker compose? In your docker run you are exposing the port on the host on 1401 ... are you connecting on this port?
In anything you attempt could you please show the command line output? Also could you pile all this info in your first post in this thread so anyone that comes and reads the issue doesnt have to scroll down and read the whole story?

If you use docker-compose do you know you can just reference other containers by their service name?
If you dont you docker compose do you know how to go and get the ip of the docker container to connect to it from the other containers? If you use multiple containers you should really use docker-compose or a stack.

**Comment by twright-msft** [comment]
Since you have exposed the 1433 port on your host as 1401 are you trying to connect to port 1401?

**Comment by shahzadmasud** [comment]
Thank you @bizmate and @twright-msft, I figure out the issue. It was a wrong port, I was trying with 1433, while it is exposed on 1401. 

@bizmate For your suggestion to be as comprehensive in exploring question. Noted.
