### ISSUE TITLE
This program requires a machine with at least 3250 megabytes of memory.

### ISSUE THREAD

**Issue by bdschaap** [Microsoft/mssql-docker#172]
I receive the error message below on macOS Sierra even after increasing memory to 4 GB within Docker preferences.

**Command**
docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=<YourStrong!Passw0rd>' -e 'MSSQL_PID=Developer' -p 1401:1433 --name sql1 -d microsoft/mssql-server-linux:2017-latest

**Result**
sqlservr: This program requires a machine with at least 3250 megabytes of memory.

**Comment by twright-msft** [comment]
Did you restart Docker?

**Comment by cheenamalhotra** [comment]
@bdschaap You can go to Docker Icon > Settings > Advanced and modify Memory and CPU allocated to Docker Application.
