### ISSUE TITLE
Unexpected argument. Enter '-?' for help.

### ISSUE THREAD

**Issue by Flodu31** [Microsoft/mssql-docker#174]
Hello,
I tried to mount/create automatically a database (it works 3 months ago).
I executed this command:
`docker run -d -p 1433:1433 -v C:/Users/florent/Desktop/DEMO08/DB/:C:/Temp/ --env attach_dbs="[{'dbName':'Orchard','dbFiles':['C:\\Temp\\Orchard.mdf','C:\\Temp\\Orchard_log.ldf']}]" -e sa_password=‘Welcome123!’ -e ACCEPT_EULA=Y --name sqlserver microsoft/mssql-server-windows:latest`
In logs of the container I've this:

> VERBOSE: Starting SQL Server
VERBOSE: Changing SA login credentials
VERBOSE: Attaching 1 database(s)
VERBOSE: Invoke-Sqlcmd -Query sp_detach_db "Orchard";CREATE DATABASE "Orchard"
ON (FILENAME = N'C:\Temp\Orchard.mdf'),(FILENAME = N'C:\Temp\Orchard_log.ldf')
FOR ATTACH ;
Sqlcmd: 'Orchard";CREATE DATABASE "Orchard" ON (FILENAME = N'C:\Temp\Orchard.mdf'),(FILENAME = N'C:\Temp\Orchard_log.ldf
') FOR ATTACH ;"': Unexpected argument. Enter '-?' for help.
VERBOSE: Started SQL Server.

Any idea?
Thanks.
Florent

**Comment by cubed-it** [comment]
I have the same error... Please fix!

**Comment by pbering** [comment]
#173 seems like it's the same (see for workaround)

**Comment by joshuashort** [comment]
Just ran into this issue; running the generated `CREATE DATABASE` statement directly with `sqlcmd` throws the same error. For some reason, removing the double quotes from around the database name makes it run -- I though double quotes were valid?

**Comment by Flodu31** [comment]
Hi,
I tried your solution but doesn't work:

> At line:1 char:103
> + ... top/DEMO08/DB/:C:/Temp/ --env attach_dbs=[{'dbName':'Orchard','dbFile ...
> +                                                        ~~~~~~~~~~
> Unexpected token ':'Orchard'' in expression or statement.
> At line:1 char:113
> + ... op/DEMO08/DB/:C:/Temp/ --env attach_dbs=[{'dbName':'Orchard','dbFiles ...
> +                                                                 ~
> Missing argument in parameter list.
>     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : UnexpectedToken

Florent

**Comment by kolomiets** [comment]
Faced the same problem with the latest -express and -developer images.
The only 2017 image that worked for me was [microsoft/mssql-server-windows](https://hub.docker.com/r/microsoft/mssql-server-windows/), but looks like it was dropped from DockerHub recently.

Our build infrastructure literally crashed because of this problem :(

**Comment by joshuashort** [comment]
@Flodu31 I mean the double quotes that get wrapped around the dbName in `start.ps1` (https://github.com/Microsoft/mssql-docker/blob/bcea633a5c1557b9961e805220d89c03c76f89a6/windows/mssql-server-windows-developer/start.ps1#L72)

This wrapping wasn't always happening, looking at the history of that file.. but some kind of quoting is required for names with spaces or other weird characters. Maybe changing the double quotes to square braces would make sqlcmd happy.

**Comment by perrysk-msft** [comment]
[Update] Sorry for the delayed response on this issue. There was a bug in the ps script that we believe is now fixed. The latest developer and express images should now work with the attach_dbs environment variable.
 - microsoft/mssql-server-windows-express (https://hub.docker.com/r/microsoft/mssql-server-windows-express/)
- microsoft/mssql-server-windows-developer (https://hub.docker.com/r/microsoft/mssql-server-windows-developer/)

Could you please verify that this problem is fixed on your end before we close this issue?

Thanks,
Perry

**Comment by joshuashort** [comment]
Thanks @perrysk-msft! It works for me now, but I see the following in the logs when attaching:

`Msg 15010, Level 16, State 1, Server 1FD90C3F14BA, Procedure sp_detach_db, Line 40
The database 'sign' does not exist. Supply a valid database name. To see available databases, use sys.databases.`

I think the statement at https://github.com/Microsoft/mssql-docker/blob/cd10b8f345eb07feedf1a31759e556f41fff2185/windows/mssql-server-windows-developer/start.ps1#L53 should have `IF EXISTS` before attempting to detach the database, not `IF NOT EXISTS`.

**Comment by perrysk-msft** [comment]
@joshuashort - Good catch! 

I'll rebuild and re-publish both the Express and Developer images by the end of today. I'll update this thread when this has been completed.

**Comment by perrysk-msft** [comment]
[update]
The updated images for Developer and Express with the "IF EXISTS" fix are now published on Docker Hub. 

Thanks again @joshuashort!

**Comment by joshuashort** [comment]
Thank you so much! I've tested our dev setup with the new version, and it's working beautifully. It'd be nice to have a hook to run some custom SQL or PowerShell, but this seems to fix the issue.

Great appreciated!

**Comment by Flodu31** [comment]
Hello,
Ok I've the same problem with the default image (who is not available anymore on Docker Hub).
But it works with the express version.
Thanks for the update.
Florent
