### ISSUE TITLE
mssql-server-windows-developer image missing tag for latest cumulative version of SQL 2017

### ISSUE THREAD

**Issue by riverar** [Microsoft/mssql-docker#177]
`mssql-server-linux` has tags to cover GA, GA + updates, and edge scenarios. `mssql-server-windows-developer` however only covers GA (with `:2017`) and edge (with `:latest`). We need a tag to cover GA + updates.

Requesting tagging be standardized across all images, or minimally commit to similar servicing for the `mssql-server-windows-developer` image.

**Comment by twright-msft** [comment]
We will do this as part of the upcoming CU1.  Thanks for pushing us to be consistent!

**Comment by wesclark** [comment]
The CU1 version of SQL Server 2017 has been pushed to the linux version, but not the Windows version.

**Comment by twright-msft** [comment]
The Windows CU1 image is out on Hub now too.

**Comment by riverar** [comment]
The Docker hub page is missing critical documentation as to what each tag corresponds to https://hub.docker.com/r/microsoft/mssql-server-windows-developer/

Assuming:
`latest` - Latest version of SQL Server 2017 available, incl. major upgrades
`2017-latest` - Latest cumulative update for SQL Server 2017, no major upgrades
`2017-GA` - Explicit GA version of SQL Server 2017
`2017-CU1` - Explicit Cumulative Update 1 version of SQL Server 2017
`2017` - Deprecated tag that currently points to 2017-GA? Or newer?
`[other tags]` - Older, explicit version tags
