### ISSUE TITLE
Missing microsoft/mssql-server-windows image

### ISSUE THREAD

**Issue by kolomiets** [Microsoft/mssql-docker#178]
Looks like **microsoft/mssql-server-windows** image was removed from DockerHub - the following link return 404 page:

https://hub.docker.com/r/microsoft/mssql-server-windows/

Image can't be pulled using docker CLI as well.

Is it a conscious decision or you are in progress of upgrade? I rely on this image and can't switch to *developer* or *express* images easily.

**Comment by twright-msft** [comment]
Now that we have hit General Availability for SQL Server 2017 we are releasing the Developer and Express Edition images on the other repos.
Depending on your use case please pull from these repos/tags now:
https://hub.docker.com/r/microsoft/mssql-server-windows-developer/tags/
https://hub.docker.com/r/microsoft/mssql-server-windows-express/tags/
