### ISSUE TITLE
Can't connect to a specified port

### ISSUE THREAD

**Issue by julielerman** [Microsoft/mssql-docker#187]
I'm on Windows.

I created one container on 1433 and can connect to the SQL Server easily by using localhost as my server name. I can do this at the command line, in VS Code and in Visual Studio 2017.

I created a second container from the image and specifed -p 1520-1520 

docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=Passw1rd -p 1520:1520 -d --name C2 microsoft/mssql-server-windows-developer

Its definitely running as per docker ps, but I can't connect to it at all.

I have tried:
localhost,1520
I got the Gateway  and IP address via docker inspect and tried those e.g.
172.25.48.1,1520
172.25.61.120,1520
It can't connect with "remote computer refused the connection".
I completely disabled Windows Defender and still have the problem.
I should be able to connect to both instances 
I've seen other issues and stackoverflow questions where people are doing this with no issues but I can't figure out what I'm doing wrong or if there is a real problem that isn't "between the chair and the keyboard"

**Comment by wesclark** [comment]
-p hostport:containerport

So, -p 1520:1433

**Comment by julielerman** [comment]
🙀
THANK YOU
So , yep, should have been a stackoverflow question.
