### ISSUE TITLE
SQL Server 2017 SP1

### ISSUE THREAD

**Issue by wesclark** [Microsoft/mssql-docker#189]
With the release of SP1 for SQL Server 2017, I assume the :latest tag will be updated with this service pack.  How do I get notified when this is available both for linux and Windows versions?  What do I watch?

**Comment by twright-msft** [comment]
There will not be "service packs" going forward.  There will only be Cumulative Updates (CUs).  Please see this blog post for more details.  https://blogs.msdn.microsoft.com/sqlreleaseservices/announcing-the-modern-servicing-model-for-sql-server/

Part of this change to modern servicing is more predictable releases. You can expect a new CU every month in the week of the 3rd Monday for the first year after a major release.  For years 2-5, there will be a quarterly CU that is also released in the week of the 3rd Monday.

You can use something like IFTTT to monitor the SQL Server Release blog RSS feed for release announcements:
https://blogs.msdn.microsoft.com/sqlreleaseservices/

**Comment by wesclark** [comment]
I meant CU#1 in my original question.  My question is how will I know when the docker images have been updated?  As of yesterday, at least, the Windows microsoft/mssql-server-windows-developer:latest was still RTM, not CU1.  What is the communicated channel for updates to the docker hub images?

**Comment by twright-msft** [comment]
The "communication mechanism" is the blog mentioned above.  When you see that happen you can look at the Tags tab on Docker Hub to see what the current tags are.
