### ISSUE TITLE
Unable to pull mssql-server-linux:2017-GA

### ISSUE THREAD

**Issue by stevespringett** [Microsoft/mssql-docker#196]
I have followed the checkout procedure for mssql-server-linux:2017-GA and am trying to pull the image. Every time I attempt to pull, I receive an authentication failure.

```bash
$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (sspringett): 
Password: 
Login Succeeded

$ docker pull store/microsoft/mssql-server-linux:2017-GA
Error response from daemon: unauthorized: authentication required
```

I checked the Docker config and it appears to be correct:
```json
{
	"auths": {
		"https://index.docker.io/v1/": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/17.09.0-ce (darwin)"
	},
	"credsStore": "osxkeychain"
}
```

I would really like to get MSSQL Server running on Docker 17.09.0-ce-mac35. Running it on macOS 10.12.6.

**Comment by twright-msft** [comment]
Hmm... I am having the same problem.  Not sure what is going on here.  Please pull microsoft/mssql-server-linux from Docker Hub for now. The image is the same so it doesnt really matter where you get it from.

**Comment by twright-msft** [comment]
I am getting the same error for other images on Store too so it must be a problem with Store at the moment.

**Comment by stevespringett** [comment]
Ok thanks for confirming. Glad to know I wasn't doing anything wrong. I attempted today and the issue appears to be resolved. Closing issue.

**Comment by asameer** [comment]
OK I am facing the same problem now it gave me authentication required , and I did login with the docker hub account 
note I am pulling the latest version

**Comment by Bhumikapd** [comment]
I am getting the same error when I try to pull the latest version of SQL server:
I am logged in with my docker id
Error response from daemon: pull access denied for icrosoft/mssql-server-linux, repository does not exist or may require 'docker login'
