### ISSUE TITLE
Restore a database on Linux docker 

### ISSUE THREAD

**Issue by wesclark** [Microsoft/mssql-docker#197]
Our linux Docker 2017 SQL Server is running in the cloud.  We want to restore an arbitrary, new database.  What is best way to do this?  How can you run a restore command using a file from another server?  Is SSH our only alternative?  Would I use filestream (although I'm gathering that doesn't work yet)?

**Comment by twright-msft** [comment]
When you say 'in the cloud' what do you mean by that (in detail)?  When you say 'a file from another server' do you mean that you are running a backup on another server and you end up with a .bak file?  If so, where is that other server (in detail)?

**Comment by wesclark** [comment]
Thanks for responding.  

We are an ISV.  We are using the Linux Docker SQL Server 2017 CU1 image in a continuous integration/test environment running in TeamCity in AWS.  A portion of our test suites, consisting of multiple Java test classes, are configured to run on SQL Server.  (We also support Oracle.)  Some of the tests are "upgrade" tests that start with a copy of the database from an earlier version of our product that must be restored at the beginning of the test.  The database is started on some virtual host in the cloud.  The test suite is running on another VM.  The test can checkout and unzip the SQL Server backup from a source control system.  So the problem is getting the backup file to be addressable from the database server.  

We just came up with a solution:  We modified the SQL Server docker image to include an HTTP service, and so with a host and a port, we can upload the backup file to the HTTP service, which can store the backup in the container's file system and be addressable by the restore command.  The suite can probably clean up at the end to conserve disk space.

Do you think this is a good solution?  Do you have any comments or suggestions?

**Comment by twright-msft** [comment]
Sounds like a great solution.  Another option is to periodically and automatically build images with your backup file in it and push the images to a private registry.  Then your CI process can pull the :latest or whatever image and use that for testing.  The backup file can be in the container and ready for restore on run or you could pre-restore it in the image so that it is ready to go whenever the container is run.

**Comment by wesclark** [comment]
We started to implement that approach, the the backups are allowed to change over time and we wanted a more dynamic solution.
