### ISSUE TITLE
Docker run command fails with Accept-Eula Agreement error

### ISSUE THREAD

**Issue by cheenamalhotra** [Microsoft/mssql-docker#199]
Commands executed: 

`$>docker pull microsoft/mssql-server-linux:2017-latest`
`$>docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=<my_password>' -p 1401:1433 --name sql2 microsoft/mssql-server-linux:2017-latest`

SQL Server does not start and fail with below error:

```
The SQL Server End-User License Agreement (EULA) must be accepted before SQL
Server can start. The license terms for this product can be downloaded from
http://go.microsoft.com/fwlink/?LinkId=746388.

You can accept the EULA by specifying the --accept-eula command line option,
setting the ACCEPT_EULA environment variable, or using the mssql-conf tool.
```
I have already accepted EULA in the 'docker run' command, is there anything missing?

**Comment by Jester98x** [comment]
Just to add that I am seeing the same issue today running Windows 10 and Docker 17.09.0-ce-win33 (13620) stable:
`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux:2017-latest`

all looks ok, then I run
`CONTAINER ID        IMAGE                                      COMMAND                  CREATED              STATUS                          PORTS               NAMES
a0f6e0c20f72        microsoft/mssql-server-linux:2017-latest   "/bin/sh -c /opt/m..."   About a minute ago   Exited (1) About a minute ago                       priceless_newton`

looking at the logs:
`docker logs a0f`

> The SQL Server End-User License Agreement (EULA) must be accepted before SQL
> Server can start. The license terms for this product can be downloaded from
> http://go.microsoft.com/fwlink/?LinkId=746388.
> 
> You can accept the EULA by specifying the --accept-eula command line option,
> setting the ACCEPT_EULA environment variable, or using the mssql-conf tool.

**Comment by twright-msft** [comment]
Try using double quotes instead of single.  See here:
https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker

**Comment by Jester98x** [comment]
@twright-msft Thanks, fixed it for me.

**Comment by cheenamalhotra** [comment]
Thanks - worked for me too! Closing the issue.

**Comment by demvin** [comment]
how about fixing https://hub.docker.com/r/microsoft/mssql-server-linux/ ?

**Comment by twright-msft** [comment]
Added a note to the Docker Hub page.

**Comment by SkilaZheng** [comment]
thanks  --worked for me too

**Comment by donhuvy** [comment]
Dangerous mistake still exist: https://stackoverflow.com/a/64321220/3728901

**Comment by MrR0807** [comment]
This is still not fixed in docker.hub [link](https://hub.docker.com/_/microsoft-mssql-server).

> Start a mssql-server instance using the latest update for SQL Server 2017
```
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest
```

**Comment by mahmmad-khamar-shaikh** [comment]
> Try using double quotes instead of single. See here:
> https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker

Worked for me. Thanks 👍

**Comment by AmrElshaer** [comment]
> Try using double quotes instead of single. See here:
> https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker

Thanks you help me for solve this issue

**Comment by simonlampen** [comment]
Could someone Pleeeeeeaaaaaasssssseeeee fix the docs page here: https://hub.docker.com/_/microsoft-mssql-server
and put double quotes. Life is to short to waste time on syntax :)

**Comment by amvin87** [comment]
Thank you for the feedback, I have made the required changes and  the update should merge in about 24 hours or earlier. :)

**Comment by chrisadkin** [comment]
I'm attempting to use the mssql-tools image within a docker files, the first line of my docker file is:

FROM mcr.microsoft.com/mssql-tools:latest

When I build the image I get:

#5 30.31 debconf: falling back to frontend: Teletype
#5 30.33 Configuring msodbcsql17
#5 30.33 -----------------------
#5 30.33 
#5 30.33 The license terms for this product can be downloaded from
#5 30.33 https://aka.ms/odbc17eula and found in /usr/share/doc/msodbcsql17/LICENSE.txt.
#5 30.33 
#5 30.33 By choosing 'Yes', you indicate that you accept the license terms.
#5 30.33 
#5 30.33 Do you accept the license terms?
#5 30.33 
#5 30.33  [yes/no] 
#5 30.33 Use of uninitialized value $_[1] in join or string at /usr/share/perl5/Debconf/DbDriver/Stack.pm line 111.
#5 30.34 The license terms for this product can be downloaded from
#5 30.34 https://aka.ms/odbc17eula and found in /usr/share/doc/msodbcsql17/LICENSE.txt.
#5 30.34 
#5 30.34 By choosing 'Yes', you indicate that you accept the license terms.
#5 30.34 
#5 30.34 Do you accept the license terms?
#5 30.34 
#5 30.34  [yes/no] 
#5 30.34 Use of uninitialized value $_[1] in join or string at /usr/share/perl5/Debconf/DbDriver/Stack.pm line 111.
#5 30.34 ERROR: The EULA was not accepted. Installation aborted.

I try to get around this using the following on the command line:

docker build --build-arg 'ACCEPT_EULA=Y' . -t cs3_csv_to_mssql:1.0

But this makes no difference, can someone please advise as to how I can work around this.

Thanks !
