### ISSUE TITLE
microsoft/mssql-server-linux exits immediately on Docker for Windows

### ISSUE THREAD

**Issue by MitchJust** [Microsoft/mssql-docker#202]
Running 

`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' microsoft/mssql-server-linux:latest`

on Docker for Windows (hyper-v) outputs

`Aborted`

straight away, and the container stops

**Comment by twright-msft** [comment]
Did you change your memory settings to at least 4 GB of RAM for the Moby VM?

**Comment by MitchJust** [comment]
Yes, 8gb is allocated to it. Note this works perfectly when switching to the VirtualBox based Docker Toolbox on Windows

`PS C:\Users\user> docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 17.11.0-ce-rc4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 992280e8e265f491f7a624ab82f3e238be086e49
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.769GiB
Name: linuxkit-00155d4b0102
ID: LWTB:FKS3:F7WN:4MSR:5WBT:VQCJ:LQMH:4GC4:7DKD:ZNQP:66IF:N3MO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 48
 System Time: 2017-11-20T22:10:20.3114299Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false`

**Comment by twright-msft** [comment]
Try running without -d and see if there is anything interesting in the output.

**Comment by MitchJust** [comment]
Running without `-d`, and with `-it`

```
PS C:\Users\user>docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -it microsoft/mssql-server-linux:latest

Aborted
```

**Comment by MitchJust** [comment]
I have confirmed that this container does work on Docker for Windows (hyper-v) on another system, so it looks like it's something in my environment. The strange part is this seems to be the only container which doesn't work.

**Comment by neittien0110** [comment]
![image](https://user-images.githubusercontent.com/8079397/90366798-f267f380-e091-11ea-991d-d42374e65509.png)
With my case, I found that the problem was the password I set too simple, 123456. 
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=123456' -p 2433:1433  -v -d mcr.microsoft.com/mssql/server

Solution: used complex password. This cmd is okay.
 docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=XYZxyz!@#$1234' -p 2433:1433  -v -d mcr.microsoft.com/mssql/server
