### ISSUE TITLE
How to get direct download link for SQL Server 2017 with advanced services

### ISSUE THREAD

**Issue by lurock** [Microsoft/mssql-docker#205]
I see the docker container here for SQL Server Express 2017 has the direct download link in it but I need full text search and some other advanced options.  How or where do I get the direct download link of the media that includes the Advanced Services such as full text search?

**Comment by twright-msft** [comment]
You can create your own Dockerfile from the one that we published here and add different feature command line parameters to build your own image with whatever you need.
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt#Feature
