### ISSUE TITLE
Where has `install` gone?

### ISSUE THREAD

**Issue by satoryu** [Microsoft/mssql-docker#206]
When I looked the dockerfile of mssql, I could not find `install` script in this repository.

https://github.com/Microsoft/mssql-docker/blob/1efc4cf9b78fa5fccea682f26067189660af85c8/linux/mssql-server-linux/Dockerfile#L12

Where has the file gone?

**Comment by twright-msft** [comment]
./install is a directory on our build drop server not a file.  This line in the Dockerfile is used to copy all the contents of the ./install directory on the build drop server into the root of the container.

**Comment by satoryu** [comment]
I couldnt find ‘install’ directory in this repository. can i build sql server with the  Dockerfile? or is there any doc for it?

**Comment by twright-msft** [comment]
Yes, you can build it by following an example more like this:
https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile
