### ISSUE TITLE
Configuration options for mssql-server-windows-developer

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/mssql-docker#208]
How was https://hub.docker.com/r/microsoft/mssql-server-windows-developer/ configured?  What options were selected?  In particular, were R and Python support selected?

**Comment by perrysk-msft** [comment]
@gbritton1 - Currently we enable only the database engine in the Windows Developer image (/FEATURES=SQLEngine) that we publish. You can enable more features by extending the dockerfile: https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-developer/dockerfile.

For a list of feature parameters, please visit this article: https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt#Feature
