### ISSUE TITLE
Creating new Dockerfile doesn't pass sa_password

### ISSUE THREAD

**Issue by stonesbg** [Microsoft/mssql-docker#211]
I am trying to create a new Dockerfile that will wrap mssql-server-windows-developer so that I can create a new database as part of a docker image.

However when I sent the password manually within the dockerfile it doesn't seem to get passed to the image.  I keep  getting "Login failed for user 'sa'.".  I checked that i can do a docker run with just the mssql-server-windows-developer image with the password and I a able to connect.  My docker file looks like below.

`
FROM microsoft/mssql-server-windows-developer:latest
SHELL ["powershell"]
ENV sa_password D0cker!a8s
ENV ACCEPT_EULA  "Y"
EXPOSE 1433
`

**Comment by twright-msft** [comment]
Have you tried putting your password in double quotes?

**Comment by stonesbg** [comment]
The quotes fix the problem for the password thanks for the help
