### ISSUE TITLE
windows developer edition does not support server 1709 build.

### ISSUE THREAD

**Issue by erichexter** [Microsoft/mssql-docker#212]
When I try to run the a container based on the latest tag on a 1709 windows sever core docker host. I get the following error message.

failure in a Windows system call: The operating system of the container does not match the operating system of the host. (0xc0370101) 

I expected that there would be a mssql-windows-developer-edition that is based on the latest server continer version 1709.

**Comment by perrysk-msft** [comment]
Thanks @erichexter!

We just published an updated mssql-windows-developer image that is based on the latest Windows Server version - Please give that a try.

**Comment by erichexter** [comment]
I don't think the base image is using a 1709 based version. I was not able to use the latest version it gave me the same error as the 2017-latest.  I pulled the history for each of the 1709 container images and the latest developer image. It looks like the server version numbers are different. 

I expected the base layer to be 
Install update **10.0.16299.64**    instead of  Install update **10.0.14393.1884**         
```
PS C:\Users\eric\github\DockerContainers\Containers\Build> docker history microsoft/windowsservercore:1709
IMAGE               CREATED             CREATED BY                     SIZE                COMMENT
be1324f21832        4 weeks ago         Install update **10.0.16299.64**   962MB
<missing>           2 months ago        Apply image 10.0.16299.15      4.62GB
```
```
PS C:\Users\eric\github\DockerContainers\Containers\Build> docker history microsoft/windowsservercore:1709_KB4048955
IMAGE               CREATED             CREATED BY                     SIZE                COMMENT
be1324f21832        4 weeks ago         Install update **10.0.16299.64**   962MB
<missing>           2 months ago        Apply image 10.0.16299.15      4.62GB

```

```
PS C:\Users\eric\github\DockerContainers\Containers\Build> docker history microsoft/mssql-server-windows-developer:latest 

IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
9e08a14c562e        2 hours ago         powershell -Command $ErrorActionPreference =…   41kB
<missing>           2 hours ago         powershell -Command $ErrorActionPreference =…   41kB
<missing>           2 hours ago         powershell -Command $ErrorActionPreference =…   121MB
<missing>           2 hours ago         powershell -Command $ErrorActionPreference =…   1.1GB
<missing>           2 hours ago         powershell -Command $ErrorActionPreference =…   41kB
<missing>           2 hours ago         powershell -Command $ErrorActionPreference =…   42.8kB
<missing>           2 hours ago         powershell -Command $ErrorActionPreference =…   41kB
<missing>           2 hours ago         cmd /S /C #(nop)  ENV ACCEPT_EULA=_             41kB
<missing>           2 hours ago         cmd /S /C #(nop)  ENV attach_dbs=[]             41kB
<missing>           2 hours ago         cmd /S /C #(nop)  ENV sa_password=_             41kB
<missing>           2 hours ago         cmd /S /C #(nop)  ENV box=https://go.microso…   41kB
<missing>           2 hours ago         cmd /S /C #(nop)  ENV exe=https://go.microso…   41kB
<missing>           2 hours ago         cmd /S /C #(nop)  LABEL maintainer=Perry Sko…   41kB
<missing>           3 weeks ago         Install update **10.0.14393.1884**                  2.72GB
<missing>           11 months ago       Apply image 10.0.14393.0                        7.68GB

```

**Comment by erichexter** [comment]
In the mean time, I have found that if I run this container using hyperv isolation on the windows server, I can use the image. so I think I am not blocked, just using a less optimal method.  As far as the developer workflows, we have to use hyperv on windows 10, so really not an issue there. it is just a problem on our build servers.

**Comment by perrysk-msft** [comment]
@eri

**Comment by erichexter** [comment]
I think you have to explicit select the windowsservercore:1709 in order to pull from that base image.  its kind of a breaking changing in tag versions, but that is what the team id soing.

**Comment by perrysk-msft** [comment]
Got it! I'll pull the 1709 base image and build a new sql dev image shortly.

**Comment by clawrenceks** [comment]
@perrysk-msft I can see that there is still no SQL image on the Docker hub compatible with Windows 1709 on the Docker Hub. It isn't too much of an issue for me as I have built my own, but being able to get it from the Docker Hub is of course so much easier.

Happy to help on this if you like.

**Comment by sixeyed** [comment]
@clawrenceks can you share the Dockerfile you used to package SQL on 1709?

**Comment by clawrenceks** [comment]
@sixeyed Sure, I actually just took the Dockerfile from this repo at https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-developer/dockerfile and changed the FROM instruction to use microsoft/windowsservercore:1709 as the base.

**Comment by sixeyed** [comment]
Thanks @clawrenceks  - works for me :)

**Comment by perrysk-msft** [comment]
Thanks all for your help and feedback and apologies for the long delay - The SQL Developer and Express 1709 images are now published on DockerHub with a 1709 tag.

Please let me know if these work ok for you - I am closing this issue for now.

Thanks, Perry
