### ISSUE TITLE
No link for complexity requirements

### ISSUE THREAD

**Issue by droed1** [Microsoft/mssql-docker#214]
Documentation on https://hub.docker.com/r/microsoft/mssql-server-windows-developer/ states:
"sa_password: The system administrator (userid = 'sa') password used to connect to SQL Server once the container is running. The password must meet the password complexity requirements found here: <LINK> "

Where in the world is the link?? I have tried a number of complexity scenarios and nothing seems to work.

**Comment by perrysk-msft** [comment]
@droed1 - Please refer to this: https://docs.microsoft.com/en-us/sql/relational-databases/security/password-policy article.

**Comment by droed1** [comment]
Thanks for the link. That is what I figured it was. Unfortunately, that didn't help my specific problem, which appears to be outside the scope of the build.
