### ISSUE TITLE
Problem in setup

### ISSUE THREAD

**Issue by asd51993** [Microsoft/mssql-docker#221]
Hi 
I tried to install mysql server on centos 7.4
and when I reach this command  

>             /opt/mssql/bin/mssql-conf setup

I get this Error 

> Traceback (most recent call last):
>   File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 277, in <module>
>     main()
>   File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 273, in main
>     processCommands()
>   File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 197, in processCommands
>     COMMAND_TABLE[args.which]()
>   File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 54, in handleSetup
>     exit(mssqlconfhelper.setupSqlServer(eulaAccepted, noprompt=args.noprompt))
>   File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 795, in setupSqlServer
>     if not checkInstall():
>   File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 765, in checkInstall
>     return runScript(checkInstallScript, True) == 0
>   File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 754, in runScript
>     return subprocess.call([sudo, "-EH", pathToScript])
>   File "/usr/lib64/python2.7/subprocess.py", line 524, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> [root@AnasMzmnh ~]# /opt/mssql/bin/sqlservr-setup
> -bash: /opt/mssql/bin/sqlservr-setup: No such file or directory
> [root@AnasMzmnh ~]# /opt/mssql/bin/mssql-conf setup
> Traceback (most recent call last):
>   File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 277, in <module>
>     main()
>   File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 273, in main
>     processCommands()
>   File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 197, in processCommands
>     COMMAND_TABLE[args.which]()
>   File "/opt/mssql/bin/../lib/mssql-conf/mssql-conf.py", line 54, in handleSetup
>     exit(mssqlconfhelper.setupSqlServer(eulaAccepted, noprompt=args.noprompt))
>   File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 795, in setupSqlServer
>     if not checkInstall():
>   File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 765, in checkInstall
>     return runScript(checkInstallScript, True) == 0
>   File "/opt/mssql/lib/mssql-conf/mssqlconfhelper.py", line 754, in runScript
>     return subprocess.call([sudo, "-EH", pathToScript])
>   File "/usr/lib64/python2.7/subprocess.py", line 524, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

mysql verison is 

>

>  [****************]# rpm -qa | grep mssql
> 
> mssql-server-14.0.3008.27-1.x86_64

**Comment by twright-msft** [comment]
Hi @asd51993 -- This mssql-docker project is for using SQL Server in containers.  Sounds like you may just be trying to do a package-based installation.  Or is this a CentOS-based container image dockerfile you are working with?

One thing to try is to make sure you are running the mssql-conf utility with sudo.

**Comment by asd51993** [comment]
I know I am an Idiot but in case someone else have the same issue Measures
the VPS I had had no sudo installed on
>Yum install sudo
then 
>sudo /opt/mssql/bin/mssql-conf setup
problem solved
