### ISSUE TITLE
newsequentialid is broken in mssql-server-linux

### ISSUE THREAD

**Issue by Sayan751** [Microsoft/mssql-docker#222]
I am using `mssql-server-linux` in combination with Entity Framework where the entities have `Guid` as Primary Key with `DatabaseGeneratedOption.Identity` option. This results in a default constraint on the primary key columns with `newsequentialid()` as default value/function.

However, `newsequentialid()` is generating duplicate values in `mssql-server-linux`, and that results naturally in PK violation.

P.S.: In the meantime, is there any workaround in this situation?

**Comment by twright-msft** [comment]
Have you tried newid() instead of newsequentialid()?

**Comment by twright-msft** [comment]
It seems that NEWID is your only option until this bug is fixed in EF. If you are open to using other data types for your PK you could do an int/bigint instead.

**Comment by wojciechrak** [comment]
I am confused... Why do you mention EF? Did you mean Entity Framework? This issue has nothing related to Entity Framework, it's plain MSSQL for linux.

**Comment by twright-msft** [comment]
I see.  My bad.  Does NewID() work?
I'll check on the status of this bug.

**Comment by wojciechrak** [comment]
Yes, `newid()` works correctly afaik.

**Comment by Sayan751** [comment]
An observation: this occurs after restarting the docker container. It seems that after restarting the container, the sequence is also reset, which results in duplicate GUID.

**Comment by JSanchezIO** [comment]
Is there anything new to add to this issue?

**Comment by JSanchezIO** [comment]
This seems to have been resolved with [Cumulative Update 4](https://support.microsoft.com/en-us/help/4056498/cumulative-update-4-for-sql-server-2017).

**Comment by twright-msft** [comment]
OK good to hear.  Closing this out then.
