### ISSUE TITLE
This program has encountered a fatal error and cannot continue running

### ISSUE THREAD

**Issue by sirio3mil** [Microsoft/mssql-docker#225]
Hi,

I'm using this [dockerfile](https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile) and I get this error

This is an evaluation version.  There are [33] days left in the evaluation period.
This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:
2017-12-21T15:19:39.231512200Z 
       Reason: 0x00000006
       Status: 0x40000015
      Message: Kernel bug check
      Address: 0x6a42b4b0
   Parameters: 0x6a62a250
                                                                                   Stacktrace: 000000006a4e8446 000000006a42b50b 000000006a41ecad 
               000000006a42aeab 000000006a4e69dd 000000006a4e5a1c 
               000000006a4e5890 000000006a4e57c5 
      Process: 7 - sqlservr
       Thread: 11 (application thread 0x1000)
  Instance Id: dfadf876-d6a2-49a0-a73e-00b603849d46
     Crash Id: 9e43a4a5-6e65-4ba7-b3f4-7225fdb22000
  Build stamp: a033534dbc90cff419f26ec9fbb0903dc3f3abc65769eec03f04659b9c68ebb2
2017-12-21T15:19:39.268043500Z 
Capturing core dump and information...
dmesg: read kernel buffer failed: Operation not permitted
No journal files were found.
No journal files were found.
Attempting to capture a dump with paldumper
WARNING: Capture attempt failure detected
Attempting to capture a filtered dump with paldumper
WARNING: Attempt to capture dump failed.  Reference /var/opt/mssql/log/core.sqlservr.7.temp/log/paldumper-debug.log for details
Attempting to capture a dump with gdb
WARNING: Unable to capture crash dump with GDB. You may need to
allow ptrace debugging, enable the CAP_SYS_PTRACE capability, or
run as root.

I'm using my own [dockerfile](https://github.com/sirio3mil/docker-sqlsrv-full/blob/master/Dockerfile) repo and this is my docker-compose configuration

mssql:
        image: reynier3mil/centos-mssql-full:latest
        container_name: "mssql"
        #restart: always
        volumes:
            - C:/www/mssql:/var/opt/mssql
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=xxxxxxxxx
            - MSSQL_PID=Developer
        ports:
            - 1433:1433

TIP 1: If I use basic dockerfile without agent + hs + fts I don't have any error. 

TIP 2: Using basic dockerfile and adding manually only the agent I get same error

Any idea or possible solution?

Regards

**Comment by twright-msft** [comment]
Can you please run `docker images` and confirm you have the most recent version of the mssql-server-linux image?

**Comment by sirio3mil** [comment]
Yes,

microsoft/mssql-server-linux          latest              b0bb2e68f091        4 weeks ago         1.33GB

**Comment by sirio3mil** [comment]
I'm also using

Docker CE
Version 17.09.1-ce-win42 (14687)
Channel: stable
3176a6a

[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17046  0

Regards
