### ISSUE TITLE
CU3 and patch for Intel Meltdown issue.

### ISSUE THREAD

**Issue by dunfor** [Microsoft/mssql-docker#228]
When wil CU3 be out for Linux? It is already out for Windows to address the Intel Meltdown issue.
https://support.microsoft.com/en-us/help/4052987/cumulative-update-3-for-sql-server-2017

**Comment by twright-msft** [comment]
Very soon... keep hitting refresh occasionally on https://hub.docker.com/r/microsoft/mssql-server-linux/tags/

**Comment by twright-msft** [comment]
CU3 is available now.  :2017-CU3 or :2017-latest or :latest tag.

**Comment by wesclark** [comment]
Yes, it is out for Windows as a scripted upgrade, but the Docker image for Windows is still on CU1.

**Comment by perrysk-msft** [comment]
Apologies for the delay - Docker image for Windows is now on CU3.
