### ISSUE TITLE
SQL Server developer Windows docker image

### ISSUE THREAD

**Issue by wesclark** [Microsoft/mssql-docker#230]
When I pull  microsoft/mssql-server-windows-developer:2017-latest, I get CU#1.  CU#3 just came out.  What is going on?  Why does the Linux docker image get updated and the Windows docker image does not?  Is Microsoft giving up on Windows Docker?  Please give us an update as to your plans for supporting the Windows Docker image of SQL Server 2017 Developer edition.

**Comment by perrysk-msft** [comment]
Apologies for the delay - Docker image for Windows is now on CU3.

**Comment by wesclark** [comment]
Thanks. Is there a reason the Windows version lags behind the Linux version?

On Jan 16, 2018 11:52 AM, Perry Skountrianos <notifications@github.com> wrote:

Apologies for the delay - Docker image for Windows is now on CU3.

**Comment by twright-msft** [comment]
Two reasons: 
1) Linux is supported in production.  Windows is dev/test use cases only for now.
2) Linux is automatically built and tested as part of our servicing pipeline.  Windows is manually built and tested for now.

**Comment by wesclark** [comment]
I had no idea about Windows being dev/test only now.  Where would I find that information?

**Comment by twright-msft** [comment]
It's noted near the top of the Docker Hub pages:
https://hub.docker.com/r/microsoft/mssql-server-windows-developer/
https://hub.docker.com/r/microsoft/mssql-server-windows-express/

> Intended Use: Development and Testing only. Not supported in production environments.

**Comment by wesclark** [comment]
So it is!  Thanks.
