### ISSUE TITLE
Recommended way to run a cluster

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/mssql-docker#231]
What is currently the recommended way to run a HA mssql cluster? Currently experimenting with k8s’s [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) which seems like a good candidate for the job. 

I’m hoping to simply define a yaml file which I apply with kubectl and the cluster should just run and the instances should be connected. Something like [this](https://codelabs.developers.google.com/codelabs/cloud-mongodb-statefulset/index.html?index=..%2F..%2Findex#5) mongodb example seems perfect. Although I’m not sure it’s possible with mssql.

**Comment by twright-msft** [comment]
We are just about to post some documentation on this.  I'll update once it is live.

**Comment by nphmuller** [comment]
Nice! Looking forward to it.

**Comment by twright-msft** [comment]
Doc will be available at this URL later today:  https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes

This scenario will be more like a FCI HA with shared storage.  We are also working on a replication based HA story with Always On Availability Groups.  More info on that in the next couple of months as we finalize that implementation and decide how/when to release it.

Going to close this issue for now though,.
