### ISSUE TITLE
mssql downgraded by apt-get install mssql-server-agent (et al)

### ISSUE THREAD

**Issue by paulholmes-london** [Microsoft/mssql-docker#232]
I am creating an image to include all additional features (Agent / HA / FTS), using:

https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile

Posted by @twright-msft 

When any of these lines in the dockerfile are included, a dependency is invoked that downgrades the latest mssql version in the base image (currently 2017 RTM-CU3-GDR) to the version that was current back when this dockerfile was posted (2017 RC2).

    RUN apt-get install -y mssql-server-agent  # Downgrades mssql to 2017 CU2
    RUN apt-get install -y mssql-server-ha  # Downgrades mssql to 2017 CU2
    RUN apt-get install -y mssql-server-fts  # Downgrades mssql to 2017 CU2

When all of these are commented out, the mssql version remains as the latest.

**Comment by twright-msft** [comment]
This is a dumb mistake on our/my part.  I'll explain over here and I'm working on fixing it right now.  Standby...  Should post something tonight.
https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile
