### ISSUE TITLE
Expire date of Full-Text Search package mssql linux

### ISSUE THREAD

**Issue by ibeamzz** [Microsoft/mssql-docker#233]
Hi Everyone,

I've found evaluation period time when added FTS package into my container [link](https://ibb.co/jo4Z46). I tried to rebuild image but the expiration date is the same. now I've only 13 days left.

Can someone found this issue like me?
I would like to know how to fix it?

Thanks!

**Comment by twright-msft** [comment]
If you built this with the Dockerfile example we provided here, please build again with the new version of the Dockerfile I just posted.
https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile

See explanation of the problem at the end of this issue
https://github.com/Microsoft/mssql-docker/issues/30

**Comment by ibeamzz** [comment]
the problem has been fixed.
Thank a lot Travis!.

**Comment by twright-msft** [comment]
Great! Thanks for letting us know!
