### ISSUE TITLE
stop after startup several seconds

### ISSUE THREAD

**Issue by xyhxiayuhang** [Microsoft/mssql-docker#234]
command to install
`docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=hadoop' -p 1403:1433 --name xyh -v /home/xyh/sqlStorage:/var/opt/mssql -d microsoft/mssql-server-linux:2017-latest`

```
[root@localhost log]# docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                          PORTS                    NAMES
71cd0f2e0b07        microsoft/mssql-server-linux:2017-latest   "/bin/sh -c /opt/mss…"   27 minutes ago      Exited (1) 7 minutes ago                                 xyh
```
the status is "up" just a few seconds, then it exited.

I use `docker start xyh`,  it also just remain a few seconds and then exited.

I don't know the reason, I just follow the instruction in 
https://docs.microsoft.com/zh-cn/sql/linux/quickstart-install-connect-docker

**Comment by twright-msft** [comment]
Try with a more complex password.

**Comment by xyhxiayuhang** [comment]
I solved the problem as you say, thank you very much@twright-msft
