### ISSUE TITLE
As a developer I want specific version tags

### ISSUE THREAD

**Issue by thisisthekap** [Microsoft/mssql-docker#236]
As a developer I want to use a specific docker image tag for each version instead of `latest` or `2017-GA`.

Specific version tags are imho key to have a reproducible and stable development environment.

**Comment by twright-msft** [comment]
There are specific version tags already.
Example:
https://hub.docker.com/r/microsoft/mssql-server-linux/tags/

Are you looking for something in addition to that?

**Comment by thisisthekap** [comment]
@twright-msft Thanks for pointing out the tags!

Is there some kind of changelog available to figure out which features are available in which tag?

**Comment by twright-msft** [comment]
Yup:  https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes#CU2

**Comment by thisisthekap** [comment]
Thank you very much! The issue may be closed now.

**Comment by twright-msft** [comment]
Cool.. Keep the feedback and questions coming!
