### ISSUE TITLE
need mssql server fts support in docker for mac

### ISSUE THREAD

**Issue by param0091** [Microsoft/mssql-docker#238]
need sql server fts support in docker for mac. I have tried installing ubuntu in docker then mssql server then mssql sever fts but it give me evaluation period issue just provide 14 days trial. Any help appreciated.
Thanks,

**Comment by twright-msft** [comment]
Did you try the new version of the example Dockerfile that is here?
https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile

**Comment by param0091** [comment]
it seems to be different from the file that i have created, The main difference is base os. I will try and let you know. Thanks
One more question i.e the microsoft/mssql-server and mssql-server-fts are free for mac on docker ?

**Comment by twright-msft** [comment]
In effect yes they are "free" because they would presumably be used just in a dev/test capacity on a mac.  The Developer Edition of SQL Server is free and has all of the features and unlimited resource limits (cores, memory, etc).  The Developer Edition is limited to non-production use by the licensing agreement.  Developer Edition is the default when you run a container.  If you want to choose a specific edition other than Developer Edition, you can pass the MSSQL_PID environment variable.

**Comment by param0091** [comment]
I have used the new dockerfile and it working fine 'Thanks for you help' but sometimes when restore .bak file it gives me error . Below is my command to restore database and error

**Commands to restore:**

1. docker load -i /Volumes/DATA/JKPackage/Docker/Archive/server.tar **(This works fine)**
2. docker run -d --name jklaws -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=P@55w0rd' -e 'MSSQL_PID=Developer' -p 1433:1433 server **(This works fine)**
3. docker cp /desktop/JayKayQA_18.12.2017.bak  jklaws:/var/opt/mssql/JKLawsBak **(This sometimes fails but in case of microsoft/mssql-server-linux:latest-2017)**
4. docker exec jklaws /opt/mssql-tools/bin/sqlcmd -U sa -P P@55w0rd -Q "RESTORE DATABASE [JayKayQA] FROM DISK='/var/opt/mssql/JKLawsBak/JayKayQA_18.12.2017.bak' WITH MOVE 'JayKayDb' TO '/var/opt/mssql/data/JayKayQA.mdf', MOVE 'JayKayDb_log' TO '/var/opt/mssql/data/JayKayQA_log.ldf' " **(This sometimes fails but in case of microsoft/mssql-server-linux:latest-2017)**

**Error: This error occure when we run command number 4**

Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

Any solution to this.

Thanks

**Comment by twright-msft** [comment]
I'm not sure why #3 would fail.  Seems like a pretty straightforward copy command.
For 4 my guess is that it is a race condition.  It takes a few seconds for SQL Server to come up inside the container and be ready for a connection.  If you are running these steps quickly one after another in a script for example, then SQL Server may not have enough time to get ready for the connection attempt before you try to connect to it with sqlcmd.  You could either build in some retry logic or wait logic and see if that helps.

**Comment by param0091** [comment]
Thanks for your valuable comments and i will try it with retry logic or wait logic. And in case of #3 command , I have checked the activity monitor and it show cpu usage exact 220% or sometimes 0% for this particular docker process and got stuck there and never complete the process or never gives any error.

**Comment by param0091** [comment]
You solution to my query works fine but i'm facing some other issue which is OS X specific 10.13.3
Hello,

I am using following docker file to create an image.
Below is the dockerfile content
=============================================================
# mssql-agent-fts-ha-tools
# Maintainers: Microsoft Corporation (twright-msft on GitHub)
# GitRepo: https://github.com/Microsoft/mssql-docker

# Base OS layer: Latest Ubuntu LTS
FROM ubuntu:16.04

# apt-get and system utilities
RUN apt-get update && apt-get install -y \
	curl apt-transport-https debconf-utils \
    && rm -rf /var/lib/apt/lists/*

# adding custom MS repository
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

# install SQL Server drivers and tools
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN /bin/bash -c "source ~/.bashrc"



RUN apt-get -y install locales
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8

CMD /bin/bash 

#Install curl since it is needed to get repo config
# Get official Microsoft repository configuration
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y curl && \
    apt-get install apt-transport-https && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list | tee /etc/apt/sources.list.d/mssql-server.list && \
    apt-get update

# Install SQL Server which a prerequisite for the optional packages below.
RUN apt-get install -y mssql-server

# Install optional packages.  Comment out the ones you don't need
# RUN apt-get install -y mssql-server-agent
# RUN apt-get install -y mssql-server-ha
  RUN apt-get install -y mssql-server-fts

# Run SQL Server process
CMD /opt/mssql/bin/sqlservr

=============================================================

#These commands are used to build the image from docker file.
cd /Users/paramvir/Desktop/docker-mssql-server-linux-with-fts-master
docker build -t mssqlimagefIle .

Below command is used for saving the newly created to specific folder
docker save mssqlimagefIle -o /Users/paramvir/Desktop/Image/mssqlimagefIle.tar

SERVER_FILE is the path of newly created image file
Below command is used to load the server to docker
docker load -i “$SERVER_FILE”

#Creating container
docker run -d --name container -e ‘ACCEPT_EULA=Y’ -e ‘SA_PASSWORD=P@55w0rd’ -e ‘MSSQL_PID=Developer’ -p 1433:1433 mssqlimagefIle

When we are running creating container command, it creates the container but it exits automatically within no time and when we check the status of the container using docker ps -a command, it shows container exited with status 255.

Please any suggestion,
Thanks
