### ISSUE TITLE
Create tags/releases

### ISSUE THREAD

**Issue by schmunk42** [Microsoft/mssql-docker#24]
So we don't need to be on latest/master all the time.

**Comment by twright-msft** [comment]
This is already done! :)
https://hub.docker.com/r/microsoft/mssql-server-linux/tags/
https://hub.docker.com/r/microsoft/mssql-server-windows/tags/
We will continue doing this and will retain n-2 releases during the preview period.

**Comment by schmunk42** [comment]
Must have overlooked this :) thanks.
