### ISSUE TITLE
Receiving Error: The evaluation period has expired.

### ISSUE THREAD

**Issue by scoobs76** [Microsoft/mssql-docker#244]
PS C:\Docker\builds\SQL2017> docker logs 782

Error: The evaluation period has expired.
This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:

       Reason: 0x00000001
       Signal: SIGSEGV - Segmentation fault (11)
   Stacktrace: 000055cb11271ce7 00007f8c22f54390 000055cb11280f52
               000055cb1126a6db 000055cb11269e59
      Process: 6 - sqlservr
       Thread: 19 (application thread 0x1030)
  Instance Id: 53be54ab-7e43-4f3f-bbef-259f5e35b65f
     Crash Id:
  Build stamp: a033534dbc90cff419f26ec9fbb0903dc3f3abc65769eec03f04659b9c68ebb2
Aborted

PS C:\Docker\builds\SQL2017> docker images

REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
sql2017                        latest              b501b9506842        2 hours ago         7.54GB
microsoft/mssql-server-linux   latest              cb3198f4b4d3        2 weeks ago         1.35GB
hello-world                    latest              f2a91732366c        2 months ago        1.85kB
node                           6.11.5              852391892b9f        2 months ago        662MB

When I run docker start for the new container, it immediately exits.

PS C:\Docker\builds\SQL2017> docker start 782
782
PS C:\Docker\builds\SQL2017> docker ps -all
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                       PORTS               NAMES
782b3ae8d7f7        sql2017             "/bin/sh -c /opt/mss…"   6 minutes ago       Exited (134) 3 seconds ago                       gracious_mahavira

Please advise.  Thanks.

**Comment by bmariesan** [comment]
We're also having this issue since yesterday morning

**Comment by twright-msft** [comment]
Looks like you have a pre-GA version of SQL Server.  You need to pull and run a newer version like :latest, :2017-latest, or :2017-GA.

**Comment by scoobs76** [comment]
Got it working.  Thanks.

**Comment by twright-msft** [comment]
Great.  Glad to hear it!
