### ISSUE TITLE
Failed To Start -- No such file or directory

### ISSUE THREAD

**Issue by ckiszka** [microsoft/mssql-docker#25]
This docker will not start for me. However, if I use 

> militellovinx/mssql-server-linux:latest

then it will run. Not sure why. I would prefer to use the latest release from MS.

## Command

 

> root@localhost:#
>  /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="KE-MSSQL" --net="bridge" -e TZ="America/New_York" -e HOST_OS="unRAID" -e "ACCEPT_EULA"="Y" -e "SA_PASSWORD"="password" -p 1433:1433/tcp -v "/var/dockers/ke/sql/":"/var/opt/mssql":rw -m 4GB microsoft/mssql-server-linux:latest
> 8619b44395377d22250742557e1f586ec4e2cbab6de91f716d7c194f96b53738
> 
> The command finished successfully!
> 

## Log

Configuring Microsoft(R) SQL Server(R)...
sqlservr: vm.cpp:38: BOOLEAN IsPossiblyValidPalAddress(const void *): Assertion `result' failed.

cat: /proc/22/sched: No such file or directory
No journal files were found.
No journal files were found.
ls: cannot access '/var/opt/mssql/log/errorlog*': No such file or directory
ls: cannot access '/var/opt/mssql/log/exception.log': No such file or directory
ls: cannot access '/var/opt/mssql/log/SQLDu*.txt': No such file or directory
ls: cannot access '/var/opt/mssql/log/SQLDu*.mdmp': No such file or directory
ls: cannot access '/var/opt/mssql/log/system_health*': No such file or directory
Configuration complete.
paltelemetry: Loading the directory /var/opt/mssql/.system/.system/telemetry failed. Errno [2]

This is an evaluation version. There are [174] days left in the evaluation period.

sqlservr: vm.cpp:38: BOOLEAN IsPossiblyValidPalAddress(const void *): Assertion `result' failed.

Capturing core dump and information for sqlservr (pid 151)...
cat: /proc/151/sched: No such file or directory
No journal files were found.
No journal files were found.
SQL Log Directory /var/opt/mssql/log
ls: cannot access '/var/opt/mssql/log/errorlog*': No such file or directory
ls: cannot access '/var/opt/mssql/log/exception.log': No such file or directory
ls: cannot access '/var/opt/mssql/log/SQLDu*.txt': No such file or directory
ls: cannot access '/var/opt/mssql/log/SQLDu*.mdmp': No such file or directory
ls: cannot access '/var/opt/mssql/log/system_health*': No such file or directory
Packaging core dump and information into compressed files.
Core dump and information will be written to /var/opt/mssql/log/core.sqlservr.01_24_2017_23_34_22.151 and logs in /var/opt/mssql/log/core.sqlservr.01_24_2017_23_34_22.151.log

**Comment by twright-msft** [comment]
What OS distro, version, and file system do you have on the host?

**Comment by ckiszka** [comment]
UnRaid 6.0, XFS

**Comment by twright-msft** [comment]
We think this is the assert that happens when the container starts up and has less than the required 4 GB of RAM.  It looks like you are trying to limit the container to -m 4GB, but does Docker Engine itself have at least 4 GB of available capacity for hosting containers?  We see this kind of thing quite often when people are using Docker for Mac or Docker for Windows which default to Docker Engine only have 2 GB by default.

**Comment by ckiszka** [comment]
The server has 24 GB of RAM, 16 GB available for use. Its weird. The other docker image, referenced above, works (except volume mapping). I think its based off your older image. Thanks for your assistance. Im trying to test the potential of moving away from MySql and start using MSSQL and NET Core. Any help and or direction with this SQL matter is greatly appreciated.

**Comment by twright-msft** [comment]
Can you please try without the -m 4GB and without the volume mapping?

**Comment by ckiszka** [comment]
## Command 

> root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="KE-MSSQL" --net="bridge" -e TZ="America/New_York" -e HOST_OS="unRAID" -e "ACCEPT_EULA"="Y" -e "SA_PASSWORD"="password" microsoft/mssql-server-linux:latest
> 191c66324a91a13bfa06957bd8596c5a85db6fbd2554614a36f3842f416d773c
> 
> The command finished successfully!

## Log


Configuring Microsoft(R) SQL Server(R)...
sqlservr: vm.cpp:38: BOOLEAN IsPossiblyValidPalAddress(const void *): Assertion `result' failed.

cat: /proc/21/sched: No such file or directory
No journal files were found.
No journal files were found.
ls: cannot access '/var/opt/mssql/log/errorlog*': No such file or directory
ls: cannot access '/var/opt/mssql/log/exception.log': No such file or directory
ls: cannot access '/var/opt/mssql/log/SQLDu*.txt': No such file or directory
ls: cannot access '/var/opt/mssql/log/SQLDu*.mdmp': No such file or directory
ls: cannot access '/var/opt/mssql/log/system_health*': No such file or directory
Configuration complete.
paltelemetry: Loading the directory /var/opt/mssql/.system/.system/telemetry failed. Errno [2]

This is an evaluation version. There are [173] days left in the evaluation period.

sqlservr: vm.cpp:38: BOOLEAN IsPossiblyValidPalAddress(const void *): Assertion `result' failed.

Capturing core dump and information for sqlservr (pid 150)...
cat: /proc/150/sched: No such file or directory
No journal files were found.
No journal files were found.
SQL Log Directory /var/opt/mssql/log
ls: cannot access '/var/opt/mssql/log/errorlog*': No such file or directory
ls: cannot access '/var/opt/mssql/log/exception.log': No such file or directory
ls: cannot access '/var/opt/mssql/log/SQLDu*.txt': No such file or directory
ls: cannot access '/var/opt/mssql/log/SQLDu*.mdmp': No such file or directory
ls: cannot access '/var/opt/mssql/log/system_health*': No such file or directory
Packaging core dump and information into compressed files.
Core dump and information will be written to /var/opt/mssql/log/core.sqlservr.01_25_2017_21_30_57.150 and logs in /var/opt/mssql/log/core.sqlservr.01_25_2017_21_30_57.150.log

**Comment by twright-msft** [comment]
OK, thanks.  Same result.  We made some changes in between 1.1 and 1.2 in how we manage memory so there could be an undiscovered bug here.  Could we trouble you to upload the dump so we can take a look at it?  If so, please contact me via email at twright a t  microsoft and I'll provide you the instructions on how to upload to our secure upload store.

**Comment by ckiszka** [comment]
Will do thanks.

**Comment by hcgonzalezpr** [comment]
Exactly same issue here. I'm using Unraid 6.3.2

Attached the logs : [https://drive.google.com/open?id=0B2l7au-TREeXYzJYVjJxVURldFk](url)

**Comment by ckiszka** [comment]
@hcgonzalezpr -- I created an lean Ubuntu VM in UnRaid with docker installed and it ran fine. Currently that is how I am operating with this docker image to date.

**Comment by hcgonzalezpr** [comment]
Thanks I'll got that route for now. Sadly this defeats the purpose of using docker to stay away from spinning up a whole a VM.

**Comment by diggforbeer** [comment]
Any chance for a fix to this, I would really like to use this docker on my unraid system directly.

**Comment by alebeta90** [comment]
Hello all,

I have same issue, it is possible to be related with the filesystem of our storage? in my case I have GlusterFS running on XFS, but if I run in a EXT4 filesystem the container works properly.

I see something similar here #126

**Comment by ckiszka** [comment]
@twright-msft -- Its been a couple years and I wanted to circle back and see if running mssql in a docker on Unraid has been updated? Thanks in advance.

**Comment by tjb-altf4** [comment]
@ckiszka I came across a solution a few days ago from another user, I'm up and running in unraid now.
Try adding the parameters  `-m 8g --ulimit stack=8192000:8192000`  (based on 8GB allocation)
Reasons explained in detail here: https://support.microsoft.com/hr-ba/help/4134638/sql-server-2017-terminates-and-generates-a-core-dump-on-rhel-7-4-when

**Comment by ckiszka** [comment]
@tjb-altf4 -- Great find. I read the post. 

I think the minimum memory requirement for Linux based Sql is 3GB. I am going to try your discovered solution with that to see if it solves the persistent storage blocker for me in unraid. 

Again, great find man! Thanks!

**Comment by ckiszka** [comment]
Just tested @tjb-altf4 solution in my docker compose file with 3GB. All works.
