### ISSUE TITLE
Suggestion: Add simple tag info to Docker Hub

### ISSUE THREAD

**Issue by ElectricWarr** [Microsoft/mssql-docker#251]
Please can you add some information explaining your tag names to the "Supported tags" section on Docker Hub?

I went searching and this comment covers exactly the information I was missing, simply trying to answer the questions "Which (non-latest) tag should I use?" and "Which other tag(s) currently map to 'latest'?".

The issue comment below is _exactly_ the information I needed, and (I think) would be useful to _all_ users new to the repository 😄 

https://github.com/Microsoft/mssql-docker/issues/166#issuecomment-334565892

**Comment by twright-msft** [comment]
Done!
