### ISSUE TITLE
"The evaluation period has expired" for the provided package from the repository

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Microsoft/mssql-docker#254]
When try to build and run the following Dockerfile, I got the error.
https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/RHEL/Dockerfile#L36

It looks like the repository is an old one. The url should be ``https://packages.microsoft.com/config/rhel/7/mssql-server-2017.repo``.

**Comment by twright-msft** [comment]
Yes, you are correct.  Thanks for pointing this out.  I've fixed it.
