### ISSUE TITLE
Development environment driver images

### ISSUE THREAD

**Issue by LuisBosquez** [Microsoft/mssql-docker#26]
A few weeks ago, the need for a pre-built PHP Docker image that included drivers and the PHP environment was raised in the following issues https://github.com/Microsoft/msphpsql/issues/168, https://github.com/Microsoft/mssql-docker/issues/4#issuecomment-272657395.

For this purpose, we have created a Docker image for PHP and pdo_sqlsrv: https://github.com/Microsoft/mssql-docker/tree/master/developer-resources/php-mssql 

This can also be pulled from `lbosqmsft/php-mssql`. 

Would these simplify developing with OSS frameworks? What other languages would be important to cover?

**Comment by mi-hol** [comment]
@LuisBosquez would it make sense to publish the download links under 'releases'?
I'd guess most people would look there ;-)

**Comment by boboldehampsink** [comment]
Maybe add `mssql-tools` as well?

**Comment by sirio3mil** [comment]
This type of images really depend on each project, my needs and ease install I make my one with [centos](https://github.com/sirio3mil/docker-php-fpm-image).

This can also be pulled from [reynier3mil/centos-php-fpm-msphpsql](https://hub.docker.com/r/reynier3mil/centos-php-fpm-msphpsql/).

**Comment by LuisBosquez** [comment]
@sirio3mil curious, how does the OS layer make a difference for a developer scenario?

**Comment by sirio3mil** [comment]
@LuisBosquez for linux developers maybe none but for me, a windows user, CentOS is much easy to configure and install, I know where I can find repos and how use it. That's all.

**Comment by gigatexal** [comment]
I too am more familiar with Linux than windows but am more familiar with SQLServer so sqlserver on Linux is perfect.

**Comment by sirio3mil** [comment]
@LuisBosquez in particular with this image as much as I can come to understand you use apache library unlike me that uses php-fpm for other browser such as nginx or shimmercat. This is the main difference by which I make my own.

**Comment by LuisBosquez** [comment]
We have created the following dev images using feedback from above, as well as from [msphpsql](https://github.com/Microsoft/msphpsql/), [tedious](https://github.com/tediousjs/tedious) and [pyodbc](https://github.com/mkleehammer/pyodbc) projects.

•	PHP: https://hub.docker.com/r/lbosqmsft/mssql-php-msphpsql/
•	Node.js: https://hub.docker.com/r/lbosqmsft/mssql-nodejs-tedious/
•	Python: https://hub.docker.com/r/lbosqmsft/mssql-python-pyodbc/

These images are meant to be extended to increase the functionality (add libraries, HTTP daemons, etc).
Let us know if there's any feedback!

**Comment by pbvarsok** [comment]
I couldn't make nginx working. Someone has done it?
