### ISSUE TITLE
microsoft/mssql-server-windows-developer page missing link

### ISSUE THREAD

**Issue by fhilton** [Microsoft/mssql-docker#263]
The "microsoft/mssql-server-windows-developer" page is missing the link to the sa_password complexity.

![image](https://user-images.githubusercontent.com/6132506/36323690-bae4e13a-131f-11e8-9ef2-0ca5c7d5549b.png)

https://hub.docker.com/r/microsoft/mssql-server-windows-developer/

**Comment by twright-msft** [comment]
Thanks for the heads up.  Fixed!
