### ISSUE TITLE
mssql-server-agent install error

### ISSUE THREAD

**Issue by IvanFarkas** [Microsoft/mssql-docker#270]
Running the mssql-agent-fts-ha-tools/Dockerfile get this error:
```
Step 4/7 : RUN apt-get install -y mssql-server-agent
 ---> Running in 5ca4f0537d17
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mssql-server-agent : Depends: mssql-server (>= 14.0.405.163-2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get install -y mssql-server-agent' returned a non-zero code: 100
```

**Comment by twright-msft** [comment]
The agent is now included in the mssql-server package so there is no need to install it as a separate step.  I've commented it out of the Dockerfile for now.

**Comment by IvanFarkas** [comment]
Awesome! **Great response time!** Thx, Ivan

**Comment by darkguy2008** [comment]
If it's already included then how to enable it? I can't seem to be able to enable it from SSMS

![unknown](https://user-images.githubusercontent.com/6304136/46602277-eb8ef380-caac-11e8-9a41-f923f6730814.png)

**Comment by twright-msft** [comment]
You can enable the Agent using this env var:
MSSQL_AGENT_ENABLED=true
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2017#environment-variables

**Comment by twright-msft** [comment]
OK cool!  I'm going to close this out.

**Comment by hitokiri** [comment]
Hello, in my case I already use the variable but the menu continues to appear as we showed in the image above.

> If it's already included then how to enable it? I can't seem to be able to enable it from SSMS
> 
> ![unknown](https://user-images.githubusercontent.com/6304136/46602277-eb8ef380-caac-11e8-9a41-f923f6730814.png)

docker compose
`version: "3.7"
services:
  sqlserver:
    image: sql-server
    build: ./Sqlserver
    container_name: sql-server
    hostname: Sqlserver
    ports:
    - "1433:1433"
    tty: true
    environment:
    - 'ACCEPT_EULA=Y'
    - 'SA_PASSWORD=1234'
    - 'MSSQL_AGENT_ENABLED=true'
    - 'MSSQL_PID=Enterprise'`
