### ISSUE TITLE
Use AD authentication for SQL Server for linux in docker container? 

### ISSUE THREAD

**Issue by hartman17** [Microsoft/mssql-docker#273]
Are there any documents on how to configure active directory authentication for SQL Server for Linux docker containers?   I'm trying to see if there is a way to do this and not have to register the container host, rather just configure the application to talk to active directory.

**Comment by twright-msft** [comment]
@hartman17  - not yet.  We are tracking this at this issue and are working on it internally here at MS right now.  Once we have some things figured out we'll publish the info.  #165

**Comment by AndiKleini** [comment]
Please go through my article where I explain how I did this for my company. 
[Authenticate .Net Core client of SQL Server with Integrated Security from Linux docker container](https://www.codeproject.com/Articles/1272546/Authenticate-Net-Core-client-of-SQL-Server-with-In)

**Comment by pedro-bonilla** [comment]
Any update on this @twright-msft ?

**Comment by AndiKleini** [comment]
I think the thread is already closed by @twright-mfs. Did you go through my article. I think it exactly deals with your problem.
[Authenticate .Net Core client of SQL Server with Integrated Security from Linux docker container](https://www.codeproject.com/Articles/1272546/Authenticate-Net-Core-client-of-SQL-Server-with-In)

**Comment by pedro-bonilla** [comment]
I think that this thread should be still opened. @AndiKleini your article is fantastic but does not solve the problem I have. I cannot create a windows login in SQL Server when it is running inside a linux docker container. This is not officially supported by MS so far.

**Comment by denis-mrd** [comment]
Dear, Microsoft, we need this so much!

**Comment by mojtabacazi** [comment]
Anyone tried this:
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017

**Comment by ashfaqurrahman-akij** [comment]
Yup
😄 
Been there done that
😄

**Comment by murugaratham** [comment]
@ashfqqurrahman-akij can share what u done to get it working?

**Comment by UmairSyed** [comment]
hi all...any updates on this one? I am trying to access SQL DB that is on the windows machine on prem. I am trying to access this DB from docker container running locally to use integrated security. The SQL DB server has implemented AD.

**Comment by murugaratham** [comment]
Keytab cron and integrated auth works, just need to ensure sql is configured for kerberos authentication and figuring out your krb5.conf settings. That’s domain specific.. spent a few hours trying and retrying

**Comment by YuhuaDeng** [comment]
> Keytab cron and integrated auth works, just need to ensure sql is configured for kerberos authentication and figuring out your krb5.conf settings. That’s domain specific.. spent a few hours trying and retrying

Please , could you share more details?

**Comment by AndiKleini** [comment]
> hi all...any updates on this one? I am trying to access SQL DB that is on the windows machine on prem. I am trying to access this DB from docker container running locally to use integrated security. The SQL DB server has implemented AD.

I thinks you can try this:
https://www.codeproject.com/Articles/1272546/Authenticate-Net-Core-client-of-SQL-Server-with-In

**Comment by fakhrulhilal** [comment]
> 
> 
> > hi all...any updates on this one? I am trying to access SQL DB that is on the windows machine on prem. I am trying to access this DB from docker container running locally to use integrated security. The SQL DB server has implemented AD.
> 
> I thinks you can try this:
> https://www.codeproject.com/Articles/1272546/Authenticate-Net-Core-client-of-SQL-Server-with-In

hi @AndiKleini, that's nice article. Unfortunately, docker image doesn't provide root access by default. I tried to use the same password as sa to gain root access, but no luck. So I can't install any required packages. Can you help?

**Comment by amvin87** [comment]
Here we have full support for Windows AD authentication for SQL Server Linux based containers. Here are the articles that you could refer to configure Windows AD authentication for SQL Server Linux containers
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-containers-ad-auth-adutil-tutorial?view=sql-server-ver15

For SQL Server on Linux (VMs, Baremetal) this is the article you can refer to:
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-ad-auth-adutil-tutorial?view=sql-server-ver15
