### ISSUE TITLE
Environment variables section not showing link for sa_password

### ISSUE THREAD

**Issue by c4rlosmarin** [Microsoft/mssql-docker#275]
The note on password complexity is as follows:
"The password must meet the password complexity requirements found here: LINK"

<img width="603" alt="sa_password" src="https://user-images.githubusercontent.com/17365297/36949478-9105276c-1fae-11e8-9e00-6ccd80b78081.png">

**Comment by twright-msft** [comment]
Thanks for the heads up.  Fixed!
