### ISSUE TITLE
Starting the SQLSERVERAGENT

### ISSUE THREAD

**Issue by RoryBolle** [Microsoft/mssql-docker#295]
Hello

I am struggling to start the SQLSERVERAGENT. I have run through all the tutorial steps, can currently connect using ssms.
I have enabled --> EXEC SP_CONFIGURE 'Agent XPs',1 
and everything looks like its working through the ssms UI.

The following fails with no error: xp_servicecontrol 'Start', 'SQLSERVERAGENT' 

The following fails with an error:
docker exec -it 8e9c624bf3a3 cmd
C:\>net start sqlserveragent
The SQL Server Agent (MSSQLSERVER) service is starting.
The SQL Server Agent (MSSQLSERVER) service could not be started.
The service did not report an error.

Any Help would be appreciated. (Apologies if I have not included relevant info.)

**Comment by twright-msft** [comment]
The SQL Server agent doesnt work in the Windows container right now.  It does work in the Linux container.  We're working on new versions of the  Windows container image now and fixing the agent is on the to do list.

**Comment by viloun** [comment]
Has this been improved in the latest docker image for the developer edition?

**Comment by joeydaowang** [comment]
Any updates here? I face the same issue here.
