### ISSUE TITLE
Need the SQL installer for 2016 SQL SP1 

### ISSUE THREAD

**Issue by jjburr** [Microsoft/mssql-docker#300]
Is it possible to obtain the download links for the docker 2016 SP1 developer edition so I can place in my dockerfile.

Thanks!

**Comment by twright-msft** [comment]
You should just be able to use the SQL 2017 Dockerfile for Windows and just update the download file location URLs.
https://github.com/Microsoft/mssql-docker/tree/master/windows/mssql-server-windows-developer

**Comment by jjburr** [comment]
Yep that’s the plan, however I cannot find the file location urls for the 2016sp1 .exe and .box - do you know what these are?

**Comment by twright-msft** [comment]
That depends on what you want.  Are you looking for developer edition, express edition, or one of the paid editions?  If paid edition, you'll need to download from the volume licensing servicing center (VLSC) first and then put them someplace where your docker build machine can reach them.

**Comment by jjburr** [comment]
Developer - I was under the understanding these were optimized setups for docker containers? 

Or am I best to just use an iso downloaded from VLSC?

**Comment by twright-msft** [comment]
There is nothing optimized about the Windows containers for SQL right now.  If you look closely at the Dockerfile, all it does it download and install using setup.exe.  The Linux containers for SQL are optimized to run in containers and supported in production.  The Windows containers are just for dev/test and experimenting for now.   We are working on optimized and supported Windows containers right now and they will be available in preview pretty soon.

**Comment by jjburr** [comment]
Great thanks Travis for the confirmation

**Comment by Ben-m-s** [comment]
I also need the packages for SQL Server 2016: I've tried the following URLs which used to work before:

```
ENV sql_server_exe_download_url="https://go.microsoft.com/fwlink/?linkid=829177" \
    sql_server_box_download_url="https://go.microsoft.com/fwlink/?linkid=829178" \
```
However, they do not work anymore.

I have also tried the following packages:

- https://go.microsoft.com/fwlink/?linkid=869611
- https://www.microsoft.com/en-us/download/confirmation.aspx?id=56840
- https://my.visualstudio.com/Downloads?q=SQL%20Server%202016%20Express&pgroup=

And the three of them result with the same error:

> Start-Process : This command cannot be run due to the error: The specified
> executable is not a valid application for this OS platform..

**The base image is**: windowsservercore-1709

The output of **SystemInfo** from inside the container is:
```
PS E:\Lab\SQLServerV2> docker exec test SystemInfo

Host Name:                 BB0755A59D97
OS Name:                   Microsoft Windows Server Datacenter
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00395-60000-00001-AA842
Original Install Date:     5/5/2018, 10:38:13 AM
System Boot Time:          6/4/2018, 6:43:52 PM
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 63 Stepping 2 GenuineIntel ~2394 Mhz
BIOS Version:              Microsoft Corporation Hyper-V UEFI Release v2.5, 8/22/2017
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              N/A
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     4,607 MB
Available Physical Memory: 4,144 MB
Virtual Memory: Max Size:  5,631 MB
Virtual Memory: Available: 5,179 MB
Virtual Memory: In Use:    452 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              N/A
Hotfix(s):                 2 Hotfix(s) Installed.
                           [01]: KB4131372
                           [02]: KB4103727
Network Card(s):           N/A
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
PS E:\Lab\SQLServerV2>
```


Any help would be appreciated.

**Comment by jjburr** [comment]
Id also like the packages for 2016 - as when creating a custom image from the downloaded media, the docker build works. But the containers never start after docker run - and time out :(
