### ISSUE TITLE
Login failed for user 'sa'

### ISSUE THREAD

**Issue by ThibaultGrg** [Microsoft/mssql-docker#301]
Hi,

Sorry to open another issue of this type but I couldn't find a resolution in the previous issues. I use the following statement to run mssql in my container:

docker run -d --name sql_server_thib -e 'ACCEPT_EULA=Y' -e MSSQL_SA_PASSWORD=‘Xx12Xxxxx12’ -p 1433:1433 microsoft/mssql-server-linux

My password has capitale letter, small letter, digits and is 11 character long therefore conforms to the recommendations. I get the mssql running fine in my container but am unable to connect using:

mssql -u sa -p Xx12Xxxxx12

I got the error (from container logs):

2018-05-07 22:48:05.11 Logon       Login failed for user 'sa'. Reason: Password did not match that for the login provided. [CLIENT: 172.17.0.1]

I tried to solve the issue for hours yesterday, tried many different password, simple/double quote around it but nothing works. How could I make sure I start with a clean slate for the sa password ? I think the first run string I used wasn't correct and the very first password set considered more characters than expected so I can't determine this password anymore. Removing /var/opt/mssql folder inside my container didn't solve either.

Thanks in advance.

Regards,
Thibault

**Comment by twright-msft** [comment]
Are you using a -v volume mount?

**Comment by twright-msft** [comment]
Try this instead:
mssql -s 127.0.0.1 -u sa -p Xx12Xxxxx12

**Comment by ThibaultGrg** [comment]
Same result using this.. The only reason I can see is that the password is not updated upon stopping container -> deleting container -> docker run. I looked extensively for ways to change this password (but you need the current one to do so) or reset it but through docker and command line I didn't find any answer..

**Comment by twright-msft** [comment]
I have this sneaking suspicion it's the mssql client that you are using.  Maybe try using sqlcmd or mssql-cli?
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-linux-2017#macos

https://github.com/dbcli/mssql-cli/blob/master/doc/installation/macos.md#macos-installation

I recommend mssql-cli.

**Comment by amitsaha** [comment]
@ThibaultGrg if you end up using `sqlcmd`, the connection string needs to have the `tcp` in it, like so:
(See [here](https://weblogs.asp.net/jongalloway/sql-force-the-protocol-tcp-named-pipes-etc-in-your-connection-string) to learn more about forcing protocol types)
```
$ sqlcmd -S tcp:127.0.0.1 ..
```

My container was started as:

```
$ docker run -d -p 1433:1433 -e sa_password=HelloWorld10 -e ACCEPT_EULA=Y microsoft/mssql-server-windows-express:2017
```

Hope that helps.

**Comment by ThibaultGrg** [comment]
Finally works! Weirdly enough it was the quote around my password in the docker run command that were causing the password to be considered wrongly. I had tried simple and double quote and it never worked but removing them completely solves the issue. Thanks for the help!

**Comment by wallism** [comment]
For me, I only put my password after -e:
-e 'mystrongpwd'
completely missing the SA_PASSWORD! This fixed it (with a valid pwd)
-e 'SA_PASSWORD=mystrongpwd'

PEBKAC

**Comment by kakins** [comment]
I have this same issue after successfully connecting yesterday.  After connecting, I deleted the container.  Then I created a new instance using the same command/password.  Now it is saying login failed for 'sa', 'Password did not match for login provided'.

**Comment by Serhioromano** [comment]
> Are you using a -v volume mount?

What if yes? I used it

```
docker run -e ACCEPT_EULA=Y 
    -e MSSQL_SA_PASSWORD=****
    --name mssql 
    -p 1433:1433 
    -v /c/Users/serhi/mssql/data:/var/opt/mssql/data 
    -v /c/Users/serhi/mssql/log:/var/opt/mssql/log 
    -v /c/Users/serhi/mssql/secret:/var/opt/mssql/secrets 
    -d mcr.microsoft.com/mssql/server:2017-latest
```

Cannot connect Azure Data Studio. I am in a Docker run on Windows, container started from WSL.

**Comment by abramadams** [comment]
Worth a mention, but make sure that if you have an instance of SQL Server installed on the host, that you have it (and all related sql services) stopped.  This caused login issues for me and took far to long to figure out.  

In my case the services had been stopped previously when the image was built, but was set to auto start so the next time I rebooted my host, I could no longer log into the docker SQL database.  I could shell into the container and sqlcmd login just fine and other docker containers could log into sql, just not from the host.

**Comment by SonGokussj4** [comment]
OH MY GOD You re GOLD. I couldn't resolve this for a week! then I opened SQL Server Configuration, stopped the service and IT WORKS... Sorry for the uppercase but I'm just so happy right now. **Thank you!**

**Comment by mtsurov** [comment]
Yep, 2 solid days of banging my head against the wall. 
never crossed my mind to stop the service. 
THANK YOU !!!!

**Comment by Mikolaj-Bochenek** [comment]
> > Are you using a -v volume mount?
> 
> What if yes? I used it
> 
> ```
> docker run -e ACCEPT_EULA=Y 
>     -e MSSQL_SA_PASSWORD=****
>     --name mssql 
>     -p 1433:1433 
>     -v /c/Users/serhi/mssql/data:/var/opt/mssql/data 
>     -v /c/Users/serhi/mssql/log:/var/opt/mssql/log 
>     -v /c/Users/serhi/mssql/secret:/var/opt/mssql/secrets 
>     -d mcr.microsoft.com/mssql/server:2017-latest
> ```
> 
> Cannot connect Azure Data Studio. I am in a Docker run on Windows, container started from WSL.
> 
> And I can confirm that I can connect without mounts

If you used bind mount volume to persist your data you could also persisted your SA_PASSWORD. If you would then create a new mssql container using the same bind mount and the different new SA_PASSWORD, the new password could be overriten by the old stored on disk. This could cause some unexpected login error.

**Comment by GarryLodge** [comment]
Good call abramadams.  I changed the externally exposed port to 14330 and now both Docker SQL container and locally installed SQL Server run together.

ExposedPorts = new Dictionary<string, EmptyStruct> { { "1433", default },  },
HostConfig = new HostConfig
    {
         PortBindings = new Dictionary<string, IList<PortBinding>>
         {
              {"1433", new List<PortBinding>{new PortBinding{HostPort = "14330"}}}
         }
     },

**Comment by tracker1** [comment]
`-e MSSQL_SA_PASSWORD=‘Xx12Xxxxx12’`

Likely the quotes are part of the password... for vars, quote the whole string including the left side of the assignment.

`-e "MSSQL_SA_PASSWORD=Xx12Xxxxx12"`

**Comment by seantleonard** [comment]
Thank you @abramadams ! worked like a charm after a good amount of time troubleshooting before finding this issue.

In my case, I didn't want to restart the host after disabling host instances of SQL server, so I modified the port mapping for docker run with `-p 1435:1433` per [Docker Docs](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose):

`docker run -d -e ACCEPT_EULA=Y -e MSSQL_SA_PASSWORD=12345678 -p 1435:1433 --name myDB mcr.microsoft.com/mssql/server:2019-latest`

**Comment by theMillenniumFalcon** [comment]
> Are you using a -v volume mount?

Yes, I am 

```
docker run -it --rm --name sql_container --hostname sql_container -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Str0ngPa$$w0rd" -v mysql:/var/lib/mysql -d -p 1433:1433 mcr.microsoft.com/mssql/server
```

On trying to connect to the container through [Azure data studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall) using the following credentials:

![Screenshot (2)](https://github.com/microsoft/mssql-docker/assets/73386487/bf66a7bd-15e7-4f5a-b8aa-0b9b075bc1cc)

I am getting the following error:

![Screenshot (4)](https://github.com/microsoft/mssql-docker/assets/73386487/ff1ed177-9e56-4a5e-b3e9-eec2ed762a3a)

**Comment by darkrepulsor** [comment]
> Finally works! Weirdly enough it was the quote around my password in the docker run command that were causing the password to be considered wrongly. I had tried simple and double quote and it never worked but removing them completely solves the issue. Thanks for the help!

THANK YOU VERY MUCH!!! Today I was completing 3 days trying to find why I couldn't connect!!! 

DO NOT PASS QUOTES!!

**Comment by pf-uvonceumer** [comment]
> > > Are you using a -v volume mount?
> > 
> > 
> > What if yes? I used it
> > ```
> > docker run -e ACCEPT_EULA=Y 
> >     -e MSSQL_SA_PASSWORD=****
> >     --name mssql 
> >     -p 1433:1433 
> >     -v /c/Users/serhi/mssql/data:/var/opt/mssql/data 
> >     -v /c/Users/serhi/mssql/log:/var/opt/mssql/log 
> >     -v /c/Users/serhi/mssql/secret:/var/opt/mssql/secrets 
> >     -d mcr.microsoft.com/mssql/server:2017-latest
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Cannot connect Azure Data Studio. I am in a Docker run on Windows, container started from WSL.
> > And I can confirm that I can connect without mounts
> 
> If you used bind mount volume to persist your data you could also persisted your SA_PASSWORD. If you would then create a new mssql container using the same bind mount and the different new SA_PASSWORD, the new password could be overriten by the old stored on disk. This could cause some unexpected login error.

This helped me. Turns out during testing the wrong sa password was persisted. I deleted my volumes and then it worked!

**Comment by HakanBayazitHabes** [comment]
You can look at the link below
https://stackoverflow.com/questions/52052494/login-fails-for-sa-sql-server-linux-docker/75245069#75245069
