### ISSUE TITLE
Default sa password

### ISSUE THREAD

**Issue by JacoSmit** [Microsoft/mssql-docker#310]
Hi,

I know containers have only one service, but I am trying to install an application based on  the mssql-server-windows-developer container, i.e. SQL Server and the application on the same container. 

My problem is that I cannot seem to login to SQL Server  using the specified sa password in the cmd script I use to start the install and my application.

The cmd script I am using looks like the following:
```
start cmd /c CALL ".\start.ps1 -sa_password PassW0rd123# -ACCEPT_EULA Y -Verbose
sqlcmd -U sa -P PassW0rd123#
``` 

The problem is that the `sqlcmd` command logs that the password is not correct when trying to login. 
What is the default password for the sa account? I want to see if I can perhaps use that?
Do you see anything wrong with the commands I am running?

Thank you.

**Comment by twright-msft** [comment]
The SA password is passed in at docker run time via the environment variable SA_PASSWORD.  See example here:  https://hub.docker.com/r/microsoft/mssql-server-windows-developer/

**Comment by JacoSmit** [comment]
Hi, 

The base example on the page mentioned in your comment works. However, the problem is that whenever I run the `start.ps1` script manually from a `.cmd` file it would not use specified sa password.

**Comment by JacoSmit** [comment]
I managed to fix the issue. I was using a password that contained a '$' sign. This was then interpreted by powershell as a variable rather than a literal string value, since I used powershell to run my .cmd file.

The problem was fixed when I changed the '$' sign to something else.
