### ISSUE TITLE
 Login failed for user 'SA'  running microsoft/mssql-server-linux

### ISSUE THREAD

**Issue by logcorner** [Microsoft/mssql-docker#319]
Hi when I try to connect to sql server container, I have the following error :    Login failed for user 'SA'
![untitled picture](https://user-images.githubusercontent.com/5066547/40890184-4a6e7cde-6772-11e8-800d-bf35f91b3556.png)

![docker version](https://user-images.githubusercontent.com/5066547/40890185-506a27b4-6772-11e8-9fac-2fee2450eb41.png)

Event if I run this sample : https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-2017

**Comment by vin-yu** [comment]
can you try changing the password to something like '12345qwerASDF'

**Comment by logcorner** [comment]
thank @vin-yu
It works fine using password 12345qwerASDF
what is the password rules using linux container ?
Regards

**Comment by vin-yu** [comment]
- The password does not contain the account name of the user.
- The password is at least eight characters long.
- The password contains characters from three of the following four categories:
1. - Latin uppercase letters (A through Z)
2. - Latin lowercase letters (a through z)
3. - Base 10 digits (0 through 9)
4. - Non-alphanumeric characters such as: exclamation point (!), dollar sign ($), number sign (#), or percent (%).

https://docs.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-2017

**Comment by Grinderofl** [comment]
How do I turn this off though? If I'm installing this on a local machine for trialing, I don't want to have to use a "strong password". How can I disable the password policy requirements (before installing)?

**Comment by twright-msft** [comment]
@Grinderofl  - Sorry there is not a way to disable the password policy check right now.

**Comment by saryeHaddadi** [comment]
Just wanted to say that for local testing, it would be nice to launch the container with an environment variable that would disable the password policy enforcement. This helps for the first experience, I would want to put an easy password so that I just run it.

**Comment by xiaohuazi123** [comment]
OOPS
