### ISSUE TITLE
Graceful service shutdown on stop

### ISSUE THREAD

**Issue by jmfirth** [Microsoft/mssql-docker#32]
What is the recommended approach to ensuring a graceful termination of the SQL service on container termination?  Correct me if I'm wrong, but my understanding is that this is blocked on Windows container images until Windows containers receive notifications that come in docker 1.14.0.  But such a thing should be possible for the Linux image?

**Comment by twright-msft** [comment]
On Linux, the sqlservr process will receive a SIGTERM signal and shut down gracefully in the case of `docker stop`.  If you do something evil like `docker rm -f` or `docker kill` then the sqlservr process will receive a SIGKILL and immediately die.  If you want to be really gentle you can use `docker stop -t 30` or something like that to give the sqlservr process more than 10 seconds to shut down gracefully.

**Comment by jmfirth** [comment]
Thank you kindly!
