### ISSUE TITLE
How licencing works in sql server container?

### ISSUE THREAD

**Issue by nileshkrishnan** [Microsoft/mssql-docker#324]
Hi,

i am interested to use sql server container, apart from giving the ACCEPT_EULA=Y , what needs to be done?
how Microsoft is ensuring i am  running with a valid licence?

Nilesh

**Comment by twright-msft** [comment]
Hi Nilesh - 
Please see the licensing guide for SQL Server 2017 for details on licensing SQL Server in containers.
http://download.microsoft.com/download/7/8/c/78cdf005-97c1-4129-926b-ce4a6fe92cf5/sql_server_2017_licensing_guide.pdf

Other than the ACCEPT_EULA=Y there are no other technical checks - no product keys, etc.  Of course, you are expected to use the product in compliance with the license terms and ensure that you have paid for SQL Server in cases where that is required - i.e. production use of SQL Server Standard, Web or Enterprise Edition for example.

**Comment by nileshkrishnan** [comment]
thanks , but then  anyone can use the image without actual licence.

**Comment by twright-msft** [comment]
That's true.  There are no technical limitations.  BTW - the same is true of the SQL Server on Linux packages.  A product key is not required to run any edition of SQL Server on Linux.  People that want to cheat the system have lots of ways of doing that.  We're not trying to prevent piracy here; just relying people's honesty.
