### ISSUE TITLE
Can we enable windows login?

### ISSUE THREAD

**Issue by ghost** [Microsoft/mssql-docker#332]
We use integrated security allot on our dev machines. I was wondering if we can connect to docker instance using Windows Authentication

**Comment by twright-msft** [comment]
If you are using Windows containers then you can theoretically use global managed service accounts to do this.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts
We havent spent much time testing that though.
We are working on Kerberos/AD auth for Linux containers now.  Please see the status of that on issue #165
