### ISSUE TITLE
Why cant i successfully make my own mssql-server-windows-express image with the supplied docker files & .ps1 script? 

### ISSUE THREAD

**Issue by ctgarvey** [Microsoft/mssql-docker#334]
I cannot successfully build and run this image on win 10 enterprise 1803. I can successfully run the already built image, and i can build the image myself but when i try to run the image i just built myself , the container stops after about a minute because of:

> docker logs 8fd
VERBOSE: Starting SQL Server
start-service : Failed to start service 'SQL Server (SQLEXPRESS)
(MSSQL$SQLEXPRESS)'.
At C:\start.ps1:27 char:1
+ start-service MSSQL`$SQLEXPRESS
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl
   ler:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands
   .StartServiceCommand

Is there any reason this will not build on win 10 1803 ?  I cannot use this image successfully as a parent image for another build (i have given up trying to troubleshoot it) so Im back to basics to see if i can at least get it to build with the  default supplied ms docker file & ps1 script. 

host os: win 10 enterprise 1803
docker: 18.03.1-ce

using dockerfile and ps1 from here:

https://github.com/Microsoft/mssql-docker/tree/master/windows/mssql-server-windows-express

**Comment by twright-msft** [comment]
Can you please share the output from the docker build command?

**Comment by ctgarvey** [comment]
Hello again :->. Please see build output below. I am using files from github (https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-express/dockerfile) . I had a query about the param() keyword not being within a function in the start.ps1, but the script is failing at the first attempt to start the SQL service. (line 27), so i dont think param() is relevant here

Build output:

PS E:\spikecontainerstaging\microsoftsqlservercontainer> docker build  -t mssqlexpresscontainer .
Sending build context to Docker daemon  6.656kB
Step 1/10 : FROM microsoft/windowsservercore
 ---> 9dbf7f740334
Step 2/10 : LABEL maintainer "Perry Skountrianos"
 ---> Running in b6c503d1a09c
Removing intermediate container b6c503d1a09c
 ---> 4c16f935f0cf
Step 3/10 : ENV sql_express_download_url "https://go.microsoft.com/fwlink/?linkid=829176"
 ---> Running in c1d74ad98892
Removing intermediate container c1d74ad98892
 ---> e8144a02ca33
Step 4/10 : ENV sa_password="_"     attach_dbs="[]"     ACCEPT_EULA="_"     sa_password_path="C:\ProgramData\Docker\secrets\sa-password"
 ---> Running in 4c2d534d6389
Removing intermediate container 4c2d534d6389
 ---> ef539c31c003
Step 5/10 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Running in 59b212174c86
Removing intermediate container 59b212174c86
 ---> ffab15ca5d2a
Step 6/10 : COPY start.ps1 /
 ---> 7e67ce242435
Step 7/10 : WORKDIR /
Removing intermediate container b0a04b875c05
 ---> 48a4439a6bc0
Step 8/10 : RUN Invoke-WebRequest -Uri $env:sql_express_download_url -OutFile sqlexpress.exe ;         Start-Process -Wait -FilePath .\sqlexpress.exe -ArgumentList /qs, /x:setup ;         .\setup\setup.exe /q /ACTION=Install /INSTANCENAME=SQLEXPRESS /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT='NT AUTHORITY\System' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS ;         Remove-Item -Recurse -Force sqlexpress.exe, setup
 ---> Running in 23157c9d5871
Microsoft .NET Framework CasPol 4.6.1586.0
for Microsoft .NET Framework version 4.6.1586.0
Copyright (C) Microsoft Corporation.  All rights reserved.

WARNING: The .NET Framework does not apply CAS policy by default. Any settings
shown or modified by CasPol will only affect applications that opt into using
CAS policy.

Please see http://go.microsoft.com/fwlink/?LinkId=131738 for more information.


Success
Microsoft .NET Framework CasPol 4.6.1586.0
for Microsoft .NET Framework version 4.6.1586.0
Copyright (C) Microsoft Corporation.  All rights reserved.

WARNING: The .NET Framework does not apply CAS policy by default. Any settings
shown or modified by CasPol will only affect applications that opt into using
CAS policy.

Please see http://go.microsoft.com/fwlink/?LinkId=131738 for more information.


Success
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
Microsoft (R) SQL Server 2017 14.00.1000.169
Copyright (c) 2017 Microsoft.  All rights reserved.

Removing intermediate container 23157c9d5871
 ---> 48f0cee53bc9
Step 9/10 : RUN stop-service MSSQL`$SQLEXPRESS ;         set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ;         set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ;         set-itemproperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\' -name LoginMode -value 2 ;
 ---> Running in 2d55841ec435
Removing intermediate container 2d55841ec435
 ---> 05c6eb97ff0f
Step 10/10 : CMD .\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose
 ---> Running in ae9979aaf3f4
Removing intermediate container ae9979aaf3f4
 ---> 1aef8a9a097e
Successfully built 1aef8a9a097e
Successfully tagged mssqlexpresscontainer:latest
PS E:\spikecontainerstaging\microsoftsqlservercontainer>

**Comment by ctgarvey** [comment]
Im closing this as the microsoft windows & SQL image docker files and scripts are out of sync with the latest windows server core image (ie tagged as latest) and do not build .  Be warned!!! Solution provided here: https://github.com/Microsoft/mssql-docker/issues/279 (Basically use a specific window server core image, and dont rely on latest. There is no way however to know which tagged image to use.)

There was some chatter about getting docker files in sync with windows 1803 image.
