### ISSUE TITLE
Are there plans on keeping mssql-server-windows-express image up-to-date?

### ISSUE THREAD

**Issue by ccrowhurstram** [microsoft/mssql-docker#337]
[mssql-server-windows-express](https://hub.docker.com/r/microsoft/mssql-server-windows-express/tags/) image on docker hub is not being kept up to date.

Are there plans on updating this image on a regular cadence whenever:
* the base image updates
* SQL Server "service packs" are published

If not can you please update the Readme [here](https://github.com/Microsoft/mssql-docker/blob/master/README.md) and on docker hub to indicate that this image is not maintained.

Thanks
Christian

**Comment by ctgarvey** [comment]
I can only get the docker file to half-work in -it mode with windows server core , tagged as: 1709. The container will not even start with windows  tagged as: latest  (1803 ) running on windows 10 host  . The curious thing is that all the powershell scripting from both the docker file and also the start.ps1 work fine in a standard windows server core 1803 VM (windows server standard 10.0.17134 - not a container).
It looks like the SQL server image is not maintained and/or is out of sync with windows server core.

**Comment by christianacca** [comment]
I created my own image for windows server core 1803. This works on my win 10 Pro 1803 desktop machine.

You might want to give this image a try: https://hub.docker.com/r/christianacca/mssql-server-windows-express/

You could even have a go at building the image locally yourself: https://github.com/christianacca/dockerfiles/blob/master/mssql-server-windows-express/build.ps1

**Comment by vin-yu** [comment]
Hi @ctgarvey @christianacca, we are working on a plan to keep these images up-to-date where we push a new image whenever there are new CUs like we do with the sql server on Linux image, but it wont be in the short term. 

That said, in the short term, we'll push out an updated image based on 1803 in the coming weeks - thanks for the [image here]( https://hub.docker.com/r/christianacca/mssql-server-windows-express/) in the meantime 👍

**Comment by Koubek** [comment]
@vin-yu From the legal perspective, are we allowed to publish our versions of the SQL images publicly??? Where can we see any details saying what we can and can't do? Of course, we are using the standard MS products inside but I am not sure whether we can publish them via docker images.

**Comment by christianacca** [comment]
Thanks @vin-yu for the confirmation

**Comment by ctgarvey** [comment]
Hi @christianacca , i was able to build SQL server express on windows server core 1803 container with your modified dockerfile and start.ps1, thanks  so much! What was the main modification you made? Was it the following switch ? /SQLCOLLATION=$env:SQL_COLLATION

![image](https://user-images.githubusercontent.com/3577185/42898041-ebce2376-8ab9-11e8-9402-90e0a349dd8e.png)

My host is win 10 enterprise 1803

**Comment by christianacca** [comment]
Great to hear the build works on more than one machine ;-)

The differences are summarized here: https://github.com/christianacca/dockerfiles/tree/master/mssql-server-windows-express#differences-to-offical-image.

That said, I was able to take the existing [dockerfile](https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-express/dockerfile), add the 1803 tag to the base image (see [here](https://github.com/christianacca/dockerfiles/blob/master/mssql-server-windows-express/dockerfile#L3)) to get a working image for 1803.

The changes summarized above were just "nice to have" enhancements.

**Comment by christianacca** [comment]
@vin-yu, are you guys likely to be announcing anything about maintaining these windows images? If not can you update the [readme](https://github.com/Microsoft/mssql-docker/blob/master/README.md) to state these images are not maintained, ideally with a mention of future plans.

**Comment by comnam90** [comment]
What's happening with this @vin-yu?
It's hard to start driving SQL Container adoption when MS can't be bothered to maintain their own images :(

**Comment by davidda** [comment]
Is it true that there are no images for SQL Server 2017+ Standard/Enterprise on Windows, just on Linux? Is Windows not a supported OS when it comes to SQL Server and containers?

**Comment by twright-msft** [comment]
@davidda  - Correct, at the moment only SQL Server on Linux containers are supported in production.  SQL Server on Windows container images have been provided for SQL Server 2017 Express/Developer editions for dev/test purposes only and are not supported.

**Comment by amitmsft** [comment]
If you are interested in evaluating SQL Server on Windows Containers, then please sign up for the Early Adopter Preview here: https://aka.ms/sqleap

**Comment by Inspyro** [comment]
@twright-msft Does this mean if we create our own docker image based on a windows base image (e.g. ltsc2019) we need to use at least Sql Server 2019 for production? Or is Sql Server 2017 still production ready in docker for windows?

**Comment by soroshsabz** [comment]
@amitmsft I think update the CU of SQL Server 2017 and base image of them, is not relevant to SQL Server 2019 Early adaptation. so I think Microsoft must update official SQL Server image to support latest update of them.

I think this issue must be reopen and update SQL Server 2017 image in all version (like Developer, Express, and normal) @vin-yu
