### ISSUE TITLE
MS ODBC Driver + PYODBC Doesn't work within Ubuntu 18.04 Docker container

### ISSUE THREAD

**Issue by superbobdthm** [Microsoft/mssql-docker#342]
I wrote a simple little test app that connects to the database using SQLAlchemy / PyODBC / MS ODBC Driver 17. 

If I configure it for Ubuntu 16.04 everything works fine:
Git Repo: https://github.com/superbobdthm/mssql-odbc  (master branch)

If I configure it for Ubuntu 18.04, I receive the following error:
`sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.2.so.0.1' : file not found (0) (SQLDriverConnect)") (Background on this error at: http://sqlalche.me/e/dbapi)`

Git Repo: https://github.com/superbobdthm/mssql-odbc (ubuntu-18.04 branch)

I can run the exact same commands in the Dockerfile in an Ubuntu 18.04 Desktop or an Ubuntu:18.04 LXD container and I do not get the `Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.2.so.0.1` error. Everything works fine.

**Comment by superbobdthm** [comment]
I was able to resolve this. It appears that the ubuntu:18.04 Docker image doesn't contain `libssl1.0.0 libssl-dev`

**Comment by ttelfer** [comment]
Just ran into this issue. I'm not sure how this has been closed. Shouldn't the instructions be updated or better yet the package fixed to include this as a dependency?

**Comment by Kolvin** [comment]
@superbobdthm I spent hours on debugging this and thank you so much for your comment - a simple install within my container solved my issues <3

**Comment by superbobdthm** [comment]
@Kolvin Glad, I could help!

**Comment by mfoulds** [comment]
Thanks very much for this. I also spent ages trying to  debug this issue. 
I ran: ```apt-get install libssl1.0.0 libssl-dev``` and all worked ok.

**Comment by angebouabre** [comment]
Yes, the ubuntu:18.04 Docker image need `libssl1.0.0 libssl-dev` to be installed.

**Comment by einarwar** [comment]
Wow. After half a workday trying to get this to work, i found this post. I am running the ubuntu 18.10 docker image, and installing `libssl1.0.0 libssl-dev` worked for me as well. Thank you @superbobdthm !
