### ISSUE TITLE
Error building mssql-server-windows-developer

### ISSUE THREAD

**Issue by timothies** [Microsoft/mssql-docker#346]
Platform is Windows Server 2016 (OS Build 14393.2395)
Docker 17.06.2-ee-10

Steps to reproduce:
PS>  git clone https://github.com/Microsoft/mssql-docker.git
PS>  cd  .\mssql-docker\windows\mssql-server-windows-developer\
PS>  docker build .

Result is an error listed below and attached in screenshot
.\setup\setup.exe : The term '.\setup\setup.exe' is not recognized as the name of a cmdlet

![image](https://user-images.githubusercontent.com/4046886/43817983-c61c76f2-9b1f-11e8-9e65-419d1c4a7392.png)

Thanks for your help

**Comment by timothies** [comment]
I've tried again today and its working.  I have no explanation, it must be user error

**Comment by goswings** [comment]
Hi, I have the same issue, but sometimes works, sometimes not....Don't know how to fix it.
