### ISSUE TITLE
Run scripts if exists in directory

### ISSUE THREAD

**Issue by spboyer** [Microsoft/mssql-docker#349]
PostgreSQL in Docker has a feature where if script file exist in  a specified directory, upon init, these get executed by default user.

```
If you would like to do additional initialization in an image derived from this one, add 
one or more *.sql, *.sql.gz, or *.sh scripts under /docker-entrypoint-initdb.d (creating 
the directory if necessary). After the entrypoint calls initdb to create the default 
postgres user and database, it will run any *.sql files, run any executable *.sh scripts, 
and source any non-executable *.sh scripts found in that directory to do further 
initialization before starting the service.
```

This scenario is partcularly helpful for creating test case data or snapshot type data for local/environment based development and testing.

**Comment by twright-msft** [comment]
Thanks for the suggestion @spboyer .  This one is definitely high on our priority list.  We are tracking this as issue #11 .  I'll close this one out as a duplicate.  Please follow #11 for updates.  We will use this approach to also satisfy the requirement for other requests like #4 and #2 .
