### ISSUE TITLE
How to run SQL server on Windows Containers, instead of Linux Containers?

### ISSUE THREAD

**Issue by artcard** [Microsoft/mssql-docker#352]
never mind, I found out there are 2 versions for Docker, Windows and Linux Containers

Windows   (very large pull, almost 10GB)
https://github.com/Microsoft/mssql-docker/tree/master/windows 
 
Linux  (small pull, about 1GB)
https://hub.docker.com/r/microsoft/mssql-server-linux/

**Comment by twright-msft** [comment]
Yep, you got it.  YMMV on the Windows containers.  They are more experimental than the Linux ones which are supported in production.  We are working better quality Windows container images and will have those out pretty soon.
