### ISSUE TITLE
Can´t restore my database from a sql 14.0.1000.169 backup wich was hosted on windows server 2012 R2. Any help please

### ISSUE THREAD

**Issue by felixminom** [Microsoft/mssql-docker#362]

**Comment by amitmsft** [comment]
What is the error that you are getting?

**Comment by felixminom** [comment]
The error I was getting was something like "family incompatibility", I ALREADY SOLVED IT. I needed to have 4 instances of sql server, but the new server I was configuring works with Ubuntu Server 16.04, wich for deafult can't create more than 1 instance. So I decided to work with docker containers, where I can have 1 instance per container. It's the first time im working with docker so the error I made was that i named all the data volumen container with the same name. I followed microsoft tutorial. READ IT CAREFULLY AND UNDERSTAND WHAT YOU'RE DOING. 

https://docs.microsoft.com/en-us/sql/linux/tutorial-restore-backup-in-sql-server-container?view=sql-server-2017

Another mistake was that I was including files that my backup from sql server hosted on windows didn't create. This is comand to see what files you have for the backup:

sudo docker exec -it sql1 /opt/mssql-tools/bin/sqlcmd -S localhost \
   -U SA -P '<YourNewStrong!Passw0rd>' \
   -Q 'RESTORE FILELISTONLY FROM DISK = "/var/opt/mssql/backup/wwi.bak"' \
   | tr -s ' ' | cut -d ' ' -f 1-2

in my case i only have 2 files: (but in my case de WWI_PRIMARY was named as WWI)

LogicalName   PhysicalName
------------------------------------------
WWI_Primary   D:\Data\WideWorldImporters.mdf
WWI_Log   E:\Log\WideWorldImporters.ldf

**Finally the command i excuted to backup my db was:**

sudo docker exec -it sql1 /opt/mssql-tools/bin/sqlcmd \
   -S localhost -U SA -P '<YourNewStrong!Passw0rd>' \
   -Q 'RESTORE DATABASE WideWorldImporters FROM DISK = "/var/opt/mssql/backup/wwi.bak" WITH MOVE "WWI_Primary" TO "/var/opt/mssql/data/WideWorldImporters.mdf",  MOVE "WWI_Log" TO "/var/opt/mssql/data/WideWorldImporters.ldf"'


HOPE I HELPED SOMEONE WITH THE SAME PROBLEM

**Comment by amitmsft** [comment]
Thanks for replying with the solution. Glad to know that you were able to resolve the issue.
