### ISSUE TITLE
Is it safe to use linux containers on windows?

### ISSUE THREAD

**Issue by sanket03** [Microsoft/mssql-docker#377]
Hello team,
We are using SQL server [linux](https://hub.docker.com/r/microsoft/mssql-server/) container on windows machines. Just wanted to confirm if there are an security concerns we should be aware of, while using linux containers on windows machines. Thanks.

**Comment by twright-msft** [comment]
No specific security concerns at the moment, but keep in mind that there are several unresolved issues with using Linux containers on Windows right now and it's not supported for production use.  One of the main blockers is that LCOW doesnt support containers with more than 2 GB of RAM and SQL Server requires 3.25 to start.

**Comment by sanket03** [comment]
Thanks for a quick response. We started with windows containers but switched to Linux containers as we were facing issues with SQL server agent. SQL jobs would fail with error "sql server agent is not currently running so it cannot be notified of this action".
 Moreover I see an [issue ](https://github.com/Microsoft/mssql-docker/issues/124) where it was suggested to use Linux containers in place of windows for working with SQL server agent.
[This ](https://github.com/Microsoft/mssql-docker/issues/340) is another issue where similar concern related to SQL agent on windows containers is brought up.

**Comment by twright-msft** [comment]
If you use Docker for Windows you wont have this problem with the memory because Docker for Windows creates this MobyLinux VM on HyperV that you can size to whatever memory you want.  The docker CLI on your Windows host will interact with the docker engine inside of the MobyLinux VM and your Linux containers will run on the Linux VM.
https://docs.docker.com/v17.09/docker-for-windows/install/

Sorry this is so complex on Windows right now.  We are working on it with the Windows team....

**Comment by sanket03** [comment]
Yes, we are currently using Docker for Windows, and therefore was wondering on the memory limitation as we can always configure the amount of memory to be allocated for MobyLinux VM. Anyways,  thanks for confirmation.
It would be great if I can get some help on windows authentication/ AAD auth on SQL server containers

**Comment by twright-msft** [comment]
Yep, we are working on that too...

**Comment by twright-msft** [comment]
Use Linux containers on Linux VMs?  It's thoroughly tested and supported.  It works on any size VM supposing enough memory to support SQL Server itself (3.25 GB of RAM minimum).  The agent works.  Almost all the core engine features work in SQL Server on Linux.  You can use a managed orchestrator service like AKS underneath to easily provide a level of HA, flexibility and automation.  Linux might not be familiar to you, but if it is just a host for a SQL Server that you are connecting to from remotely anyway, maybe it doesn't matter as much what OS the SQL Server is running on?  Maybe it's worth a try and see what you think?  The docker experience itself is really not much different between Windows and Linux.

**Comment by sanket03** [comment]
Thanks for your explanation, but unfortunately we cannot go ahead with Linux VMs.
I went through certain docs where running Linux containers on Windows server 2016 is possible via lcow, but as you pointed out, it has a memory limitation of 2GB on containers.
Is there anyway I could try with some preview version of SQL server Windows containers where agent would work?
If not, then feel free to close this ticket and thanks a lot for your support.

**Comment by twright-msft** [comment]
Got it.  Look for something on Windows Server to be available by around end of calendar year.
