### ISSUE TITLE
Running dockerfile hangs at Success SQLServer 2017. Remaining steps do not run.

### ISSUE THREAD

**Issue by gforty** [Microsoft/mssql-docker#381]
Just trying to familiarize myself with windows containers I decided to attempt to build my own container using the dockerfile supplied with the Microsoft/mssql-docker project. When I run the build, it will get to the step where it installs sql express and it will hang at the Success...privacy policy details for sql server express 2017 (ver : 14.00.1000.169).
The host is a Windows 2016 server (ver : 10.0.14393) virtual machine (vbox) running with a docker pull microsoft/windowsservercore:latest (ver : 10.0.14393).
I can ctrl-c out of the build then do a docker run and it works however this is less than ideal as there are remaining tasks that need to run not to mention if I want to customize this dockerfile by adding additional tasks.
Thanks in advance.

**Comment by Pirlo-Zhang** [comment]
@gforty 

Which step you stuck in when building the dockerfile? 
What version of docker are you using ?
Can you have a look in your Docker logs in AppData or ProgramData?

Please have a check following similar thread and see if that helps.

["docker build" immediately hangs indefinitely. Windows 10](https://github.com/docker/toolbox/issues/613)



Currently

**Comment by gforty** [comment]
@Pirlo-Zhang Thanks for the response.
It hangs at, what seems to be, the end of the sqlexpress install where it provides several "Success!" messages. It is almost as if it is waiting on a response from the user.
I am running docker version 17.06.2-ee-16 (client and server)
I forgot to mention I am attempting to do this offline. I did a docker pull for the windowsservercore online. I slightly modified the code removing the web-request and adding a COPY task for the sqlexpress executable from this (line 16-20 in original dockerfile):

`COPY start.ps1 /
WORKDIR /

RUN Invoke-WebRequest -Uri $env:sql_express_download_url -OutFile sqlexpress.exe ; \
Start-Process -Wait -FilePath .\sqlexpress.exe -ArgumentList /qs, /x:setup ; \`

To this:
`COPY SQLEXPR_x64_ENU.EXE /sqlexpress.exe
 COPY start.ps1 /
WORKDIR /

#RUN Invoke-WebRequest -Uri $env:sql_express_download_url -OutFile sqlexpress.exe ; \
RUN Start-Process -Wait -FilePath .\sqlexpress.exe -ArgumentList /qs, /x:setup ; \`

I successfully built container using dockerfile with Invoke-WebRequest but not with my slight modification.
Thanks in advance!

**Comment by gforty** [comment]
OK. I apologize. If I wait long enough it eventually finishes. While I was attempting this build (several times yesterday), Windows update service had a hung process and was pegging the host VM's CPU so had I waited longer than an hour it eventually would have completed I believe. I freed up the CPU and reran with my modified Dockerfile and it ran successfully.
