### ISSUE TITLE
TDSSNIClient initialization failed with error 0xffffffff, status code 0x80. Reason: Unable to initialize SSL support

### ISSUE THREAD

**Issue by suvvenndu** [Microsoft/mssql-docker#382]
Tried running a container with following command:
`sudo docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=SecertP@ssW0rd!' -p 1433:1433 --name TestName-SqlServer microsoft/mssql-server-linux`

Container does not start with following error log:

> 2018-10-16 09:06:42.54 spid19s Error: 17182, Severity: 16, State: 1. 2018-10-16 09:06:42.54 spid19s TDSSNIClient initialization failed with error 0xffffffff, status code 0x80. Reason: Unable to initialize SSL support.
> 
> 2018-10-16 09:06:42.55 spid19s Error: 17182, Severity: 16, State: 1. 2018-10-16 09:06:42.55 spid19s TDSSNIClient initialization failed with error 0xffffffff, status code 0x1. Reason: Initialization failed with an infrastructure error. Check for previous errors.
> 
> 2018-10-16 09:06:42.56 spid19s Error: 17826, Severity: 18, State: 3.
> 
> 2018-10-16 09:06:42.56 spid19s Could not start the network library because of an internal error in the network library. To determine the cause, review the errors immediately preceding this one in the error log.
> 
> 2018-10-16 09:06:42.56 spid19s Error: 17120, Severity: 16, State: 1.
> 2018-10-16 09:06:42.56 spid19s SQL Server could not spawn FRunCommunicationsManager thread. Check the SQL Server error log and the operating system error log for information about possible related problems.

**Comment by twright-msft** [comment]
That's a new one I havent seen before.  What OS are you using?

**Comment by suvvenndu** [comment]
@twright-msft , I am using Ubuntu 18.04 (Bionic Beaver)

**Comment by twright-msft** [comment]
That might be the problem.  We dont support 18.04 yet (coming soon!).  Can you please try 16.04?

**Comment by suvvenndu** [comment]
Thanks  @twright-msft , Will be waiting for a release with 18.04 support. My home server runs on 18.04 , so switching back to 16.04 is not an option for me :( .

**Comment by suvvenndu** [comment]
Just did a a clean install of 18.04 and the image is working as expected. I suspect the root cause was Katoolin which change lots of meta data for Ubuntu.

When  Was having a look at the server using cockpit, I was seeing Kali Linux instead of Ubuntu.
