### ISSUE TITLE
How to use Windows authentication for SQL server Windows container

### ISSUE THREAD

**Issue by sai78** [Microsoft/mssql-docker#383]
Hello Team,

I Pulled **microsoft/mssql-server-windows-developer** image and run the image with SA user name and Password in my local system. I created one simple database in that container. I successfully connected to that database through SSMS using SA username. But is there any way we could use Windows Authentication to connect to SQL server container. Thanks in Advance.

**Comment by twright-msft** [comment]
Not yet.  This is tracked as #165
