### ISSUE TITLE
Documentation missing vital link / info

### ISSUE THREAD

**Issue by MaxxVelocity** [Microsoft/mssql-docker#388]
Creating a docker image with MSSQL will fail to produce a use-able instance and fail silently if a sufficiently complex password is not provided. This can be an expensive mistake for someone just learning Docker w/MSSQL and its not made very clear form the documentation. 

Furthermore, if one did notice the one mention of password complexity, they would still not be able to identify the requirements as there is a placeholder text where the link should be. 

Please update the documentation with either a working link or better yet, a brief description of the complexity requirements, so that future newcomers can avoid wasting time trying to understand why useless containers are being created. 

https://hub.docker.com/r/microsoft/mssql-server-windows-express/

**Comment by twright-msft** [comment]
Fixed it!
