### ISSUE TITLE
Dockerfile - Windows Server Equivalient to Linux needed

### ISSUE THREAD

**Issue by KernowCode** [microsoft/mssql-docker#399]
Hi, I have followed Julie Lerman example of preparing SQL Server instances as images where I am prefiguring the image with a database already created.  This works find for LINUX with the files below but I am struggling converting it to the microsoft/mssql-server-windows-developer.  Any help would be appreciated in convert over.  Many thanks.

I am using Docker For Windows CE - using Windows Containers on Windows 10 

> Dockerfile ...
FROM microsoft/mssql-server-linux:latest
ENV SA_PASSWORD=Passw0rd
ENV ACCEPT_EULA=Y
COPY entrypoint.sh entrypoint.sh
COPY sqlCmdStartup.sh sqlCmdStartup.sh
COPY sqlCmdScript.sql sqlCmdScript.sql
RUN chmod +x ./sqlCmdStartup.sh
RUN /bin/bash ./entrypoint.sh

> entrypoint.sh ...
#start the script to create the DB and data then start the sqlserver
./sqlCmdStartup.sh & /opt/mssql/bin/sqlservr || true

> sqlCmdStartup.sh ...
sleep 30s
/opt/mssql/bin/sqlcmd -S localhost -U sa -P Passw0rd -d master -i sqlCmdScript.sql

> sqlCmdScript.sql ...
shutdown with nowait
GO

**Comment by KernowCode** [comment]
Thankyou for trying to help but I have aleady explored the available documentation which is why I am here posting this request for help.  What I needed is a working translation of the above Linux scripts but for Windows.  Many thanks

**Comment by twright-msft** [comment]
@KernowCode - Any particular reason you want to use Windows containers instead of Linux?

**Comment by zlepper** [comment]
@twright-msft Not the op, but: Because we run on windows servers, which doesn't support LCOW. And missing windows and linux containers is still a so-so experience, if it works at all.

**Comment by amitmsft** [comment]
Please sign up for "SQL Server in Windows Containers" in the SQL Server EAP program if you are still interested in evaluating SQL Server on Windows Containers.
