### ISSUE TITLE
I am having issues using the attach_dbs with docker-compose

### ISSUE THREAD

**Issue by beaudryj** [Microsoft/mssql-docker#40]
So I have a few issues with the attach_dbs when using it with docker-compose, I attempted building off of the example json which fails as invalid JSON so I cleaned it up. 

```
[  
   {  
      "dbName":"MaxDb",
      "dbFiles":[  
         "C:\\temp\\maxtest.mdf",
         "C:\\temp\\maxtest_log.ldf"
      ]
   },
   {  
      "dbName":"PerryDb",
      "dbFiles":[  
         "C:\\temp\\perrytest.mdf",
         "C:\\temp\\perrytest_log.ldf"
      ]
   }
]
```
![image](https://cloud.githubusercontent.com/assets/2633564/23680015/b2c3314c-0357-11e7-91dc-6394c4fe0d9c.png)

![image](https://cloud.githubusercontent.com/assets/2633564/23680045/d46b144a-0357-11e7-90ea-e9b00c746df2.png)

Am I supposed to have this configured differently ?

**Comment by perrysk-msft** [comment]
[@beaudryj] Does it work with docker run?
docker run -d -p 1433:1433 -v C:/temp/:C:/temp/ -e sa_password=<YOUR SA PASSWORD> -e ACCEPT_EULA=Y -e attach_dbs="[{'dbName':'SampleDB','dbFiles':['C:\\temp\\sampledb.mdf','C:\\temp\\sampledb_log.
ldf']}]" microsoft/mssql-server-windows-express

**Comment by beaudryj** [comment]
I'll try it out when I get home, but why should that matter if both methods are going to be grabbing an environment variable that is being set?

**Comment by perrysk-msft** [comment]
It should not - I want to start by excluding everything else and see if the simple docker run with the attach_dbs var works on your side.

**Comment by beaudryj** [comment]
when I run the docker run it fails to find the files

**Comment by perrysk-msft** [comment]
Do you have the C:\temp\sampledb.mdf and C:\temp\sampledb_log.ldf files on the host?

**Comment by beaudryj** [comment]
I used mine but yes

**Comment by perrysk-msft** [comment]
Do you mind posting the exact error so we can repro on our side?

**Comment by perrysk-msft** [comment]
Also, I am assuming that you can docker run the microsoft/mssql-server-windows-express container if you do not pass the attach_dbs var?

**Comment by perrysk-msft** [comment]
Could you please try the following when you can (added \\):
docker run -d -p 1433:1433 -v C:/temp/:C:/temp/ -e sa_password= -e ACCEPT_EULA=Y -e attach_dbs="[{'dbName':'SampleDB','dbFiles':['C:\\temp\\sampledb.mdf','C:\\temp\\sampledb_log.
 ldf']}]" microsoft/mssql-server-windows-express

**Comment by beaudryj** [comment]
![image](https://cloud.githubusercontent.com/assets/2633564/23713291/7621d864-03f3-11e7-9595-3f7abebf75d8.png)

**Comment by perrysk-msft** [comment]
I was able to repro this behavior locally. By doing the following I was able to successfully run and connect to the container bypassing the error:

1. Assign an sa_password (E.g. -e sa_password=Password1!) instead of leaving it blank. [Sorry about that, I should have put a sample password (E.g. sa_password=<YourStrongPassword!>) in the docker run command above]
2. Not using the -a at the end of the command. We are currently looking into this to figure out why this is causing an issue. Will let you know what we find.

Could you please try the following and see if it works on your end (passing and sa_password and omitting the -a at the end):
docker run -d -p 1433:1433 -v C:/temp/:C:/temp/ -e sa_password=Password1! -e ACCEPT_EULA=Y -e attach_dbs="[{'dbName':'SampleDB','dbFiles':['C:\\temp\\sampledb.mdf','C:\\temp\\sampledb_log.
 ldf']}]" microsoft/mssql-server-windows-express

**Comment by beaudryj** [comment]
so it is not outputting anything now and when I do a docker ps there are no containers

**Comment by perrysk-msft** [comment]
- What environment are you using? Windows/Linux and what version
- What is the docker version that you have installed (docker info)

**Comment by beaudryj** [comment]
![image](https://cloud.githubusercontent.com/assets/2633564/23720078/a2ca8aec-040b-11e7-8425-496c7d181cca.png)

**Comment by perrysk-msft** [comment]
Thanks! Let me see if I can repro the same behavior on the same environment.

**Comment by beaudryj** [comment]
Just noticed on the os version thats running server 2016 not win 10

**Comment by perrysk-msft** [comment]
Are you on a Windows 10 or Windows Server 2016 host?

**Comment by beaudryj** [comment]
Windows Server 2016 Host

**Comment by perrysk-msft** [comment]
Did you follow the below article to setup? 
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server

**Comment by beaudryj** [comment]
Yeah I did. 

![image](https://cloud.githubusercontent.com/assets/2633564/23721070/a3202c42-040e-11e7-84ea-7ea2da9bbb88.png)

**Comment by perrysk-msft** [comment]
Let me setup a Win 2016 machine and get back to you.

**Comment by beaudryj** [comment]
👍 thank you for the quick replys, in the mean time I pulled down the dockerfile and force set the variables. I wonder if it would be possible to refactor this in a way to have the script convert the yml down to JSON for people using docker compose. 

ex: 
```
services:
  db:
    image: microsoft/mssql-server-windows-express
    environment:
      sa_password: "Password1"
      ACCEPT_EULA: "Y"
      attach_dbs: 
        dbname: sampledb
        dbfiles: '["C:\\temp\\maxtest.mdf","C:\\temp\\maxtest_log.ldf"]'
    ports:
      - "1433:1433" # REMARK: This is currently required, needs investigation
```

**Comment by perrysk-msft** [comment]
No problem :) Converting yml to JSON is a good idea - I'll add it to our backlog.

**Comment by perrysk-msft** [comment]
https://github.com/Microsoft/mssql-docker/issues/41

**Comment by perrysk-msft** [comment]
I followed all the instructions here (just to double check): https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server on a brand new Windows Server 2016 VM and I was not able to repro your issue.

Is it possible to share screens and troubleshoot further?

**Comment by perrysk-msft** [comment]
![5](https://cloud.githubusercontent.com/assets/7462604/23724322/266963a6-0401-11e7-95e3-3b284a830c97.PNG)
![4](https://cloud.githubusercontent.com/assets/7462604/23724329/2ed4fe74-0401-11e7-95f9-59bfadb3d71e.PNG)

**Comment by beaudryj** [comment]
Sure I might be able to get something going tomorrow

**Comment by perrysk-msft** [comment]
Sounds good - Ping me when you are ready.

**Comment by beaudryj** [comment]
So I revisited your formatting and believe there was a typo in my JSON in terms of working with double quotes and single quotes

**Comment by perrysk-msft** [comment]
Does it work on your side now? Should we close this issue?

**Comment by beaudryj** [comment]
Yeah I think so.

**Comment by perrysk-msft** [comment]
Thanks [@beaudryj].

**Comment by richmccloud** [comment]
@perrysk-msft 
Hi,
I am also have a problem running the attach_dbs from docker-compose.  Running the exact same command via docker run works just fine.  The container starts just fine, I can connect and validate that the volume (c:\temp) is there and I can see the mdf/ldf file.

Below is my docker-compose file and the error I am receiving.

Thanks

**docker-compose**
version: '3'
services:
  db:
    image: microsoft/mssql-server-windows
    environment:
      sa_password: "P@ssword!"
      ACCEPT_EULA: "Y"
      attach_dbs: "[{'dbName':'DemoAE','dbFiles':['C:\\temp\\DemoAE.mdf','C:\\temp\\DemoAE.ldf']}]"
    volumes:
      - "c:/temp:c:/temp"
    tty: true
    networks:
      default:
        ipv4_address: 192.168.1.101


**Error:**
Compose starts but error attaching db's:
db_1   | ConvertFrom-Json : Unrecognized escape sequence. (49): [{'dbName':'DemoAE',
db_1   | 'dbFiles':['C:\temp\DemoAE.mdf','C:\temp\DemoAE.ldf']}]
db_1   | At C:\start.ps1:36 char:30
db_1   | + $dbs = $attach_dbs_cleaned | ConvertFrom-Json
db_1   | +                              ~~~~~~~~~~~~~~~~
db_1   |     + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentEx
db_1   |    ception
db_1   |     + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Co
db_1   |    mmands.ConvertFromJsonCommand

**Comment by pradley** [comment]
Would be nice if you guys could post what the fix actually was im still having the same problem. Any help ?

**Comment by beaudryj** [comment]
Mine was a matter of using 4 \\\\ on the file path instead of 1 or 2

**Comment by MohsenAra** [comment]
it work with this env: 
attach_dbs: [{'dbName':'DemoAE','dbFiles':['C:\\temp\\DemoAE.mdf','C:\\temp\\DemoAE.ldf']}]

without quotation environment variable and use \\ instate of \
