### ISSUE TITLE
Please add tags in Docker Hub to the microsoft/mssql-server public repository.

### ISSUE THREAD

**Issue by clagreca03** [microsoft/mssql-docker#400]
In the legacy repository, API calls can be made (https://hub.docker.com/v2/repositories/microsoft/mssql-server-linux/tags/) that return the list of available images.

**Comment by forkazmoden** [comment]
Hi Chris,

For the tags you need, please refer to [microsoft/mssql-server-linux](https://hub.docker.com/r/microsoft/mssql-server-linux/)
