### ISSUE TITLE
EULA link has conflicting information with SQL Server Express T&C

### ISSUE THREAD

**Issue by skeeler** [microsoft/mssql-docker#401]
The ACCEPT_EULA link (http://go.microsoft.com/fwlink/?LinkId=746388) points to a document that suggests this is pre-release/preview software that cannot be used in production environments and is limited to 10 copies. This seems to conflict with the general usage terms for SQL Server Express. Require some clarification on availability of SQL Server Express docker image that can be used in production.

**Comment by forkazmoden** [comment]
Hi,

You can obtain a free SQL Server Express production license [here](https://go.microsoft.com/fwlink/?linkid=857693). If you want to run production container images，there are a few differences you should know. For more information, please refer to [Run production container images](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-2017#production).

**Comment by amitmsft** [comment]
The SQL Server Express on Windows Container is not a supported configuration for production use and is correctly stated as pre-release software. So please sign up for https://aka.ms/sqleap for Early Adoption Preview for SQL Server on Windows Cotnainers.
