### ISSUE TITLE
Windows container doesn't do port forwarding 

### ISSUE THREAD

**Issue by anthonyvdotbe** [Microsoft/mssql-docker#402]
When I execute:
`docker run -d -p 1433:1433 -e "sa_password=Afi2,23(gK" -e ACCEPT_EULA=Y microsoft/mssql-server-windows-developer`

`docker ps` shows the container is up:
> CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                   PORTS                    NAMES
735a0449a7ae        microsoft/mssql-server-windows-developer   "powershell -Command…"   About an hour ago   Up 2 minutes (healthy)   0.0.0.0:1433->1433/tcp   peaceful_heyrovsky

but the host isn't listening on port 1433 (verified with `netstat -a`).

I did move the ProgramData to another partition by adding `{"graph": "D:\\Docker Windows containers"}` to `C:\ProgramData\Docker\config\daemon.json`, but other than that, I haven't changed any Docker settings or configuration.

Docker version 18.09.0, build 4d60db4
Windows 10 Pro, version 1809, build 17763.194

**Comment by forkazmoden** [comment]
Hi,

Your command seems ok to me. Can you connect to the SQL Server instance from outside the container by using SSMS? Please refer to Connect from SSMS installed on the host from this [blog](https://cloudblogs.microsoft.com/sqlserver/2016/10/13/sql-server-2016-express-edition-in-windows-containers/).

**Comment by anthonyvdotbe** [comment]
@forkazmoden yes, I'm able to connect using SSMS, so the issue was using `netstat` to verify.

I found [this](https://stackoverflow.com/questions/36454955/docker-and-netstat-netstat-is-not-showing-ports-exposed-by-docker-containers) stackoverflow answer, which states that whether or not the port shows up in netstat, depends on using the [EXPOSE](https://docs.docker.com/engine/reference/builder/#expose) command in the Dockerfile.
