### ISSUE TITLE
Add EXPOSE in Dockerfile of Windows containers

### ISSUE THREAD

**Issue by anthonyvdotbe** [Microsoft/mssql-docker#406]
The Dockerfile of the Linux containers contains an `EXPOSE 1433` instruction. However, this is currently lacking in the Dockerfile of the Windows containers. 

[This](https://stackoverflow.com/questions/36454955/docker-and-netstat-netstat-is-not-showing-ports-exposed-by-docker-containers) stackoverflow answer states that, whether or not the port shows up in `netstat`, depends on using the [EXPOSE](https://docs.docker.com/engine/reference/builder/#expose) command in the Dockerfile. (see also #402)

**Comment by forkazmoden** [comment]
I tried to add `EXPOSE` instruction in Dockerfile to build a new image and the port still isn’t listed by netstat. 

> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                 PORTS                    NAMES
db297a6aa73a        test                "powershell -Command…"   2 hours ago         Up 2 hours (healthy)   0.0.0.0:1401->1433/tcp   cocky_poincare

I also tried to use docker run `--expose` to add the exposed port. But it don’t work to. I can only use `docker inspect` to find the post.

>  "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "db297a6aa73a6bc401fe139a3f96f4edaf59caca2f4e2199be6fd410d909056d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1401"
                    }
                ]
            },

**Comment by anthonyvdotbe** [comment]
@forkazmoden you're right, sorry about the noise. Since Linux containers do show up in netstat, I assume it's a generic issue with Windows containers.
