### ISSUE TITLE
Container Starts and Stops

### ISSUE THREAD

**Issue by TheMrAnderson** [Microsoft/mssql-docker#407]
Running Docker on unRAID server 6.6.6.  I have yet to be able to get the container to successfully start.  It will shut down within 4 seconds of starting.  I am getting the following in the log.

This program has encountered a fatal error and cannot continue running.
The following diagnostic information is available:

Reason: 0x00000003
Message: result
Stacktrace: 000055f17a081962 000055f17a014427
Thread: 11 (application thread 0x1000)
Instance Id: 241440d4-aad3-4cd2-bbaf-50e357d8ebef
Crash Id: 69b82135-a8b6-487f-af1f-cd76529dd599
Build stamp: 1dc223c2c297541dfebf5ce3265c3e74bbe289d287259e15dd32bd77f11bc1bd

Capturing core dump and information...
No journal files were found.
No journal files were found.
Attempting to capture a dump with paldumper
WARNING: Capture attempt failure detected
Attempting to capture a filtered dump with paldumper
WARNING: Attempt to capture dump failed. Reference /var/opt/mssql/log/core.sqlservr.7.temp/log/paldumper-debug.log for details
Attempting to capture a dump with gdb
WARNING: Unable to capture crash dump with GDB. You may need to
allow ptrace debugging, enable the CAP_SYS_PTRACE capability, or
run as root.

**Comment by forkazmoden** [comment]
Hi,

Could you please share your docker run command? 

And the error message looks like the following thread. See if it can help.
[Fatal error on startup #126](https://github.com/Microsoft/mssql-docker/issues/126)

**Comment by TheMrAnderson** [comment]
I've tried many different things and followed the suggestions in #126 but not yet found a resolution.  

Docker Run Command: docker run -d --name='SQL' --net='eth0.30' --privileged=true -e TZ="America/Chicago" -e HOST_OS="Unraid" -v '/mnt/user/Applications/MSSQL/':'/var/opt/mssql':'rw' -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -e '--cap-add=CAP_SYS_PTRACE' -e 'MSSQL_PID=Developer' 'mcr.microsoft.com/mssql/server'

**Comment by twright-msft** [comment]
Unfortunately, we've had quite a few issues reported with Unraid and it's not something we've tested or supported so far.  You can see a list of the issues with Unraid in this query:  https://github.com/Microsoft/mssql-docker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+unRAID
Is it possible to give it a try without unraid in the picture and on one of the supported OS and file system combos?

**Comment by TheMrAnderson** [comment]
My only other computer is a Mac, which I've read somewhere has issues running this container.  I can give that a shot and report back if you want.

**Comment by TheMrAnderson** [comment]
I've scrapped the idea of using this container on Unraid.
