### ISSUE TITLE
RAM value judgement

### ISSUE THREAD

**Issue by justin2004** [microsoft/mssql-docker#418]
why can't sqlservr just use swap space if it is available?

i have 1G physical RAM and 7G swap space but sqlserver still says:
"sqlservr: This program requires a machine with at least 2000 megabytes of memory."

and we can see what it is doing:
...
sysinfo({uptime=3532, loads=[20512, 54240, 90400], totalram=1037512704, freeram=308752384, sharedram=0, bufferram=0, totalswap=7516188672, freeswap=7420506112, procs=165, totalhigh=0, freehigh=0, mem_unit=1}) = 0
...

so it doesn't just try to malloc and fail or something but rather it looks for physical ram (using the sysinfo system call) and makes a value judgement for me. e.g. "your swap space isn't good enough."

see related: https://github.com/Microsoft/mssql-docker/issues/114
https://github.com/Microsoft/mssql-docker/issues/172
https://github.com/Microsoft/mssql-docker/issues/91

**Comment by forkazmoden** [comment]
Hi,

By default, a container has no resource constraints and can use as much of a given resource. It is feasible to configure swap on your Docker hosts by using `--memory-swap*` . But remember that swap is slower and less performant than memory. Please refer to [Limit a container's resources](https://docs.docker.com/config/containers/resource_constraints/).

**Comment by justin2004** [comment]
Hi @forkazmoden ,

I am not talking about limiting resources in a container (which is what --memory-swap does).

The issue here is that I am giving my container access to about 8G of virtual memory (physical + swap) and sqlservr is refusing to consider swap space when it makes its "This program requires a machine with at least 2000 megabytes of memory" decision.

sqlservr specifically calls the sysinfo system call to see how much physical memory I have and then refuses to run.

I'm wondering why sqlservr calls sysinfo and looks at the field "totalram" at all. Why does it not just attempt to malloc the amount of it needs?

**Comment by NamPNQ** [comment]
This problem should resolve, any update?

**Comment by justin2004** [comment]
@NamPNQ ,
I made a docker image that works around this limitation:
https://github.com/justin2004/mssql_server_tiny

**Comment by justin2004** [comment]
found a workaround

**Comment by vedrank** [comment]
> @NamPNQ ,
> I made a docker image that works around this limitation:
> https://github.com/justin2004/mssql_server_tiny

Hm...  

To run docker container from mcr.microsoft.com/mssql/server:2017-latest-ubuntu image with memory limit set to 512MB we had to set MSSQL_MEMORY_LIMIT_MB env variable.

Command:
docker run  -e 'MSSQL_MEMORY_LIMIT_MB=3'  -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password' --memory=512m -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-latest-ubuntu

Ref:
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2017

**Comment by justin2004** [comment]
@vedrank 
when you run
`docker run --memory=512m ubuntu cat /proc/meminfo | grep MemTotal`
do you see only 512m?

**Comment by firefixmaarten** [comment]
Just encountered the same bug:
# docker run --memory=512m ubuntu cat /proc/meminfo | grep MemTotal
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d19f32bd9e41: Pulling fs layer
d19f32bd9e41: Verifying Checksum
d19f32bd9e41: Download complete
d19f32bd9e41: Pull complete
Digest: sha256:34fea4f31bf187bc915536831fd0afc9d214755bf700b5cdb1336c82516d154e
Status: Downloaded newer image for ubuntu:latest
MemTotal:       32527792 kB

That is indeed all the memory on my machine.

Same issue with 2019-latest image in k8s, resource limit is totally ignored and it sees the host memory instead of the memory limit/request. Do we have a fix for this by now ?
