### ISSUE TITLE
start.ps1 - The system cannot find the file specified

### ISSUE THREAD

**Issue by mvalpreda** [microsoft/mssql-docker#421]
If there is some documentation I am missing, I am all for starting over......I am new to docker......

This is what I have done so far

- Set up Windows 2016 VM and current on Windows updates
- Installed Container role from Server Manager
- Install-Module DockerMsftProvider -Force
- Install-Package Docker -ProviderName DockerMsftProvider -Force
- Install-Package ContainerImage -Force
- Created strong SA password in C:\ProgramData\Docker\secrets\sa-password
- Copy\paste contents https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-express/dockerfile to c:\sql\dockerfile 
- Copy\paste contents https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-express/start.ps1 to c:\sql\start.ps1

c:\sql\> docker build - < dockerfile
Sending build context to Docker daemon  3.584kB
Step 1/10 : FROM microsoft/windowsservercore
 ---> ea9f7aa13d03
Step 2/10 : LABEL maintainer "Perry Skountrianos"
 ---> Using cache
 ---> 1b0f4f033900
Step 3/10 : ENV sql_express_download_url "https://go.microsoft.com/fwlink/?linkid=829176"
 ---> Using cache
 ---> 2cab396c57b9
Step 4/10 : ENV sa_password="_"     attach_dbs="[]"     ACCEPT_EULA="_"     sa_password_path="C:\ProgramData\Docker\secrets\sa-password"
 ---> Using cache
 ---> bf7e7861e6db
Step 5/10 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
 ---> Using cache
 ---> 30b552183943
Step 6/10 : COPY start.ps1 /
COPY failed: CreateFile \\?\C:\ProgramData\docker\tmp\docker-builder075099570\start.ps1: The system cannot find the file specified.

**Comment by forkazmoden** [comment]
Hi mvalpreda,

>COPY failed: CreateFile \?\C:\ProgramData\docker\tmp\docker-builder075099570\start.ps1: The system cannot find the file specified.

Please check if the file present in the directory that you're building from. Also check if there is a `.dockerignore` file in your build directory. Here is a similar thread. See if it can help.
[COPY / The system cannot find the file specified. #34893](https://github.com/moby/moby/issues/34893)
