### ISSUE TITLE
Failed to install fts in 2017-latest-ubuntu

### ISSUE THREAD

**Issue by vvkim20** [Microsoft/mssql-docker#422]
Running docker on Windows machine and used " docker pull mcr.microsoft.com/mssql/server:2017-latest-ubuntu" to get the image. then 

tried to install fts on the container (https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-full-text-search?view=sql-server-2017) 

root@7ab599da0d97:/# apt-get install -y mssql-server-fts
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package mssql-server-fts

Is this document dated? or linux docker is not working?

**Comment by forkazmoden** [comment]
Hi,

You need to import the public repository GPG keys and register the Microsoft Ubuntu repository first. Try this.

```
apt-get install -y curl

curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list | tee /etc/apt/sources.list.d/mssql-server.list

apt-get update
apt-get install -y mssql-server-fts
```

**Comment by vvkim20** [comment]
it works. Thanks!

**Comment by m4ttheweric** [comment]
does anyone have updated steps for 2019? i've been at it for 4 hours and I am dying.

**Comment by hericlesbitencourt** [comment]
> does anyone have updated steps for 2019? i've been at it for 4 hours and I am dying. trying to install sql server 2019 in a docker container running on a mac. need full text indexing.


```
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list | tee /etc/apt/sources.list.d/mssql-server.list

apt-get update
apt-get install -y mssql-server-fts
```

**Comment by AdhamRammadan** [comment]
cd ~/Downloads
`wget http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/multiarch-support_2.27-3ubuntu1_amd64.deb `
`sudo apt-get install ./multiarch-support_2.27-3ubuntu1_amd64.deb`
