### ISSUE TITLE
MSSQL Express DockerHub not linking to correct documentation

### ISSUE THREAD

**Issue by vegasbrianc** [microsoft/mssql-docker#427]
It appears the documentation that is being used in DockerHub is referencing a different source other than this GitHub repo. Additionally, it appears the source which is currently in use has incorrect Markdown formatting as the example Code block snippets don't display in DockerHub

Docker Hub -https://hub.docker.com/r/microsoft/mssql-server-windows-express
MSSQL Express docs - https://github.com/Microsoft/mssql-docker/tree/master/windows/mssql-server-windows-express

**Comment by forkazmoden** [comment]
Hi,

Which document in the link are you referring to?

**Comment by vegasbrianc** [comment]
@forkazmoden Thanks for your reply. If you notice the Docker Hub Link & MSSQL link are 2 completey seperate documents. Actually, the MSSQL Express doc is updated and has better examples.

The Docker Hub link as you notice doesn't properly display the code blocks from the MSSQL docs.

Is this clear?

**Comment by amitmsft** [comment]
SQL Server examples on Docker are available on the [official Microsoft documentation](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash). Please feel free to leave comments on the particular docs pages which you feel require changes/improvements.
