### ISSUE TITLE
Timezone: America/Chicago does not account for DST

### ISSUE THREAD

**Issue by nwarlen** [microsoft/mssql-docker#434]
##### 1. Run a container, passing in desired Timezone
```
docker run -e "TZ=America/Chicago" microsoft/mssql-server-linux:2017-latest
```
##### 3. Get Date using `SELECT GETDATE()`

---

#### Expected outcome:
Given the current offset for America/Chicago is `-5`, I would expect `SELECT GETDATE()` to return UTC time - 5 hours

###### Example:
UTC time: 12:00:00
expected: 07:00:00

---

#### Actual Result:
`SELECT GETDATE()` is returning the time related to the standard (non DST) offset `-6` i.e UTC time - 6 hours

###### Example:
UTC time: 12:00:00
actual: 06:00:00

**Comment by forkazmoden** [comment]
Hi,

That's a known issue. One option is install tzdata mannually in your container. Or you can add the following lines to your Dockerfile:
```
apt-get update
apt-get install tzdata
```

Please refer to[ Wrong offset for Europe/Moscow timezone](https://github.com/Microsoft/mssql-docker/issues/411).

**Comment by amitmsft** [comment]
SQL Server DateTime data type is not DST aware. Please file a feature ask for the same here: https://feedback.azure.com/forums/908035-sql-server

You can use the timezone offset for DST calculations. Reference: https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-2017

If you have questions regarding SQL Server database engine like the one here, then please leverage MSDN and StackOverflow.

I will close this thread as this is not a container specific issue.
