### ISSUE TITLE
Docker not opening SQL connection

### ISSUE THREAD

**Issue by alihoshaimy** [Microsoft/mssql-docker#435]
Hi Dears,

I am facing an issue with Docker on visual studio 2017 asp core 2.2. Every thing works fine when I run the project in IIS Express debug mode and able to do migrations. However, running in Docker Debug mode doesn't open the connection to sql server even that I am able to login in directly via SQL IDE using same credentials.

Error:
One or more errors occurred. (A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server))

Connection String:
"CatalogDB": "Data Source=localhost,1445;Initial Catalog=CatalogDB;User Id=sa;Password=CatalogApi(!);MultipleActiveResultSets=true"

Docker-compose.yml:
version: '3.4'

services:
  catalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    depends_on:
      - mssqlserver
         
  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    ports:
      - "1445:1433"

    container_name: mssqlcontainer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=CatalogApi(!)

Any Idea

**Comment by forkazmoden** [comment]
Hi,

Have you tried to use the IP address of your machine that hosts your container to do the connection?
`Data Source=W.X.Y.Z,1445`

**Comment by alihoshaimy** [comment]
Hi @forkazmoden 

I tried the ip found in ipconfig for docker and used it directly in MSSQL , worked. however still getting an error when running the application via docker compose:

Inner Exception 1:
SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)

**Comment by forkazmoden** [comment]
HI,

Can you post the compose file so that I can test on my environment?

**Comment by alihoshaimy** [comment]
Thank you @forkazmoden 

I have followed the steps in these URLs with no luck :(
https://docs.docker.com/compose/aspnet-mssql-compose/
https://kimsereyblog.blogspot.com/2018/10/docker-compose-asp-net-core-application.html

here is my compose file:
version: '3.4'

services:
  productcatalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: shoes-catalog
    ports:
      - "5000:80"
    depends_on:
      - sql.data
  sql.data:
    image: "mcr.microsoft.com/mssql/server"  
    #image: "microsoft/mssql-server-linux:latest"  
    ports:
      - "1445:1433"
    container_name: mssqlcontainer
    environment:
      SA_PASSWORD: "ProductApi(!)"
      ACCEPT_EULA: "Y"

**Comment by alihoshaimy** [comment]
Issue has been solved by updating the connection string as below regardless whether it is in appsettings.json or in docker-compose file:

version: '3.4'

services:
  productcatalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=db;Database=CatalogDb;User=sa;Password=ProductApi(!);MultipleActiveResultSets=true
    ports:
      - "5002:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "ProductApi(!)"
      ACCEPT_EULA: "Y"
    ports:
      - "1445:1433"

**Comment by demonguru18** [comment]
- "1445:1433" should be 1433:1433

Here is my Docker port mapped to sql container port on 1433
<img width="1412" alt="Screen Shot 2019-09-25 at 7 40 20 PM" src="https://user-images.githubusercontent.com/4347612/65647463-c997c500-dfcc-11e9-876d-b599679fad09.png">
