### ISSUE TITLE
How to connect to SQL Server hosted on Docker in Azure Ubuntu VM

### ISSUE THREAD

**Issue by vinuvt** [microsoft/mssql-docker#438]
Hi,

I have installed SQL Server 2019 docker on Azure Ubuntu VM. The container is up and running. However, I cannot connect to it using SSMS from outside the VM. While creating the container I used port 1450 to map to 1433. Also, I have configured the NSG to allow the traffic. Still, I have no luck.

![2019-03-21 14_51_36-Window](https://user-images.githubusercontent.com/6842188/54761073-4ba3cd00-4be9-11e9-9b18-4936efb5da62.png)

Thanks

**Comment by forkazmoden** [comment]
Hi,

If you want to connect from outside the container, you should specify the IP address and the port at the same time. Please refer to [Use SQL Server Management Studio on Windows to manage SQL Server on Linux](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-manage-ssms?view=sql-server-2017)

**Comment by vinuvt** [comment]
Thanks. That's exactly I am doing

**Comment by chaim1221** [comment]
I can't connect through the virt either on a KVM instance. I wonder if it's related? The machine is just not listening on :1433. The firewall rules for it to do so are in place, it just won't. Were you able to resolve this? It might help us as well.

**Comment by chaim1221** [comment]
It's worth noting that it does seem to be listening on ipv6, which is just not useful for our stack.

**Comment by chaim1221** [comment]
Turned out to be unrelated. Chef Docker cookbook. `publish_all_ports`. Sorry! Separate issue!
