### ISSUE TITLE
Some tags not listed on the docker hub page

### ISSUE THREAD

**Issue by aharpervc** [microsoft/mssql-docker#439]
Related: https://github.com/Microsoft/mssql-docker/issues/167, https://github.com/Microsoft/mssql-docker/issues/345, https://github.com/Microsoft/mssql-docker/issues/400

I'm disappointed that not all relevant tags are listed on the docker hub page, here: https://hub.docker.com/_/microsoft-mssql-server?tab=description

For example, these are missing:

* `2017-CU13-ubuntu`
* `2017-CU14-ubuntu`

And any of the 2019 CTP tags, such as

* `2019-CTP2.3-ubuntu`

I noticed this because I saw the blog post about CTP 2.4, and wondered if there was a new docker image, so I found the docker hub page and checked the tags, and it's not listed. So I was forced to guess what the tag _might_ be based on the CTP 2.3 tag name. But this is silly, I shouldn't have to guess your tag structure, because it ought to be clearly listed.

**Comment by forkazmoden** [comment]
Hi,

You can retrieve a list of all available tags for mssql/server at  https://mcr.microsoft.com/v2/mssql/server/tags/list

```
{
  "name": "mssql/server",
  "tags": [
    "2017-CU1-ubuntu",
    "2017-CU10",
    "2017-CU10-ubuntu",
    "2017-CU11",
    "2017-CU11-ubuntu",
    "2017-CU12",
    "2017-CU12-ubuntu",
    "2017-CU13",
    "2017-CU13-ubuntu",
    "2017-CU14",
    "2017-CU14-ubuntu",
    "2017-CU2-ubuntu",
    "2017-CU3-ubuntu",
    "2017-CU4-ubuntu",
    "2017-CU5-ubuntu",
    "2017-CU6-ubuntu",
    "2017-CU7-ubuntu",
    "2017-CU8-ubuntu",
    "2017-CU9-ubuntu",
    "2017-GA-ubuntu",
    "2017-GDR-ubuntu",
    "2017-latest",
    "2017-latest-ubuntu",
    "2018-CTP20",
    "2018-CTP20-ubuntu",
    "2019-CTP2.0",
    "2019-CTP2.0-ubuntu",
    "2019-CTP2.1",
    "2019-CTP2.1-ubuntu",
    "2019-CTP2.2",
    "2019-CTP2.2-ubuntu",
    "2019-CTP2.3",
    "2019-CTP2.3-ubuntu",
    "2019-CTP2.4",
    "2019-CTP2.4-ubuntu",
    "2019-latest",
    "latest",
    "latest-ubuntu",
    "vNext-CTP2.0-ubuntu"
  ]
}
```

**Comment by aharpervc** [comment]
Helpful, thanks. It would be nice if this sync'd to the docker hub page automatically somehow...
