### ISSUE TITLE
Migrate to Nano Server base image?

### ISSUE THREAD

**Issue by bazzilic** [Microsoft/mssql-docker#44]
Would it be possible to migrate to the Nano Server base image? At least for the Developer version: starting up the container takes a good minute or two on a pretty buffy machine, and then you'd need to wait for a minute or two while SQL Server starts accepting connections. Some of this time just accounts for the sheer size of the image, which is at least 5GB due to the size of the Server Core image.

Developers might need to re-run a container quite often, and it's getting annoying quite quickly :)

**Comment by perrysk-msft** [comment]
Thanks for the comment [@bazzilic]!
Unfortunately, SQL Server is not yet supported on Nano Server but we are working on it. 

1-2 minutes to start the container and 1-2 to start accepting connections seems like a lot - It takes ~5sec to start SQL Server and also start accepting connections according to simple tests that we did on our side. Do you mind sharing the hardware specs of the machine that you are using? We'd like to repro and look into it if possible.

**Comment by bazzilic** [comment]
It's an HP Z440 workstation: Win 10 Pro x64, Intel Xeon E5-1680 v4 (3.4 GHz, 20 MB cache, 8 cores), 16 GB.

Anyway, this is interesting, I assumed it was normal behavior so I didn't try to troubleshoot it. It is not an SSD machine, so I might need to look if the images are very fragmented or something. I am also running v1.13.0.9795 of Docker for Windows, which is from ~6 weeks ago, that might be the issue too.

**Comment by bazzilic** [comment]
Just tried it on a different machine (Win 10 Pro x64, Core i7 2.8 GHz, 16 GB _and_ an SSD drive; Docker for Windows v1.13.0) -- ~ 30-35 sec to start, 50 sec to start accepting connections.

**Comment by perrysk-msft** [comment]
Thanks for the test! 
~30-35 seconds for a hyper-v container (which is the only Windows container supported on Win 10) makes sense. I forgot to mention that **~5 sec** is the time we measured for a Windows Server core container. 

Note that you should see faster times when starting additional hyper-v Windows containers as files loaded in memory get reused. Do you get faster times after starting another container?

**Comment by bazzilic** [comment]
Just tried `docker run -d microsoft/windowsservercore` and then `docker run -it --rm microsoft/windowsservercore`. Second container took 18 sec to get me to cmd.exe prompt.

Also, I updated previous comment with some more timings, take a look if you haven't seen.

**Comment by perrysk-msft** [comment]
Thanks again for the additional perf numbers :) 
Improving startup times on Windows containers is something that the team is currently looking at and hopefully can improve moving forward.

**Comment by bazzilic** [comment]
Good to hear, hope to see results released soon!

**Comment by guillaume86** [comment]
@perrysk-msft hi, any progress on the nanoserver support?

**Comment by nguyenxndaidev** [comment]
@perrysk-msft Hi, do you have any news on this issue?
