### ISSUE TITLE
Missing example  for attach DB

### ISSUE THREAD

**Issue by SquallHalle** [microsoft/mssql-docker#444]
Hey Folks,

in the DockerHub Documentation you are missing the example command for attaching dbs. 
Thanks for fixing this.
:-)

Tobias

**Comment by forkazmoden** [comment]
Hi Tobias,

You mean something like this?
```
CREATE DATABASE MyAdventureWorks   
    ON (FILENAME = N'/var/opt/mssql/data/AdventureWorks_Data.mdf'),   
    (FILENAME = N'/var/opt/mssql/data/AdventureWorks_Log.ldf')   
    FOR ATTACH;  
```

**Comment by amitmsft** [comment]
All of our documentation for SQL Server on Containers is maintained now at https://docs.microsoft.com/en-us/sql/linux/
