### ISSUE TITLE
Connection fails in May Windows Update

### ISSUE THREAD

**Issue by eluchsinger** [microsoft/mssql-docker#446]
I had a working instance of the `microsoft/mssql-server-windows-developer:latest` container running and could connect until I changed to the preview ring and updated using the May update. Sadly, I can't go back to the previous ring right now. 

I ran this command:

`docker run -d -p 1433:1433 -v C:/temp/SqlServerDev:C:/temp/ -e sa_password=SpeciallyDifficultPassword123! -e ACCEPT_EULA=Y --name SqlServerDev microsoft/mssql-server-windows-developer:latest`

The container's state is `healthy` and I can connect to it by using `docker exec` and running the SQLCMD.

**Comment by eluchsinger** [comment]
I just reverted to Windows 1809 and it works flawlessly again. There is a problem with Windows May Update.

**Comment by forkazmoden** [comment]
Hi,

It seems that the issue is related to Windows update. You can feedback the problem to Windows support. Please refer to [Where Do I Report Windows 10 Issues?](https://askleo.com/report-windows-10-issues/)

**Comment by eluchsinger** [comment]
I don't think it's me who should open an issue with Windows support...

**Comment by amitmsft** [comment]
Thanks for the reporting the issue. If you are interested in working with Windows Containers, please sign up for the Early Adopter Preview for SQL Server on Windows Containers at https://aka.ms/sqleap. We currently do not support SQL Server on Windows Containers and it is something that the team is working on.
