### ISSUE TITLE
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'driver' : file not found (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by przemolb** [microsoft/mssql-docker#448]
Hi all,
I am trying to use a docker image built from https://github.com/Microsoft/mssql-docker/blob/master/oss-drivers/pyodbc/Dockerfile (and added python3) to connect to Azure SQL database.
```
import pyodbc
driver = 'ODBC Driver 17 for SQL Server'
server = 'sql_srv'
database = 'mydb'
uid = 'myadmin'
pwd = 'mypass'
con_string = r'DRIVER={driver};SERVER={server};DATABASE={database};UID={uid};PWD={pwd}'
cnxn = pyodbc.connect(con_string)

cursor = cnxn.cursor()

print ('Using the following SQL Server version:')
tsql = "SELECT @@version;"
with cursor.execute(tsql):
    row = cursor.fetchone()
    print (str(row[0]))
```
but I get the following error:
```
Traceback (most recent call last):
  File "/sample.py", line 22, in <module>
    cnxn = pyodbc.connect(con_string)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'driver' : file not found (0) (SQLDriverConnect)")
```
Can anyone hint me please what is missing ?

**Comment by forkazmoden** [comment]
Hi,

>>[unixODBC][Driver Manager]Can't open lib 'driver' : file not found (0) (SQLDriverConnect)")

The error indicates that the configuration file of the ODBC driver is not configured well. Please check it out with `odbcinst -j`

**Comment by przemolb** [comment]
```
root@49299e8d95f7:/sample# odbcinst -j
unixODBC 2.3.7
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /root/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8

root@49299e8d95f7:/sample# cat /etc/odbcinst.ini
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2
UsageCount=1

[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.3.so.1.1
UsageCount=1

root@49299e8d95f7:/sample# cat /etc/odbc.ini
root@49299e8d95f7:/sample# ls -al /etc/ODBCDataSources/
total 8
drwxrwxr-x 2 root root 4096 Dec  5 23:17 .
drwxr-xr-x 1 root root 4096 Apr 23 21:18 ..
```
What is missing/wrong ?

**Comment by przemolb** [comment]
Any hint what is missing ?

**Comment by behconsci** [comment]
@przemolb having same issue here, did you solve it?

**Comment by przemolb** [comment]
@behconsci yes, I did:
```
drivers = [item for item in pyodbc.drivers()]
driver = drivers[-1]
print("driver:{}".format(driver))
server = 'myserver'
database = 'mydb'
uid = 'myuser'
pwd = 'mypass'
con_string = f'DRIVER={driver};SERVER={server};DATABASE={database};UID={uid};PWD={pwd}'
print(con_string)
cnxn = pyodbc.connect(con_string)
...
```

**Comment by selvakarna** [comment]
How to connect SQL Using pyodbc Linux OS? I got error below when i use above code?


    raise Exception('This function is available for use in Windows only.')
Exception: This function is available for use in Windows only.

**Comment by yoshi-kim** [comment]
can you give an example of what you mean by "drivers = [**item for item in pyodbc.drivers()**]"

**Comment by jborichevskiy** [comment]
> can you give an example of what you mean by "drivers = [**item for item in pyodbc.drivers()**]"

It looks like @przemolb is simply making a list of the returned drivers from the `pyodbc.drivers()` function and using the last one in the list with `[-1]`.

In my case, here is what that looks like:
```python
In [34]: pyodbc.drivers()
Out[34]: ['ODBC Driver 13 for SQL Server']

In [35]: [item for item in pyodbc.drivers()][-1]
Out[35]: 'ODBC Driver 13 for SQL Server'

In [36]: driver = [item for item in pyodbc.drivers()][-1]

In [37]: driver
Out[37]: 'ODBC Driver 13 for SQL Server'
```

This driver string should now be passed as the parameter in the connection string like so:

`con = pyodbc.connect('DRIVER={driver};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)` 

assuming that you've set the `server, database, username, password` variables before this.

For reference, I'm using [this guide](https://www.microsoft.com/en-us/sql-server/developer-get-started/python/mac/step/2.html).

**Comment by yoshi-kim** [comment]
The connection string i'm attempting to connect with is as follows:
conn_string = "\
driver=/opt/cloudera/impalaodbc/lib/64/libclouderaimpalaodbc64.so; \
host=server.example.com; \
port=21050; \
database=default; \
AuthMech=1; \
KrbFQDN=server.example.com; \
KrbRealm=EXAMPLE.COM; \
KrbServiceName=impala; \
UseSASL=1; \
SSL=1; \
CAIssuedCertNamesMismatch=0; \
TrustedCerts=/opt/cloudera/impalaodbc/lib/64/cacerts.pem; \
Trusted_Connection=yes"

conn = pyodbc.connect(conn_string, autocommit=True)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.OperationalError: ('08S01', '[08S01] [Cloudera][ImpalaODBC] (100) Error from the Impala Thrift API: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (No Kerberos credentials available (default cache: KEYRING:persistent:123456789)) (100) (SQLDriverConnect)')

Is it possible to use a krb service name instead of a uid?

**Comment by anjanwahwar** [comment]
Hi, This error indicates the missing ODBC driver while building the docker images. I have got the same issue and resolved the same by explicitly providing instruction to install Linux ODBC driver.

Write below instruction in your docker file to make it work:
-======================================
RUN apt-get install curl
RUN apt-get install apt-transport-https
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list

RUN apt-get update
ENV ACCEPT_EULA=y DEBIAN_FRONTEND=noninteractive
RUN apt-get install mssql-tools unixodbc-dev -y

**Comment by vishnusagittarius** [comment]
Im facing this issue

**Comment by emilio-carrasco** [comment]
Thanks in advance for the help .

Ubuntu system.
Python 3.7
Installed pyodbc.
Installed Microsoft ODBC Driver for SQL Server (Linux Ubunti)

I am trying to connect using pyodbc. The connection string I am using is:

DRIVER={ODBC Driver 17 for SQL Server}; Server=XX; Database=XX; UID=XX; PWD=XX;

The error I get back is:

Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.2.1' : file not found (0) (SQLDriverConnect)")

I have tried uninstalling and reinstalling the driver several times but no luck. Everything remains the same.



odbcinst -j

unixODBC 2.3.9
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES...: /etc/ODBCDataSources
USER DATA SOURCES...: /home/emilio/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8


cat /etc/odbcinst.ini

ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.7.so.2.1
UsageCount=1

**Comment by joshua-obvience** [comment]
I'm having the same issue on June 17, 2021.

**Comment by jrenato7** [comment]
I started having the same issue when changing from Intel to Apple Silicon and run it over Docker. 

The output for "**_odbcinst -j_**" and "**_cat /etc/odbcinst.ini_**" commands inside my container was the same @emilio-carrasco's output.

The solution was to add the parameter "_**--platform linux/amd64**_" on the docker build command.

The final command became:
`docker buildx build --platform linux/amd64 . -t <image_nam>`

**Comment by ZacWang15** [comment]
```
import pyodbc
print(pyodbc.drivers())

>>> ['ODBC Driver\xa017\xa0for\xa0SQL Server']
```

If I replace 'ODBC Driver 17 for SQL Server' with 'ODBC Driver\xa017\xa0for\xa0SQL Server', it will work.
I don't know why Unicode '\xa0' is in the driver name.

**Comment by ERasheed21** [comment]
> Hi, This error indicates the missing ODBC driver while building the docker images. I have got the same issue and resolved the same by explicitly providing instruction to install Linux ODBC driver.
> 
> Write below instruction in your docker file to make it work: -====================================== RUN apt-get install curl RUN apt-get install apt-transport-https RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list
> 
> RUN apt-get update ENV ACCEPT_EULA=y DEBIAN_FRONTEND=noninteractive RUN apt-get install mssql-tools unixodbc-dev -y

`apt-key add -` seems to throw an error now "Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8))". Is there any easy fix to this line of code?

**Comment by ENO-QC** [comment]
I got this issue and fixed it this way : 

My code had "SQL Driver" changed it to " ODBC Driver 17 for SQL Server".

I also used @ERasheed21 and @anjanwahwar commands for my docker file : 

Write below instruction in your docker file to make it work:
-======================================
RUN apt-get install curl
RUN apt-get install apt-transport-https
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/msprod.list

RUN apt-get update
ENV ACCEPT_EULA=y DEBIAN_FRONTEND=noninteractive
RUN apt-get install mssql-tools unixodbc-dev -y

=======================================
But I changed it to my version "20.04", so here it is : 

**Write below instruction in your docker file to make it work:**
-======================================
RUN apt-get install curl
RUN apt-get install apt-transport-https
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/msprod.list

RUN apt-get update
ENV ACCEPT_EULA=y DEBIAN_FRONTEND=noninteractive
RUN apt-get install mssql-tools unixodbc-dev -y

**Comment by Sulecs1** [comment]
Hello everybody,
The connection string was also showing as driver 18. I was getting error due to this.
I performed these steps in order and found that there is odbc driver 17 on the back. It got better when he made 17 instead of 18.


1)odbcinst -j

<img width="229" alt="image" src="https://user-images.githubusercontent.com/61309605/214781099-ed91f034-3e8d-43db-813c-7a47e1a8d32e.png">

configure!
2) cat /etc/unixODBC/odbcinst.ini 


It's done!

**Comment by mockupoverflow** [comment]
hi, 

i think is a syntax problem (python)

import pyodbc

driver = 'ODBC Driver 17 for SQL Server'
server = 'sql_srv'
database = 'mydb'
uid = 'myadmin'
pwd = 'mypass'

instead of
  con_string = r'DRIVER={driver};SERVER={server};DATABASE={database};UID={uid};PWD={pwd}'

try:
con_string = r'DRIVER={driver};SERVER={server};DATABASE={database};UID={uid};PWD={pwd}' .format(driver=driver,server=server, database=database, uid=uid, pwd=pwd)

hope not too late :), was fighting on same issue
