### ISSUE TITLE
image won't run on Mac since docker updated to Docker Community Edition

### ISSUE THREAD

**Issue by sethdarr** [Microsoft/mssql-docker#45]
Since I updated my docker to Docker Community Edition, the microsoft/mssql-server-linux image will not start.  I've tried removing all my images and repulling, but no dice.  I'll do a

$ (sudo) docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=somelegitpasswordthatworked before' -p 1433:1433 -d microsoft/mssql-server-linux

It returns an ID, but when you immediately run "docker ps", there are no running images and you (obviously) can't connect to it.

My docker version (I'm on a Mac, btw):

Version 17.03.0-ce-mac2 (15657)
Channel: beta
32de842512

Thanks,
Seth

**Comment by twright-msft** [comment]
Hi @sethdarr - can you please check to make sure that you have 4GB+ of RAM allocated to Docker in the preferences?  If that doesnt sort it out, please remove the -d so that the container will output the log to the terminal and see if there is something there.

**Comment by sethdarr** [comment]
Bah!  That was the problem, all was fine after I allocated 4GB of RAM.  Live and learn.  Thanks!

**Comment by twright-msft** [comment]
Ha, great.  I've "learned" that lesson about 4 times now.  LOL
