### ISSUE TITLE
The file archive [/opt/mssql/lib/sqlserver.sfp] is invalid.

### ISSUE THREAD

**Issue by Orgoth** [Microsoft/mssql-docker#450]
After upgrading to a new version a file seems to be broken.

docker logs 53b1fd5f0010
```
The file archive [/opt/mssql/lib/sqlserver.sfp] is invalid.
```

Is there a way to repair this file?

**Comment by forkazmoden** [comment]
Hi,

Which version of SQL Server are you using? And could you try to downgrade SQL Server to a previous release?

**Comment by Orgoth** [comment]
Thanks for the quick answer.
Unfortunately I was in a bit of a hurry that day and didn't consider reinstalling the container.
You can delete this issue.
If I could reproduce the problem, I would write a new ticket with exact details.
Thanks anyway for the support. :+1:

**Comment by lukewis** [comment]
I'm seeing this error just following the steps on this tutorial: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver15&pivots=cs1-bash

Docker version 20.10.8, build 3967b7d
