### ISSUE TITLE
can not run containter for sqlserver

### ISSUE THREAD

**Issue by ClementeGao** [microsoft/mssql-docker#452]
sqlservr: This program requires a machine with at least 2000 megabytes of memory

**Comment by forkazmoden** [comment]
Hi,

Could you check the memory option in  Docker settings? Please try changing it from the default 2 GB to 4 GB or something and try running SQL Server on Linux again?

**Comment by ClementeGao** [comment]
i only want to go test sqlserver for linux,The server I bought had only 1 g of memory

**Comment by justin2004** [comment]
@ClementeGao ,

I made a docker image that works around this memory (limitation) policy:
https://github.com/justin2004/mssql_server_tiny

**Comment by ClementeGao** [comment]
OK thank you！
