### ISSUE TITLE
Instructions on docker-hub are incompatible with Windows cmd.exe

### ISSUE THREAD

**Issue by sakurai-youhei** [microsoft/mssql-docker#457]
**Issue**

There are a couple of instructions starting with `docker run -e 'ACCEPT_EULA=Y' ...` on docker-hub but the single quotation (`'`) doesn't work intentionally on Windows cmd.exe; All of the single quotations have to be translated to double quotations beforehand.

URL: https://hub.docker.com/_/microsoft-mssql-server

![image](https://user-images.githubusercontent.com/721858/58523148-5e94d800-81fe-11e9-8660-6943d7f82db7.png)

**What if just doing copy & paste on Windows cmd.exe**

The MSSQL claims acceptance to EULA, which is an annoying booby trap.

```
The SQL Server End-User License Agreement (EULA) must be accepted before SQL
Server can start. The license terms for this product can be downloaded from
http://go.microsoft.com/fwlink/?LinkId=746388.

You can accept the EULA by specifying the --accept-eula command line option,
setting the ACCEPT_EULA environment variable, or using the mssql-conf tool.
```

FYI: This may be duplicate of https://github.com/microsoft/mssql-docker/issues/210, https://github.com/microsoft/mssql-docker/issues/199 and https://github.com/microsoft/mssql-docker/issues/20.

**Comment by forkazmoden** [comment]
Hi,

You can also use Powershell to run the docker command. The single quotation (') will work.

**Comment by amitmsft** [comment]
Thank you for reporting the issue. SQL Server on Windows Containers is not supported yet. We are working to officially support this. If there is an interest in evaluating this as part of an early adopter program, please sign up here: https://aka.ms/sqleap.
