### ISSUE TITLE
question: where to get links for latest version of mssql-server-developer to update dockerfile?

### ISSUE THREAD

**Issue by SubjectiveReality** [microsoft/mssql-docker#461]
Hi - anybody know how or where to get updated links to install the latest version of mssql developer to update the corresponding dockerfile here https://github.com/microsoft/mssql-docker/blob/cc923c716f9042ee94fb9b4307ff33a39b3d7d72/windows/mssql-server-windows-developer/dockerfile#L6? 

Looks like lines 6 & 7 would need  to be updated.

**Comment by forkazmoden** [comment]
Hi,

If you want to use the latest version of SQL Server, you will have to install the update packages by yourself.

**Comment by amitmsft** [comment]
We are not updating the SQL Server Windows Developer images right now. We are working on providing images for SQL Server on Windows Container. Please sign up for the preview at https://aka.ms/sqleap
