### ISSUE TITLE
odsole70.dll  not found

### ISSUE THREAD

**Issue by 93Kamuran** [microsoft/mssql-docker#464]
I want to make http request from sqlserver here is my SP 

DECLARE @sUrl varchar(200)      
DECLARE @obj int      
DECLARE @response varchar(8000)      
      
SET @sUrl='http://xxxxxx?xx='+x
EXEC sp_OACreate 'MSXML2.ServerXMLHttp',@obj out      
EXEC sp_OAMethod @obj,'Open',NULL,'GET',@sUrl,false      
EXEC sp_OAMethod @obj,'send'      
EXEC SP_OAGetProperty @obj,'responseText',@response out      
       
--select @response [response]      
EXEC sp_OADestroy @obj

on windows servers ı was using these commands to allowing the configure 
sp_configure ‘show advanced options’, 1;
GO
RECONFIGURE;
GO
sp_configure ‘Ole Automation Procedures’,1
reconfigure

I run commands without any error but when  o triggered to SP 
this error occurs

"odsole70.dll  not found"

 when ı write this 'sp_helptext sp_OACreate'

ı can see   odsole70.dll but ı could not achieve to sen HTTP request

**Comment by amitmsft** [comment]
Are you trying this on a SQL Server on Linux container? SQL Server on Linux does not support extended stored procedures. Please see [this article](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes?view=sql-server-2017#Unsupported).
