### ISSUE TITLE
Support for older SQL Server versions?

### ISSUE THREAD

**Issue by paladini** [microsoft/mssql-docker#470]
I currently need to start a SQL Server 2008 in order to retrieve some old data that my company is working on right now. I would like to suggest to add these older versions on your Docker image, since there's a lot of companies that still use older versions of SQL Server.

This way, developers will be able to run SQL Server 200* versions from Linux, Windows and Mac (I'm currently using macOS Mojave, so I cannot use the original installer from Microsoft).

Any plans on make available these older SQL Server versions on your Docker image?

**Comment by amitmsft** [comment]
There are no plans to offer container images for SQL Server 2016 or below. SQL Server Container support is offered for SQL Server 2017 on Linux Containers. We are working on SQL Server 2019 on Windows Containers. Please sign up for the Early Adopters Preview if interested. More details [here]( https://cloudblogs.microsoft.com/sqlserver/2019/07/01/sql-server-2019-on-windows-containers-now-in-early-adopters-program/) You can restore older database backups on newer releases. All SQL Server releases are forward compatible w.r.t. backups i.e. they allow restoring a backup from an older release of SQL Server.
