### ISSUE TITLE
Can't connect to SQL Azure instance from inside docker container

### ISSUE THREAD

**Issue by kierenj** [microsoft/mssql-docker#473]
My dockerfile:

```docker
FROM mcr.microsoft.com/mssql-tools:latest
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
CMD [ "/bin/bash" ]
```

(Same when just running on `mcr.microsoft.com/mssql-tools:latest`)

I run:

`sqlcmd -H tcp:my_sql_azure_host.database.windows.net,1433 -U MyUser -P MyPass -d MyDb -q "SELECT 1+1" -N`

And always get:

```
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..
```

(On local Docker - on Win 10 latest build)

The server is running, the firewall is open - I can connect via my local Azure Data Studio. But not from inside docker?

Tried locally (Docker for Windows) and from within a kubernetes cluster, the nodes of which have firewall access to the SQL Server (other apps on the same nodes connect via EF Core fine).

What's more, if I run `sudo tcpdump -XX &` to start a package trace to stdout, when I run `sqlcmd`, I see no output at all... `curl https://whatever` gives lots of output. Is the tool not connecting at all?

**Comment by kierenj** [comment]
Ok... so:

```usage: sqlcmd            [-U login id]          [-P password]
  [-S server or Dsn if -D is provided]
  [-H hostname]          [-E trusted connection]
```

Apparently "`hostname`" is code for "tell the server my workstation name is..."?

https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-2017 says it just fine. Is it worth maybe updating those command line switches - I din't see `-S server` at all since `-H hostname` jumped out.. and I wanted to specify the hostname.

**Comment by amitmsft** [comment]
Did you get it working after using the -S switch?

**Comment by kierenj** [comment]
Yep. My issue is now with the command line documentation / banner :) Worth changing maybe?

**Comment by amitmsft** [comment]
Got it. Please file a PR for this [article](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-2017). I will close this issue for now.

**Comment by kierenj** [comment]
the article looks fine - says workstation name for -H. Not that i found it or thought I needed it since the command line help said it was “server name”. 
Can I file a PR for the tool instead?

**Comment by amitmsft** [comment]
For filing a feedback for the tool, you would need to file here: https://feedback.azure.com/forums/908035-sql-server
