### ISSUE TITLE
Cannot connect from within docker

### ISSUE THREAD

**Issue by mtrtm** [microsoft/mssql-docker#476]
I have two containers, one that is a net core web api and this one (mssql-docker).

I followed all steps to get the container running.  I can connect using Sql Server Management Studio to the docker container (I mapped 1433 -> 11433 and can use `localhost,11433` to connect).

If I inspect docker networks, I see that the sql server container is on 172.18.0.2.  If I use the following connection string in my web api docker container I can connect to the sql server container: `server=172.18.0.2;Database=master;Integrated Security=False;User ID=sa;Password=abc123ABC123;MultipleActiveResultSets=True`

Obviously the IP will change so I cannot hardcode the IP.  When I change it to use the docker name from my docker-compose, it fails.  Connection string that fails: `"server=sqlserverContainer;Database=master;Integrated Security=False;User ID=sa;Password=abc123ABC123;MultipleActiveResultSets=True"`.  Failure message: `A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)".`

This health check must pass for me to promote this into helm and off my system.  I am using AspNetCore.HealthChecks.SqlServer nuget package and my docker-compose looks like this:

```
sqlserverContainer:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=abc123ABC123
    ports:
      - 11433:1433
```

In my web api container, I can do the following:
```
 > ping sqlserverContainer
PING sqlserverContainer (172.18.0.2) 56(84) bytes of data.
64 bytes from dockercompose7749112877033456121_sqlserverContainer_1.dockercompose7749112877033456121_default (172.18.0.2): icmp_seq=1 ttl=64 time=0.115 ms
```

I have added a third container running in the same docker network and using the docker-compose name in the connection string works just fine.

Considering I can connect internally (docker network) using the IP, externally using localhost, and internally to a different third mysql container using the docker compose name, I feel this is a config issue with Sql Server or the library that handles the connection string.

Can anyone shed some light why this wouldn't work?

**Comment by tracker1** [comment]
If you are on windows, from outside the container and the container's network, you will not be able to access directly by address:port, you'll need to --expose PORT or -p EXTPORT:INTPORT as you have outlined above.  If you're using Docker Desktop, the docker engine itself is running inside a virtual machine and you may or likely not have access to the address in question which is a second abstraction away from you.

Your API should be in the same docker-compose, and have links and depends_on set to use your named sql instance.

**Comment by tracker1** [comment]
Alternatively, make sure both are added to a named network, then use the instance name you have set for your sql instance.

**Comment by mtrtm** [comment]
Hi @tracker1 thanks for your response.

As stated above, I can access it from my main machine (outside of Docker using localhost).  I have created an example to demonstrate: https://github.com/mtrtm/CSharp_Aspnetcore_DockerAndSqlServer

**Comment by mtrtm** [comment]
I'd like to close this as I have figured out it is Visual Studio related somehow.  Details: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/issues/230
