### ISSUE TITLE
 Connection failed No open connection to Mssql@DRIVER=FreeTDS;SERVER=127.0.0.1;PORT=1433;

### ISSUE THREAD

**Issue by rogerarce** [microsoft/mssql-docker#477]
Trying to connect to MsSQL server running on docker with workbench

odbcinst -j
> unixODBC 2.3.7
> DRIVERS............: /etc/odbcinst.ini
> SYSTEM DATA SOURCES: /etc/odbc.ini
> FILE DATA SOURCES..: /etc/ODBCDataSources
> USER DATA SOURCES..: /etc/odbc.ini
> SQLULEN Size.......: 8
> SQLLEN Size........: 8
> SQLSETPOSIROW Size.: 8

> [FreeTDS]
> Description=FreeTDS unixODBC Driver
> Driver=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
> Setup=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so
> 
> [ODBC Driver 17 for SQL Server]
> Description=Microsoft ODBC Driver 17 for SQL Server
> Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.3.so.1.1
> UsageCount=1
> 
> [MySQL]
> Driver=/usr/lib/x86_64-linux-gnu/odbc/libmyodbc8w.so
> UsageCount=1

> 8bc7f1743e23        mcr.microsoft.com/mssql/server:2017-latest-ubuntu   "/opt/mssql/bin/sqls…"   5 days ago          Up 26 minutes       0.0.0.0:1433->1433/tcp                     mssql

**Comment by rogerarce** [comment]
probably an issue on odbc driver closing the ticket.

**Comment by tracker1** [comment]
@rogerarce if you're in a supported environment could try the officital driver for linux.

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017
