### ISSUE TITLE
Same image works with Docker run but not with Docker-Compose run or up

### ISSUE THREAD

**Issue by vRITHNER** [microsoft/mssql-docker#482]
Hi,
I have created a new SQL Server Express image for Windows Server 2019

> (mcr.microsoft.com/windows/servercore:ltsc2019)

I test the image on a Windows Server 2019 Vm on Azure in process isolation (Not Hyper-V).
The Sql Server service starts well when I run the image with a Docker Run command.

The same image with a Docker-Compose run or up + same parameters return an error when the service starts:

I struggle since days to find the reason without success. 
Anyone could give me some hints on the reason ?

**The DockerFile:**

    FROM mcr.microsoft.com/windows/servercore:ltsc2019 
    USER ContainerAdministrator

    SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

    # see https://support.microsoft.com/en-us/help/4462262 for latest CU
    ARG DOWNLOAD_URL="https://go.microsoft.com/fwlink/?linkid=829176"

    ENV sa_password="_" `
        sa_password_path="C:\ProgramData\Docker\secrets\sa-password"

    RUN Invoke-WebRequest -Uri $env:DOWNLOAD_URL -OutFile sqlexpress.exe; `
        Start-Process -Wait -FilePath .\sqlexpress.exe -ArgumentList /qs, /x:setup ; `
        .\setup\setup.exe /q /ACTION=Install /INSTANCENAME=SQLEXPRESS /FEATURES=SQLEngine /UPDATEENABLED=0 /SQLSVCACCOUNT='NT AUTHORITY\System' /SQLSYSADMINACCOUNTS='BUILTIN\ADMINISTRATORS' /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS ; `
        Remove-Item -Recurse -Force sqlexpress.exe, setup

    RUN Stop-Service MSSQL`$SQLEXPRESS ; `
        Set-ItemProperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpdynamicports -value '' ; `
        Set-ItemProperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\supersocketnetlib\tcp\ipall' -name tcpport -value 1433 ; `
        Set-ItemProperty -path 'HKLM:\software\microsoft\microsoft sql server\mssql14.SQLEXPRESS\mssqlserver\' -name LoginMode -value 2 ;

    COPY start.ps1 /
    CMD .\start -sa_password $env:sa_password  -Verbose

**The Docker-Compose:**

       mssql:
           container_name: mssql
           image: ${DOCKER_REGISTRY-}mssql
           environment:
              ACCEPT_EULA: Y
              SA_PASSWORD: "yourStrong(!)Password"
          build:
              context: sqlserver
              dockerfile: Dockerfile
          ports:
             - "1433:1433/tcp"
          #tty: true #had to remove it to avoid another null character error
           volumes:
              - .db:C:/Program Files/Microsoft SQL Server/MSSQL14.SQLEXPRESS/MSSQL/DATA

**start.ps1:**

    param(
        [Parameter(Mandatory=$false)]
        [string]$sa_password
    )

    Write-Verbose "Starting SQL Server"
    start-service MSSQL`$SQLEXPRESS

    if($sa_password -eq "_") {
        $secretPath = $env:sa_password_path
        if (Test-Path $secretPath) {
            $sa_password = Get-Content -Raw $secretPath
        }
        else {
            Write-Verbose "WARN: Using default SA password, secret file not found at: $secretPath"
        }
    }

    if($sa_password -ne "_")
    {
        Write-Verbose "Changing SA login credentials..."
        $sqlcmd = "ALTER LOGIN sa with password=" +"'" + $env:sa_password + "'" + ";ALTER LOGIN sa ENABLE;"
        & sqlcmd -Q $sqlcmd
    }

    Write-Verbose "Started SQL Server."

    $lastCheck = (Get-Date).AddSeconds(-2) 
    while ($true) 
    { 
        Get-EventLog -LogName Application -Source "MSSQL*" -After $lastCheck | Select-Object TimeGenerated, EntryType, Message	 
        $lastCheck = Get-Date 
        Start-Sleep -Seconds 2 
    }

**The Error:**
> Attaching to mssql
> mssql              | VERBOSE: Starting SQL Server
> mssql              | start-service : Failed to start service 'SQL Server (SQLEXPRESS)
> mssql              | (MSSQL$SQLEXPRESS)'.
> mssql              | At C:\start.ps1:7 char:1
> mssql              | + start-service MSSQL`$SQLEXPRESS
> mssql              | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> mssql              |     + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceControl
> mssql              |    ler:ServiceController) [Start-Service], ServiceCommandException
> mssql              |     + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands
> mssql              |    .StartServiceCommand
> mssql              |
> mssql exited with code 1

*ps: do anyone knows a standard SQL Image witch works in a Win2019 process isolution.
Any image I pull give the

> "The container operating system does not match the host operating system"

Thanks in advance
-Vince

**Comment by minican** [comment]
According to the official document , for windows server 2019 there is only one version support the process isolation.
Windows Server, version 1903.
Seems you could try the following image : docker pull mcr.microsoft.com/windows/servercore:1903 
For the sac and ltsc difference ,see: Windows Server servicing channels: LTSC and SAC

**Comment by vRITHNER** [comment]
Hi and txs for the tips but this is not working:

docker pull mcr.microsoft.com/windows/servercore:1903
1903: Pulling from windows/servercore
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

only the mcr.microsoft.com/windows/servercore:ltsc2019 is pulled correctly

txs
-v

**Comment by minican** [comment]
Try to install the KB4507453 for your host os , and then check if you could pull the 1903 image .

**Comment by vRITHNER** [comment]
This update has been replaced apparently:

[A screenshot of a cell phone  Description automatically generated]

And the new kb doesn’t want to install…

[A screenshot of a social media post  Description automatically generated]



[A screenshot of a social media post  Description automatically generated]
txs
-v

**Comment by vRITHNER** [comment]
I think I may partly understand what is happening and why the service doesn't start with docker-compose.
I checked the SQL install folders and the DATA folder is empty.
if I copy manually the content of the 'template data' folder inside the DATA folder, the service starts.
Another issue is happening at this moment, I get another error:

>  Attaching to mssql
> mssql              | VERBOSE: Starting SQL Server
> mssql              | VERBOSE: Changing SA login credentials... 'yourStrong(!)Password'
> mssql              | Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login failed for user 'User Manager\ContainerAdministrator'..

I know I have enough memory and the password complexity is correct.
- Anyone can help ?
also
- Why SQL Express setup doesn't copy the standard mdf files in the DATA folder ?


Txs
-Vince

**Comment by vRITHNER** [comment]
also, when I try to repro the image directly from this Github repo, I get this error:

> This SQL Server 2017 Setup operation requires administrator privileges. Access denied. To continue, run Setup with an account that has administrator privileges on this computer.

is this something because of the Docker native version on Windows Server 2019 ?
To allow the installation, I need to add : `USER ContainerAdministrator`

is this ok to do that ?
txs

**Comment by amitmsft** [comment]
SQL Server 2017 is not supported on Windows Containers. We are currently running Private Preview for SQL Server on Windows Containers right now. Please feel free to sign up using instructions available [here](https://cloudblogs.microsoft.com/sqlserver/2018/09/25/sql-server-2019-preview-containers-now-available/)

**Comment by quangnx** [comment]
I ran Docker CLI under Windows Server 2019
To allow the image work installation, I need to accept Eula

But it seems no help provide for EULA

Can someone help?
