### ISSUE TITLE
Can't login in ps with SA user

### ISSUE THREAD

**Issue by bteixeira691** [microsoft/mssql-docker#487]
Im following this, https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-powershell
When I try `sqlcmd -S 127.0.0.1,1433 -U SA -P "Qwerty123"`  give me this "error" -> Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Login failed for user 'SA'..

I already tried new passwords, images and Ports.

**Comment by minican** [comment]
You could try to check if it works fine in other version odbc driver , you could  download the odbc 17 from `[Download ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-2017)`.

**Comment by bteixeira691** [comment]
it works.. thanks
