### ISSUE TITLE
Pull error

### ISSUE THREAD

**Issue by MiaoShuYo** [microsoft/mssql-docker#489]
When I execute this command below ‘docker pull mcr.microsoft.com/mssql/server:2017-latest-ubuntu’, prompt  ‘Get https://mcr.microsoft.com/v2/mssql/server/manifests/2017-latest: net/http: TLS handshake timeout’

**Comment by minican** [comment]
try if it works fine under the vpn . see :[TLS handshake timeout](https://github.com/docker/kitematic/issues/1125)
