### ISSUE TITLE
File has unexpected size (72463 != 72485)

### ISSUE THREAD

**Issue by effolkronium** [microsoft/mssql-docker#491]
```
Step 7/16 : RUN cd /usr/src/gtest/ && cmake . && make && cp *.a /usr/lib
---> Using cache
---> 312a281e5c9d
Step 8/16 : RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
---> Using cache
---> 32b41bd6d8a9
Step 9/16 : RUN curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
---> Using cache
---> fc3ad477ce2d
Step 10/16 : RUN apt-get update
---> Running in dbb164bc08c0
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease [3226 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:6 http://archive.canonical.com/ubuntu bionic InRelease
Get:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages [72.5 kB]
Err:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
File has unexpected size (72463 != 72485). Mirror sync in progress? [IP: 13.80.10.205 443]
Hashes of expected file:

    Filesize:72485 [weak]
    SHA512:c26c6c86803325466bd742789acc9e54a745d045a6b3af1ce26d34e98c9a4904c6873db0cc9b2be7f99385ef6e6237f6e5cd6776fe6c0a1737cae2a67f8566f9
    SHA256:3fe8d8513549a43d26d917287a5a832d0c577ee62ac37b1daae5aade614dff54
    SHA1:e2a5cc1ecb44c77caa98eebac08b9d9f4b1e8215 [weak]
    MD5Sum:30a55059e4b9ef8d02cca7e7acc01cdb [weak]
    Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
    Fetched 255 kB in 2s (125 kB/s)
    Reading package lists...
    E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.gz File has unexpected size (72463 != 72485). Mirror sync in progress? [IP: 13.80.10.205 443]
    Hashes of expected file:
    - Filesize:72485 [weak]
    - SHA512:c26c6c86803325466bd742789acc9e54a745d045a6b3af1ce26d34e98c9a4904c6873db0cc9b2be7f99385ef6e6237f6e5cd6776fe6c0a1737cae2a67f8566f9
    - SHA256:3fe8d8513549a43d26d917287a5a832d0c577ee62ac37b1daae5aade614dff54
    - SHA1:e2a5cc1ecb44c77caa98eebac08b9d9f4b1e8215 [weak]
    - MD5Sum:30a55059e4b9ef8d02cca7e7acc01cdb [weak]
    Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
    E: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by sikeenan** [comment]
I'm seeing this when I manually pull the ODBC driver as well FYI.

`
Err:7 https://packages.microsoft.com/ubuntu/18.04/prod bionic/main amd64 Packages
  File has unexpected size (72463 != 72485). Mirror sync in progress? [IP: 13.80.10.205 443]
  Hashes of expected file:
   - Filesize:72485 [weak]
   - SHA512:c26c6c86803325466bd742789acc9e54a745d045a6b3af1ce26d34e98c9a4904c6873db0cc9b2be7f99385ef6e6237f6e5cd6776fe6c0a1737cae2a67f8566f9
   - SHA256:3fe8d8513549a43d26d917287a5a832d0c577ee62ac37b1daae5aade614dff54
   - SHA1:e2a5cc1ecb44c77caa98eebac08b9d9f4b1e8215 [weak]
   - MD5Sum:30a55059e4b9ef8d02cca7e7acc01cdb [weak]
  Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
Get:8 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [4173 B]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [6222 B]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [755 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [925 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [7216 B]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1276 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [16.8 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4212 B]
Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]
Fetched 17.0 MB in 1s (11.7 MB/s)
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.gz  File has unexpected size (72463 != 72485). Mirror sync in progress? [IP: 13.80.10.205 443]
   Hashes of expected file:
    - Filesize:72485 [weak]
    - SHA512:c26c6c86803325466bd742789acc9e54a745d045a6b3af1ce26d34e98c9a4904c6873db0cc9b2be7f99385ef6e6237f6e5cd6776fe6c0a1737cae2a67f8566f9
    - SHA256:3fe8d8513549a43d26d917287a5a832d0c577ee62ac37b1daae5aade614dff54
    - SHA1:e2a5cc1ecb44c77caa98eebac08b9d9f4b1e8215 [weak]
    - MD5Sum:30a55059e4b9ef8d02cca7e7acc01cdb [weak]
   Release file created at: Tue, 20 Aug 2019 22:43:21 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&       curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list &&       apt-get update &&             ACCEPT_EULA=Y apt-get install msodbcsql17 &&       rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100
simonkeenan@dockhost2:~/development/docker-archangel$ 

`

GEOGRAPHIC REGION: EU, UK & DE fails.

**Comment by sikeenan** [comment]
FYI my pull just worked ok.
