### ISSUE TITLE
SQL Server 2012 Standard edition

### ISSUE THREAD

**Issue by Geekays** [Microsoft/mssql-docker#50]
Is there a way to create a docker image for SQL Server 2012 Standard/Enterprise?
What are the host requirements for running SQL Server on Docker and how may I apply license and what license should I buy?

**Comment by twright-msft** [comment]
Although we haven't tried it yet, you should be able to use the Dockerfile for the Windows container images as a starting point.
https://github.com/Microsoft/mssql-docker/blob/master/windows/mssql-server-windows-developer/dockerfile
You should just need to change the location of where the exe file is coming from.
Please give it a try and let us know what you find.  You can even send us a pull request if you want to add your Dockerfile to the repo here.

Host requirements...
See here: https://msdn.microsoft.com/en-us/library/ms143506(v=sql.110).aspx

Regarding licensing...
SQL Server in Docker containers is licensed effectively the same as virtual machines.  Have a look at the licensing blog for more information:
https://blogs.technet.microsoft.com/uspartner_ts2team/2011/11/30/a-concise-sql-server-2012-licensing-overview/

Keep in mind though that running SQL Server (any version, any edition) on Windows containers is not supported in production right now.  Express and Developer Edition can be used for testing/development purposes.

It would be interesting to know though - why SQL 2012 instead of SQL 2016 or vNext?

**Comment by Geekays** [comment]
Thanks @twright-msft for the update.

So, is there any documentation on the road-map for SQL Server on Docker? And, terms for licensing etc.

**Comment by twright-msft** [comment]
Microsoft's licensing guide will be updated to discuss Docker with the SQL Server vNext release later this year.  As for roadmap... incremental improvements to SQL Server in Docker are tracked here in the open on this GitHub project issues board.  Do you have any specific questions about the future of SQL Server on Docker?

**Comment by Geekays** [comment]
Thanks. I do not have any specific points at this time. Shall follow this space.

**Comment by twright-msft** [comment]
OK great.  Any other particular items to discuss on this issue or can we close it out?  Were you able to get SQL Server 2012 to run in a container?

**Comment by Geekays** [comment]
I am not working on creating SQL Server 2012 docker at this time. Shall await further updates and releases for running SQL Server for production.

**Comment by kumar-technumen** [comment]
@twright-msft Hey Travis, I am having a hard time getting SQL Server 2012 install in a docker container. I started with the .net 3.5 sdk image `mcr.microsoft.com/dotnet/framework/sdk:3.5` and copied SQL Sever 2012 install setup files into it and ran a command line install 

```
RUN .\setup2012\setup.exe /q /ACTION="install" /INSTANCENAME=SQLEXPRESS /FEATURES=SQL /UPDATEENABLED=0 /SQLSVCACCOUNT="mssql" /SQLSYSADMINACCOUNTS="BUILTIN\ADMINISTRATORS" /TCPENABLED=1 /NPENABLED=0 /IACCEPTSQLSERVERLICENSETERMS /ADDCURRENTUSERASSQLADMIN=True
```

Below are the errors I see in the Summary.txt file. Any thoughts to help me succeed with this. Thank you.

```
Detailed results:
  Feature:                       Database Engine Services
  Status:                        Failed: see logs for details
  Reason for failure:            An error occurred for a dependency of the feature causing the setup process for the feature to fail.
  Next Step:                     Use the following information to resolve the error, and then try the setup process again.
  Component name:                SQL Server 2008 Setup Support Files
  Component error code:          1935
  Component log file:            C:\Program Files\Microsoft SQL Server\110\Setup Bootstrap\Log\20200307_133613\SqlSupport_KatmaiRTM_Cpu64_1.log
  Error description:             An error occurred during the installation of assembly 'Microsoft.NetEnterpriseServers.ExceptionMessageBox,fileVersion="10.0.2531.0",version="10.0.0.0000",c
ulture="neutral",publicKeyToken="89845DCD8080CC91",processorArchitecture="MSIL"'. Please refer to Help and Support for more information. HRESULT: 0x80070002.
  Error help link:               http://go.microsoft.com/fwlink?LinkId=20476&ProdName=Microsoft+SQL+Server&EvtSrc=setup.rll&EvtID=50000&ProdVer=11.0.2100.60&EvtType=SqlSupport.msi%40Create
Shortcuts%401935%3a0x80070002

  Feature:                       SQL Server Replication
  Status:                        Failed: see logs for details
  Reason for failure:            An error occurred for a dependency of the feature causing the setup process for the feature to fail.
  Next Step:                     Use the following information to resolve the error, and then try the setup process again.
  Component name:                SQL Server 2008 Setup Support Files
  Component error code:          1935
  Component log file:            C:\Program Files\Microsoft SQL Server\110\Setup Bootstrap\Log\20200307_133613\SqlSupport_KatmaiRTM_Cpu64_1.log
  Error description:             An error occurred during the installation of assembly 'Microsoft.NetEnterpriseServers.ExceptionMessageBox,fileVersion="10.0.2531.0",version="10.0.0.0000",c
ulture="neutral",publicKeyToken="89845DCD8080CC91",processorArchitecture="MSIL"'. Please refer to Help and Support for more information. HRESULT: 0x80070002.
  Error help link:               http://go.microsoft.com/fwlink?LinkId=20476&ProdName=Microsoft+SQL+Server&EvtSrc=setup.rll&EvtID=50000&ProdVer=11.0.2100.60&EvtType=SqlSupport.msi%40Create
Shortcuts%401935%3a0x80070002

  Feature:                       SQL Browser
  Status:                        Failed: see logs for details
  Reason for failure:            An error occurred during the setup process of the feature.
  Next Step:                     Use the following information to resolve the error, uninstall this feature, and then run the setup process again.
  Component name:                SQL Server Browser
  Component error code:          0x84BB0001
  Error description:             SQL Server Browser configuration for feature 'SQL_Browser_Redist_SqlBrowser_Cpu32' was cancelled by user after a previous installation failure. The last at
tempted step: Starting the SQL Server Browser service 'SQLBrowser', and waiting for up to '900' seconds for the process to complete. .
  Error help link:               http://go.microsoft.com/fwlink?LinkId=20476&ProdName=Microsoft+SQL+Server&EvtSrc=setup.rll&EvtID=50000&ProdVer=11.0.2100.60&EvtType=0x4F9BEA51%400xD3BEBD98
%401211%401&EvtType=0x4F9BEA51%400xD3BEBD98%401211%401

  Feature:                       SQL Writer
  Status:                        Passed

  Feature:                       SQL Client Connectivity
  Status:                        Passed

  Feature:                       SQL Client Connectivity SDK
  Status:                        Passed

Rules with failures:

Global rules:

Scenario specific rules:

Rules report file:               C:\Program Files\Microsoft SQL Server\110\Setup Bootstrap\Log\20200307_133613\SystemConfigurationCheck_Report.htm
```
