### ISSUE TITLE
Permissions issue in Docker SQL Server 2017 while restoring certificate

### ISSUE THREAD

**Issue by chaim1221** [microsoft/mssql-docker#505]
I have an unanswered issue on [dba.stackexchange](https://dba.stackexchange.com/questions/249327/permissions-issue-in-docker-sql-server-2017-while-restoring-certificate), and I'm beginning to think it may be a bug, because I have tried everything I can think of to restore the certificate, to no avail (regenerating keys. dropping keys. re-adding keys, etc.).

To reproduce:

1. Start a Docker container instance of SQL Server 2017 Express, with volumes attached at `/var/opt/mssql/backups` and `/var/opt/mssql/certs`.

2. Run the following:
```
USE master
GO
-- GENERATE KEYS --
--
ALTER SERVICE MASTER KEY FORCE REGENERATE;
--
BACKUP SERVICE MASTER KEY TO FILE = '/var/opt/mssql/certs/servicemasterkey.smk'
    ENCRYPTION BY PASSWORD='';
GO
--
CREATE MASTER KEY
    ENCRYPTION BY PASSWORD='';
GO
--
BACKUP MASTER KEY TO FILE = '/var/opt/mssql/certs/masterkey.key'
    ENCRYPTION BY PASSWORD='';
GO
--
CREATE CERTIFICATE sqlserver_backup_cert
    WITH SUBJECT = 'sqlserver_backup_cert'
GO
--
BACKUP CERTIFICATE sqlserver_backup_cert TO FILE = '/var/opt/mssql/certs/sqlserver_backup_cert.cer'
    WITH PRIVATE KEY ( FILE = '/var/opt/mssql/certs/sqlserver_backup_cert.key' ,
    ENCRYPTION BY PASSWORD = '')
GO
```
3. Make some encrypted backups that you can't recover without that key.
4. Destroy your container.
5. Make a completely new container, and attach the same volumes.
6. Run the following:
```
-- RESTORE  KEYS --
-- ------------- --
--
USE master
GO
--
--DROP CERTIFICATE sqlserver_backup_cert
--GO
--
--ALTER SERVICE MASTER KEY FORCE REGENERATE
--GO
--
RESTORE SERVICE MASTER KEY FROM FILE = '/var/opt/mssql/certs/servicemasterkey.smk'
    DECRYPTION BY PASSWORD = ''
    --
    FORCE
    --
GO
--
DROP MASTER KEY
GO
--CREATE MASTER KEY ENCRYPTION BY PASSWORD = ''
RESTORE MASTER KEY FROM FILE = '/var/opt/mssql/certs/masterkey.key'
    DECRYPTION BY PASSWORD = ''
    ENCRYPTION BY PASSWORD  = ''
GO
--
OPEN MASTER KEY DECRYPTION BY PASSWORD = '';
--
CREATE CERTIFICATE sqlserver_backup_cert FROM FILE = '/var/opt/mssql/certs/sqlserver_backup_cert.crt'
  WITH PRIVATE KEY (
    FILE = '/var/opt/mssql/certs/sqlserver_backup_cert.key',
    DECRYPTION BY PASSWORD = ''
  )
GO
--
CLOSE MASTER KEY;
```
7. Receive the error: `[S00019][15208] The certificate, asymmetric key, or private key file is not valid or does not exist; or you do not have permissions for it.`
8. Cry, because your backups will never be restored, and you must now find a new career.

**Comment by chaim1221** [comment]
(This contrived example assumes that destroying your container wipes out the original instance. I realize that's not technically _true_ in most valid scenarios. In reality, these two database servers are on completely separate instances.)

**Comment by srutzky** [comment]
Follow-up based on the DBA.StackExchange Q &amp; A:

### The Issue

The file extension on the **sqlserver\_backup\_cert** file is different between the `BACKUP` and `CREATE` (i.e. restore) statements. It is backed-up as **.cer** but then you are looking for **.crt** in the `CREATE`.

### Suggested Improvement

You could skip the files altogether by using hex bytes (i.e. a `VARBINARY` literal). You would do the following:

**On Prod**

```sql
SELECT CERTENCODED(CERT_ID(N'sqlserver_backup_cert')) AS [CertificateAndPublicKey],
       CERTPRIVATEKEY(CERT_ID(N'PrivateKeyTest'),
                      'new_password_for_extract(A)',
                      'current_password(B)') AS [PrivateKey];
```

**On Test**

```sql
CREATE CERTIFICATE [sqlserver_backup_cert]
    FROM BINARY = {output of CERTENCODED}
    WITH PRIVATE KEY (
        BINARY = {output of CERTPRIVATEKEY},
                 DECRYPTION BY PASSWORD = 'new_password_for_extract(A)',
                 ENCRYPTION BY PASSWORD = 'current_password(B)'
                     );
```

I would _highly_ recommend this approach and stop messing with files in the first place (whenever / wherever possible, of course). That way you can have fully-contained roll-out scripts with no external dependencies.

**Comment by chaim1221** [comment]
I am closing this as not an issue with `mssql-docker`, but feel free to follow the linked dba.stackexchange question for any updates.
