### ISSUE TITLE
Error with "Invoke-Sqlcmd"

### ISSUE THREAD

**Issue by micking** [Microsoft/mssql-docker#51]
Starting the mssql-server-windows container gives the following error in the logs:
```
VERBOSE: Starting SQL Server
VERBOSE: Changing SA login credentials
Invoke-Sqlcmd : The 'Invoke-Sqlcmd' command was found in the module 'SQLPS', but the module could not be loaded. For more information, run 'Import-Module SQLPS'.
At C:\start.ps1:31 char:5
+     Invoke-Sqlcmd -Query $sqlcmd
+     ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Invoke-Sqlcmd:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

VERBOSE: Started SQL Server.
```

by that the sa password is unchnged and the sql server is unusable

**Comment by perrysk-msft** [comment]
Thanks @micking! 

We are aware of the issue and we are working on a fix.

**Comment by perrysk-msft** [comment]
[@micking]

We have replaced Invoke-Sqlcmd with sqlcmd.exe in the start.ps1 script to bypass the error and also uploaded the latest images in Docker hub. You should be able to pull the latest image from DockerHub and successfully run and connect to a SQL Server CTP1.4 container. 

Please let us know if you run into any issues.
