### ISSUE TITLE
How can I integrate SQL Server AD authentication on Windows docker container

### ISSUE THREAD

**Issue by pbunluesin** [microsoft/mssql-docker#510]
Hi,

I would like to integrate AD Account to SQL Server Windows docker container

Would you please suggest and guide me step by step.

**Comment by amitmsft** [comment]
SQL Server on Windows containers are still in preview and there is no support for AD for SQL Server in Windows containers. Please sign up for the preview at https://aka.ms/sqleap if you want to use the latest containers.
