### ISSUE TITLE
Is SQL Server 2019 on Linux GA?

### ISSUE THREAD

**Issue by Cherishty** [microsoft/mssql-docker#518]
Hi team,

I'd like to use **sqlserver 2019 Linux container** (as client) to connect other sqlserver. While I wonder whether the has a `GA `version on Linux? 

Seen from dockerhub and MSDoc, I can only find the latest version of 2019 is `mcr.microsoft.com/mssql/server:2019-CTP3.2-ubuntu`, while it is just a Community Preview version? 
Do you think this image is **reliable** enough to serve as the **client**, in industry use?

Much of thanks!

**Comment by amitmsft** [comment]
SQL Server 2019 will be GA in CY2019. Our GA announcement will be made on [this blog](https://cloudblogs.microsoft.com/sqlserver/).
