### ISSUE TITLE
linux - init db

### ISSUE THREAD

**Issue by lkurzyniec** [microsoft/mssql-docker#519]
It would be great to have a possibility to initialize fresh instance with some data:
* db name (_Initial Catalog_)
* scripts to run on above db (create schema, provide data)

**Comment by nocentino** [comment]
If I understand your request correctly, this example should do what you're asking. This is part of a larger example using replication, but the initialization of the databases will use the same method.

[https://github.com/microsoft/sql-server-samples/tree/master/samples/containers/replication/db1]

**Comment by lkurzyniec** [comment]
Yes, it looks like what I need, what I expect. I will try it this week and let you know about the results. Thanks!

**Comment by lkurzyniec** [comment]
After couple of hours, it works as intended - it is possible to start the container with initialized db. 
Honestly, it's quite hard to achieve. It's much simpler in case of either `mysql` or `mongodb`. You should make it more devfriendly ;)

One more thing - you should add 'How to' instructions onto [docker hub](https://hub.docker.com/_/microsoft-mssql-server), because people are asking about it (e.g. your issue [here](https://github.com/Microsoft/mssql-docker/issues/2)).

Here is my working example: https://github.com/lkurzyniec/netcore-boilerplate
