### ISSUE TITLE
SQL Server Windows docker for production

### ISSUE THREAD

**Issue by Joehannus** [microsoft/mssql-docker#520]
Not every company allows usage of Linux. Therefore an official Windows based SQL server docker image is necessary, that can be used in a production environment, not based on Express or Developer editions.

**Comment by amitmsft** [comment]
Please sign up for the SQL Server on Windows Container EAP [here](http://aka.ms/sqleap).

**Comment by Joehannus** [comment]
> Please sign up for the SQL Server on Windows Container EAP [here](http://aka.ms/sqleap).

I did that. I also got a welcome e-mail. But haven't received any other mails yet. What I wonder though, now that SQL Server 2019 is generally available, is when the SQL Server 2019 Windows Docker containers will be generally available as well?
