### ISSUE TITLE
SQL Server 2017-CU17-ubuntu tag missing

### ISSUE THREAD

**Issue by dbamaster** [microsoft/mssql-docker#529]
Hello there!

I recently noticed the 2017-**CU**17-ubuntu tag is missing when updating my CI/CD pipeline in Jenkins. I had to manually update the pipeline to use 2017-**cu**17-ubuntu instead. 

Please note the difference between **CU17** and **cu17**, the lowercase is a problem because Docker is key sensitive.

**Docker pull example:**
![Screen Shot 2019-11-11 at 21 14 23](https://user-images.githubusercontent.com/38668645/68641626-aa93ba80-04c8-11ea-9cb1-9ad63755cb4b.png)

**Listing images from MCR:**
![Screen Shot 2019-11-11 at 21 16 41](https://user-images.githubusercontent.com/38668645/68641656-c4350200-04c8-11ea-8920-d56b4025837a.png)

Thanks!

**Comment by vin-yu** [comment]
We have resolved this, you can now pull with "CU17"
