### ISSUE TITLE
SQL Server 2019 Developer/Express Windows Container

### ISSUE THREAD

**Issue by joeydaowang** [microsoft/mssql-docker#533]
Hi,

Will we have SQL Server 2019 Developer/Express Windows container, and when if it will be provided? 

Cheers.

**Comment by kkbruce** [comment]
Have any plan provider MS SQL 2019 for Windows Container?

**Comment by kkbruce** [comment]
Hi @vin-yu 
I look at this blog: https://cloudblogs.microsoft.com/sqlserver/2019/07/01/sql-server-2019-on-windows-containers-now-in-early-adopters-program/ , Have any release plan?

**Comment by amitmsft** [comment]
Please stay tuned to our blog. We will announce updates to our release plan there when we are ready. If there is a requirement where you would like to use SQL Server on Windows containers, please join our Early Adopter Program so that we can share updates under NDA.
