### ISSUE TITLE
mssql docker license

### ISSUE THREAD

**Issue by lesca** [Microsoft/mssql-docker#54]
Hello team,

I'd like to know is it free to use the mssql docker on linux? As I know MSSQL is very expensive on windows. 

Thank you.

**Comment by twright-msft** [comment]
Regardless of where you run it - VM, Docker, physical, cloud, on prem - the licensing model is the same and it depends on which edition of SQL Server you are using.

The Express and Developer Editions are free.  Standard and Enterprise have a cost.

Express Edition has most core features, especially those that are needed by an application, but it is limited in terms of the number of cores that it can use.  Express Edition can be used in production.

Developer Edition has ALL features and has no resource limits.  It is limited by the license agreement to only be used in dev/test and not in production.

More information here:
https://www.microsoft.com/en-us/sql-server/sql-server-2016-editions

**Comment by LuisBosquez** [comment]
Just added this information to the FAQ in the README file https://github.com/Microsoft/mssql-docker/commit/2482e85aa1d56c5845c01c58805414d37273ad15
