### ISSUE TITLE
SQL Server 2017-CU18-ubuntu and 2017-CU18 tags missing

### ISSUE THREAD

**Issue by dbamaster** [microsoft/mssql-docker#543]
Hello there!

I recently noticed the 2017-CU18-ubuntu tag is missing when updating my CI/CD pipeline in Jenkins. I had to manually update the pipeline to use 2017-CU18-ubuntu-16.04 instead.

Please note the difference between CU17 and CU18, the version of Ubuntu was added at the end of the tag:

Docker pull example:

```bash
[dba mastery] $  docker pull mcr.microsoft.com/mssql/server:2017-CU18-ubuntu
Error response from daemon: manifest for mcr.microsoft.com/mssql/server:2017-CU18-ubuntu not found: manifest unknown: manifest unknown
```

Listing images from MCR:
```bash
[dba mastery] $  curl -sL https://mcr.microsoft.com/v2/mssql/server/tags/list/ | grep "2017-CU17"
    "2017-CU17",
    "2017-CU17-ubuntu",

[dba mastery] $  curl -sL https://mcr.microsoft.com/v2/mssql/server/tags/list/ | grep "2017-CU18"
    "2017-CU18-ubuntu-16.04",
```

Thanks!

**Comment by vin-yu** [comment]
we have decided to add update the tag to be fully explicit which lists out the SQL Server Version, CU, OS distro and OS distro version. This is because we plan to support more distro versions soon.   

<SQL Server Version>-CU<CU Number>-<OS distro>-<OS distro version>

you can learn more about it here:
https://hub.docker.com/_/microsoft-mssql-server

**Comment by dbamaster** [comment]
> we have decided to add update the tag to be fully explicit which lists out the SQL Server Version, CU, OS distro and OS distro version. This is because we plan to support more distro versions soon.
> 
> `<SQL Server Version>-CU<CU Number>-<OS distro>-<OS distro version>`
> 
> you can learn more about it here:
> https://hub.docker.com/_/microsoft-mssql-server

The new tag makes sense, I was kind of guessing that was the path you guys were taken but wanted to confirm anyway :)

I will update my pipelines accordingly.
Thanks Vin!!
