### ISSUE TITLE
the image runs as mssql user

### ISSUE THREAD

**Issue by UdayModi** [microsoft/mssql-docker#549]
Shouldn't it run as root?

**Comment by vin-yu** [comment]
wWe have decided to run this as a non-root user by default as it is safer. You can always run this as root with the instructions listed here: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-2017#nonrootuser 

learn more about non root containers here:
https://techcommunity.microsoft.com/t5/sql-server/non-root-sql-server-2019-containers/ba-p/859644
