### ISSUE TITLE
mssql-docker pricing model for production use

### ISSUE THREAD

**Issue by rupeshtech** [microsoft/mssql-docker#556]
We want to use mssql-docker for our Database in container in production.
Currently we have Dbs using Azure Sql (as PAAS). 
Where can I find the detailed licensing (and pricing) documentation about mssql-docker use in production.

**Comment by amitmsft** [comment]
SQL Server container pricing is based on SQL Server core based licensing model. Please see the [SQL Server Licensing Guide](https://aka.ms/sql2019licenseguide) for more details about how container licensing works.
