### ISSUE TITLE
KB4532691 breaks building a MSSQL image

### ISSUE THREAD

**Issue by MuhKuh7** [microsoft/mssql-docker#569]
The image with dockerfile `windows/mssql-server-windows/dockerfile` (when based on 1809) does not build anymore on a Windows Server 2019 1809 when KB4532691 is installed.

It seems the `Start-Process -Wait -FilePath .\SQL.exe -ArgumentList /qs, /x:setup` is not executed correctly.

Uninstalling KB4532691 fixes the issue.

**Comment by westzipfel** [comment]
It is even more:
- Installation of most msi fails with "Error 1719. The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact y our support personnel for assistance.". At least with custom actions within msi.
- Starting of executables fails with error -1073741502 (0xC0000142 - "DLL Initialization Failed")
Some information is available from MS:
[https://support.microsoft.com/en-us/help/4532691/windows-10-update-kb4532691](url)
[https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im](url)

**Comment by robertoandrade** [comment]
Having the same issue running builds either in Appveyor or Azure DevOps... any .exe or .msi executed with `Start-Process -Wait` fail immediately generating no logs. Any workarounds available since I have no control over the host environment in either platform?

**Comment by westzipfel** [comment]
Using an actualized base image, labeled by *20200211*, e.g.  mcr.microsoft.com/dotnet/framework/runtime:4.8-20200211-windowsservercore-ltsc2019
fixed my problems.

**Comment by westzipfel** [comment]
Note that the base image must match the host machine (inconvenient solution, to put it mildly:-(). Check https://hub.docker.com/_/microsoft-dotnet-framework-runtime for latest details - it seems that some "fixed" base images are now marked as "latest" i.e. no need to address particular version explilictly.
