### ISSUE TITLE
Is there an Express or Developers edition for linux containers?

### ISSUE THREAD

**Issue by benze** [Microsoft/mssql-docker#57]
Is there a docker container for Mssql Express or Developers edition in a linux container?

I want to run MSSQL as a linux container, but I am always being warned of my license expiry.  In a dev environment, I do not know how to continue.  I do not want to use it in prod, but I do not know where to find a developer's edition in a linux container format.

Does such a container exist?

**Comment by LuisBosquez** [comment]
SQL Server in Linux is currently in preview mode, which is why you get the expiry message. There will be a Developer Edition container, but this is going to be released on GA (mid 2017, I believe). 

The message should only be a warning and shouldn't block you from doing anything. Are you experiencing any issues that block you from developing?

**Comment by benze** [comment]
No - no issues so far.  I just had a concern about running a container on my dev system that would expire in 180days in which time I'll be stuck scrambling to figure out how to get licenses for it, etc.  It especially isn't a system that I can recommend for a DevOps track, etc if it expires in 6 months.

However, if there is a Dev container that will be released mid 2017, that will resolve the issues.

Thanks,

Eric

**Comment by twright-msft** [comment]
I have a theory...
This is the error in the log: lsof: command not found
The assumption with the mssql-server-linux container right now is that the sqlservr process is running as root.
Is it possible that you are trying to run this container in something like OpenShift that doesnt allow running containers as root by default?

**Comment by kspearrin** [comment]
@LuisBosquez Will there be an Express Edition for Linux at GA?

**Comment by twright-msft** [comment]
Yes, in fact there is an Express Edition starting with RC1.  You can choose the edition you want by passing in the -e MSSQL_PID environment variable at `docker run`.
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
