### ISSUE TITLE
Ubuntu 19.10 Updates Crashes 

### ISSUE THREAD

**Issue by Bignatus** [microsoft/mssql-docker#577]
This is what I get ANYTIME I try to update my system **(Ubuntu 19.10)**. Please I need a solution from the community...

OUTPUT:

natus@etApi-CCXC:~$ sudo apt update
Get:1 http://us.archive.ubuntu.com/ubuntu eoan InRelease [2,821 B]             
Err:1 http://us.archive.ubuntu.com/ubuntu eoan InRelease                       
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:2 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease [2,829 B]     
Err:2 http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease               
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:3 http://ppa.launchpad.net/gezakovacs/ppa/ubuntu eoan InRelease [2,832 B]  
Err:3 http://ppa.launchpad.net/gezakovacs/ppa/ubuntu eoan InRelease            
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:4 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease [2,831 B]   
Err:4 http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease             
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:5 http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu eoan InRelease [2,841 B]
Err:5 http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu eoan InRelease   
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Get:7 http://us.archive.ubuntu.com/ubuntu eoan-security InRelease [2,830 B]    
Err:7 http://us.archive.ubuntu.com/ubuntu eoan-security InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:8 https://brave-browser-apt-release.s3.brave.com stable InRelease
Get:9 http://us.archive.ubuntu.com/ubuntu eoan-proposed InRelease [2,830 B]
Err:9 http://us.archive.ubuntu.com/ubuntu eoan-proposed InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:6 https://packagecloud.io/AtomEditor/atom/any any InRelease                
Reading package lists... Done
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'http://us.archive.ubuntu.com/ubuntu eoan InRelease' is not signed.
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/eoan/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'http://us.archive.ubuntu.com/ubuntu eoan-updates InRelease' is not signed.
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/eoan-updates/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'http://ppa.launchpad.net/gezakovacs/ppa/ubuntu eoan InRelease' is not signed.
E: Failed to fetch http://ppa.launchpad.net/gezakovacs/ppa/ubuntu/dists/eoan/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'http://us.archive.ubuntu.com/ubuntu eoan-backports InRelease' is not signed.
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/eoan-backports/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu eoan InRelease' is not signed.
E: Failed to fetch http://ppa.launchpad.net/linuxgndu/sqlitebrowser/ubuntu/dists/eoan/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/eoan-security/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://us.archive.ubuntu.com/ubuntu eoan-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/eoan-proposed/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'http://us.archive.ubuntu.com/ubuntu eoan-proposed InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by dbamaster** [comment]
Hello there,

I don't think Ubuntu 19.0 is supported for SQL Server on Linux. According to Microsoft docs, only 16.04 is supported. You can see the details [here](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15#prerequisites).

Ubuntu 18.04 is supported after making these [modifications](https://docs.microsoft.com/en-us/archive/blogs/sql_server_team/installing-sql-server-2017-for-linux-on-ubuntu-18-04-lts).

Cheers.

**Comment by amitmsft** [comment]
Closing this issue as SQL Server is not supported on Ubuntu 19.0.

**Comment by Bignatus** [comment]
Alright thanks very much for the insights
