### ISSUE TITLE
Docker custom image build fails with full text search 

### ISSUE THREAD

**Issue by xcellenceit** [microsoft/mssql-docker#578]
Hi, 

While building a custom docker image with support for full text search i used this dockerfile...

https://github.com/Microsoft/mssql-docker/blob/1efc4cf9b78fa5fccea682f26067189660af85c8/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile

This fails with the error message:

> <html>
> <head><title>404 Not Found</title></head>
> <body bgcolor="white">
> <center><h1>404 Not Found</h1></center>
> <hr><center>nginx/1.10.3 (Ubuntu)</center>
> </body>
> </html>
> E: Malformed line 1 in source list /etc/apt/sources.list.d/mssql-server.list (type)
> E: The list of sources could not be read.
> The command '/bin/sh -c export DEBIAN_FRONTEND=noninteractive &&     apt-get update &&     apt-get install -y curl  &&     curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&     curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server.list | tee /etc/apt/sources.list.d/mssql-server.list &&     apt-get update' returned a non-zero code: 100
> 

![image](https://user-images.githubusercontent.com/661269/75872940-12ce2980-5e35-11ea-9754-de980d17c9fb.png)

**Comment by dbamaster** [comment]
Hello there,

Would you mind to share your Dockerfile? The Dockerfile example you are pointing out is very out-dated.

To be specific the line 6 of that Docker file is no longer valid:
```docker
FROM microsoft/mssql-server-linux

**Comment by xcellenceit** [comment]
Please use this dockerfile, this works fine for us.

https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile

**Comment by dbamaster** [comment]
> Please use this dockerfile, this works fine for us.
> 
> https://github.com/Microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile

Excellent, thanks for sharing!

**Comment by xcellenceit** [comment]
You're welcome. Sharing always helps us.
