### ISSUE TITLE
Error with mssql-customize example

### ISSUE THREAD

**Issue by stephlocke** [microsoft/mssql-docker#591]
After  a git clone and build on Windows I get:

```
T:\mssql-docker\linux\preview\examples\mssql-customize>docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=StrongPassw0rd' -p 1434:1433 --name sql1 mssql-custom
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

I think perhaps this is a WORKDIR issue but not sure.

---
Docker setup
Docker For Windows: 2.2.0.5
Engine: 19.03.8

**Comment by dbamaster** [comment]
> standard_init_linux.go:211: exec user process caused "no such file or directory"

Hello there!

I think this is related to a problem with Git on Windows, you can take a look [here](https://github.com/docker/labs/issues/215#issuecomment-304596295) 😁

Cheers,

**Comment by vin-yu** [comment]
I got this working on my Windows machine by changing the End of Line Sequence from `CRLF` to `LF`
