### ISSUE TITLE
Unable to mount volume

### ISSUE THREAD

**Issue by Magnavolt** [microsoft/mssql-docker#600]
Hello!
After updating to Docker version 19.03.8, build afacb8b i'am not able to mount volume.
This is the command i'am running.
```
docker run  
    -p 1433:1433 ^
    --name sqlserver2019 ^
    -e "ACCEPT_EULA=Y" ^
    -e "SA_PASSWORD=password123!" ^
    -e "MSSQL_COLLATION=Finnish_Swedish_CI_AS" ^
    -v c:/db2:/var/opt/mssql/data ^
    -d mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
```
and the log show this message
```

SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2020-05-12 12:28:25.27 Server Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2020-05-12 12:28:25.35 Server ERROR: Setup FAILED copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf': 31(A device attached to the system is not functioning.)
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x8007001f)
```

If i remove the -v line it works fine. I think this is a Docker issue because it worked before i updated docker.

**Comment by TFSM** [comment]
Can confirm this issue. Reverting to the previous version of Docker Desktop for Windows (Community, v2.2.0.5) fixed this issue. I read through the change log on the Docker website, but I'm not sure what caused the breaking change.

**Comment by luisgandrade** [comment]
The same is happening here after the most recent update of Docker.

**Comment by uncleserge** [comment]
Have the same problem after updating Docker Desktop to the recent version (2.3.0.2).

**Comment by KVerwold** [comment]
Same problem here with version 2.3.0.2 . Even tried to reset Docker to factory defaults, which didn't helped.

**Comment by neisep** [comment]
Same problem for me, i had to go back to 2.2.0.5.

**Comment by Magnavolt** [comment]
As a workaround i copy my file in to the container.
```
docker cp C:\db2\db2-last.bak sqlserver2019:/var/opt/mssql/data/
```

**Comment by itymofeev** [comment]
Confirm, I'm experiencing the same issue after updating to Docker version 2.3.0.2. Any update guys?

**Comment by stgonzales** [comment]
Same issue after update docker

**Comment by MisterY** [comment]
Please, there's no need to say "me too" and notify everyone subscribed. That part is obvious.
It's simple: 

1. Add 👍 to the original post,
2. Click Subscribe to get notified about the updates,
3. Read previous messages for the workaround,
4. Add comments only if you can contribute some new and useful information,
5. Chill

**Comment by CoskunSunali** [comment]
> I'm not sure what caused the breaking change

@TFSM Probably something to do with the following change.

> Docker Desktop now allows sharing individual folders, rather than whole drives, giving more control to users over what is being shared.

**Comment by c0dingarchit3ct** [comment]
Same issue!

**Comment by stephen-turner** [comment]
Docker response: This is a regression in Docker. We will fix it. This ticket can be duped against https://github.com/docker/for-win/issues/6646.

**Comment by aspnet1** [comment]
👎
