### ISSUE TITLE
Connection between Web and SQL

### ISSUE THREAD

**Issue by Llongshot** [microsoft/mssql-docker#611]
Hi, I'm having an issue regarding service DNS/IP. I have 3 docker services, 1 is DB with the name, imagine, "database", other 2 are Rest and Webservice. All of them are in the Ingress default network, added automatically when service is created and in an normal custom overlay network. In the database connection strings of the Rest and Webservice containers I put the DB container service name "database", but the containers can't reach the DB by the service name or even by it's IP address. If I put the IP address of the container DB it works. Setup is Docker EE version 18.09.5 in Swarm Mode for Windows. Anyone can't point me out in a troubleshooting? Regards.

**Comment by gadeleonp** [comment]
How did you make the connection string?

**Comment by Llongshot** [comment]
At many days Lost, the problem was a Windows update. After the rollback the issue was solves
