### ISSUE TITLE
I'm getting problems in installing SQL server in Parrot OS

### ISSUE THREAD

**Issue by charity1475** [microsoft/mssql-docker#626]
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2749.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

here is my odbcinst.in

ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.5.so.2.1
Server = tcp:127.0.0.1,1433

**Comment by vin-yu** [comment]
Are you installing on SQL Server in a Parrot OS or using a SQL Server container on Parrot OS? 

ParrotOS is not a supported OS at this time.

**Comment by charity1475** [comment]
Ok I got you , can please tell me the best option out there?🙏

**Comment by wkrea** [comment]
woww it's so bad news :disappointed:

**Comment by charity1475** [comment]
Issue resolved.
