### ISSUE TITLE
mssql-tools in debian installation gets https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.gz  Writing more data than expected (103561 > 103377)

### ISSUE THREAD

**Issue by Alonreznik** [microsoft/mssql-docker#627]
Hi there.
In the last hours, we get a problem on installation the debian mssql-tools:

```
https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.gz  Writing more data than expected (103561 > 103377)
```

It seems the gpg file and the Release files aren't match:
![image](https://user-images.githubusercontent.com/8024926/85546496-9fd80100-b625-11ea-8e88-c004301b4648.png)

Please fix it asap because it makes our deployment (and I think more others) to fail :)

Thanks
Alon

**Comment by jlongo-daitan** [comment]
Same happening here, please fix it

**Comment by jlongo-daitan** [comment]
Do you have an estimate to fix this?

**Comment by Alonreznik** [comment]
Seems to be fixed now via other channels.
I'm closing the issue.
However, please guide to where we should open an issue in cases this is happening again.

Alon

**Comment by jlongo-daitan** [comment]
@Alonreznik it's working now. Thx
