### ISSUE TITLE
docker pull microsoft/mssql-server-windows-express doesn't work

### ISSUE THREAD

**Issue by chek75** [Microsoft/mssql-docker#65]
<img width="585" alt="screen shot 2017-04-14 at 4 36 44 am" src="https://cloud.githubusercontent.com/assets/27491946/25042334/1dae18aa-20cc-11e7-8b90-c481e459d381.png">

**Comment by twright-msft** [comment]
You can't run a Windows container on Docker for Mac.  Docker for Mac has a VM running locally on your mac that is Linux based where the containers are run.  You'll need to use the mssql-server-linux image.

$ docker pull microsoft/mssql-server-linux
