### ISSUE TITLE
Unable to start the sqlserver container in docker

### ISSUE THREAD

**Issue by fengyinyong** [microsoft/mssql-docker#653]
I ran the command  "docker pull mcr.microsoft.com/mssql/server:2017-latest" and got the image。but when i make a container on it,  the container does not work，it's state is exit。 Can anyone give me available solutions??

the command: docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Sql@123456"  -p 1433:1433 --name sqlserver -d mcr.microsoft.com/mssql/server:2017-latest
![Image_20201027214049](https://user-images.githubusercontent.com/68414905/97310194-e96b7d80-189d-11eb-91f8-4a48535edc87.png)

and the Hyper-v‘s memery is more than 2G。

![image](https://user-images.githubusercontent.com/68414905/97310386-20419380-189e-11eb-9bbc-961ef18f795f.png)

**Comment by nocentino** [comment]
Try updating the environment variable from SA_PASSWORD to MSSQL_SA_PASSWORD

It changed along the way, here's the 2017 doc for that. 
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-linux-2017#use-with-docker

**Comment by fengyinyong** [comment]
@nocentino  it still does not work.
 here is my command:
docker run -e ACCEPT_EULA=Y -e MSSQL_PID="Developer" -e MSSQL_SA_PASSWORD="<YourStrong!Passw0rd>" -e MSSQL_TCP_PORT=1234 -p 1234:1234 -d mcr.microsoft.com/mssql/server:2017-latest

![3](https://user-images.githubusercontent.com/68414905/97384558-e35fb600-190a-11eb-82d0-ce4b31c8a8c5.png)

**Comment by nocentino** [comment]
Can you post the logs using docker logs $CONTAINER_ID?

**Comment by fengyinyong** [comment]
I’ve get this problem solved : when I run a container on the image， I need to set it's memory more than 2000 MB.

![image](https://user-images.githubusercontent.com/68414905/97852981-72693580-1d32-11eb-9929-e0e846d88a78.png)
Thanks for your help.
