### ISSUE TITLE
Connect SQL Server Management Studio (v17) to the Linux docker container running on Virtual Box.

### ISSUE THREAD

**Issue by srueff** [Microsoft/mssql-docker#67]
I got the Linux docker image working w/o any issues, but the tools were not on the image I pulled today.  After some trial and error, I was able to download them separately and everything works great inside the container itself.  However, I'm unable to connect SQL Server Management Studio to the Linux container running on Virtual Box.

Any suggestions?

**Comment by twright-msft** [comment]
Did you use the docker run -p parameter to map the ports from the host to the container?

**Comment by srueff** [comment]
Yes!  It turns out that the issue was with my local "McAfee Host Intrusion Prevention Service". Once I disabled it, SQL Server Management Studio worked fine.
