### ISSUE TITLE
impossible to connect to SQL server container through SSMS

### ISSUE THREAD

**Issue by GregSino** [microsoft/mssql-docker#675]
Hi guys,

Strange problem with MS SQL server 2019 installed in a container.

Here is my install command:

`docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=STRONGpassword11*" -p 1433:1433 --name NAME -h OTHERNAME -d mcr.microsoft.com/mssql/server:2019-latest`

Got the confirmation message.

Then, I start the container:
`docker start NAMEORID`

no problem. I can also see it's running in the Docker desktop application

the "docker ps" command give me an answer too:
`8f73c5b0500a   mcr.microsoft.com/mssql/server:2019-latest   "/opt/mssql/bin/perm…"   About an hour ago   Up About an hour   0.0.0.0:1433->1433/tcp   apitest`

Then I try to start a bash:
docker exec -it apitest "bash"
I can go

So I try to loggin:
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "<YourNewStrong@Passw0rd>"
I've the "1>" answer so everything is ok

After that, I try to create a database directly in with bash:
```
1> CREATE DATABASE dbtest
2> SELECT Name from sys.Databases
3> GO
```
It works.

To get the ip of the container:
`docker inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" 8f73c5b0500a`

so finally, I try to connect with SSMS with:
`172.17.0.2,1433`

doesn't work.

I tried to specify the name of the container:
`172.17.0.2\apitest,1433`

doesn't work too....and same error: 258

What can I do?

**Comment by GregSino** [comment]
I've checked the logs and find one error:

`2021-02-03 05:15:22.74 spid9s      Unable to retrieve registry value 'NodeRole' from Windows registry key 'Software\Microsoft\Microsoft SQL Server\MSSQL\Polybase\Configuration': (null).`

Don't know if it's important...

**Comment by GregSino** [comment]
tried to do this:
`docker exec -it <container id or name> hostname -i`
Have this answer:
172.17.0.2

But, the ping doesn't answer......

**Comment by GregSino** [comment]
Feel a little bit alone...

I tried to inspect bridge:
`docker network inspect bridge`

result:
```
"Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1
...
"IPv4Address": "172.17.0.2/16",
```"

but if I try to connect:
`sqlcmd -S 172.17.0.1,1433 -U SA -P "PASSWORD"`

I have an error 53, don't find it....

**Comment by Crespalvaro** [comment]
Hi @GregSino 

You are not the only one struggling with this. Currently we are trying to deploy this image in openshift with the exact same result. In our case we have the concern that it could be due to memory resources assigned to the image. This image is suppose to work with a minimun of 2gb but we managed to run it with just 1.3 gb. I dont know if this could cause any error but I dont feel like the issue is there since I can access the sql sever through sqlcmd.

Did you find a solution already?

**Comment by GregSino** [comment]
Yes, I finally find a solution: 
1- stop the local sql server (it seems it was in conflict with the docker container)
2- start the container, and it's working for me
3- restart the local sql server

Now, I've access to the both sql server :)

**Comment by TreyZh** [comment]
The server ip is your pc ip+port.
The port is that when you exec 'docker run ... -p port:xxxx'.
Ip is not the result you got from 'docker exec -it <container id or name> hostname -i'
