### ISSUE TITLE
Problemas com M1 vs SQLServer

### ISSUE THREAD

**Issue by pauloPH3A** [microsoft/mssql-docker#677]
A boa noticia é que o PostgreSQL roda normalmente no M1 da Apple. Caso a Microsoft não se manifeste com um versão para o Arm64, é só migrar para o PostGreSql, e está funcionando normalmente no Docker.

**Comment by amvin87** [comment]
Azure SQL Edge runs with arm modules please try Azure SQL Edge: https://azure.microsoft.com/en-in/products/azure-sql/edge/

SQL Server is not supported for arm architecture.
