### ISSUE TITLE
Unable to connect to remote linked server with latest update of "mcr.microsoft.com/mssql/server:latest"

### ISSUE THREAD

**Issue by alaincao** [microsoft/mssql-docker#682]
Heylow,

we have a database in a Linux container that connects to another (Windows) server using "Linked Server".
When we run the query
```sql
select * from [IP_ADDRESS,PORT].CRM.dbo."Address"
```
using the image at version `mcr.microsoft.com/mssql/server   latest   62c72d863950` from 4 days ago (that'd be around 2021-04-03), it fails with the error:
```
OLE DB provider "MSOLEDBSQL" for linked server "IP_ADDRESS,PORT" returned message "Client unable to establish connection".
Msg 10054, Level 16, State 1, Line 0
TCP Provider: An existing connection was forcibly closed by the remote host.
```

OTOH, when I revert back to the previous image `a8948ed97d80` from 2 months ago, that query succeeds without problem.

Has something changed in the latest image?

Thanks

**Comment by alaincao** [comment]
The remote host is a "forgotten" Server 2014 really not up to date. So I am pretty sure this is an issue with SSL or something, we are in the "3X carbon copy form filling administrative paperwork" way of "windows updating" it, but I'd rather have input of knowledgable people in the mean-time ;-)

**Comment by sstidl** [comment]
We had a similar problem: Win 2012R2 Server could not connect anymore with the default ODBC Driver. We had to upgrade to ODBC Driver 17 for SQL Server

**Comment by amvin87** [comment]
yes, when the tag 2019-latest is used it basically downloads the latest SQL 2019 CU with the latest OS image,.

**Comment by alaincao** [comment]
I can confirm that when using the image `mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-18.04`, the issue goes away, thanks!  
I suppose I can close this issue...  

I am still in the process of updating the remote server and will test with `latest` again once it's done (spent a whole evening on this and updates keeps popping up... damn, I don't miss the old WindowsUpdate! ).   
I'll post the results here.

**Comment by alaincao** [comment]
FYI, the remote host (Windows 2012 / SQL2014) has finally been "windows updated", and the `latest` image still cannot connect.  
I guess we're stuck with the `18.04` image until that server is replaced...
