### ISSUE TITLE
Please provide ARM version, so users can run it on MacOs M1 machies

### ISSUE THREAD

**Issue by hrstoyanov** [microsoft/mssql-docker#683]
We need this like ... yestrday!

**Comment by amvin87** [comment]
SQL Server currently is not supported for ARM nor in the roadmaps for now, but you can try running SQL Edge : https://azure.microsoft.com/en-in/resources/videos/sql-database-edge-on-arm-device/  which is a lighter version and supported on ARM and edge devices.

**Comment by hrstoyanov** [comment]
Does SQL Edge support the full MS TDS wire protocol ?

**Comment by SQLSourabh** [comment]
SQL Edge uses the same SQL Engine which powers Azure SQL or SQL Engine, same supports the TDS protocol in the same manner as SQL Server or Azure SQL.

**Comment by hrstoyanov** [comment]
Thanks .. this might work!
One remark - the [Docker hub page](https://hub.docker.com/_/microsoft-azure-sql-edge?) has x86-64 labels, but not ARM64. This can confuse people to believe that ARM containers are not available. Please fix the labels.

**Comment by amvin87** [comment]
Thanks for the feedback ! 

@SQLSourabh can you please help update the label tags for the sql edge docker hub page to also reflect the ARM64 label. With this I am closing this issue for now.

**Comment by hrstoyanov** [comment]
One more question - does SQL Edge support CDC (change data capture)?

**Comment by SQLSourabh** [comment]
Yes SQL Edge support CDC.

**Comment by thisisthekap** [comment]
Docker is going to add support without the need for QEMU: https://github.com/docker/roadmap/issues/384
