### ISSUE TITLE
Environment Variable to auto-create a Database?

### ISSUE THREAD

**Issue by zhao-li** [microsoft/mssql-docker#685]
Thank you for providing this image to develop and test against SQL Server.

Reading through the description at: https://hub.docker.com/_/microsoft-mssql-server?tab=description

I did not see an environment variable to auto-create a database, similar to PostgreSQL's `POSTGRES_DB`: https://hub.docker.com/_/postgres

Is there an easy, prescribed way of auto-creating a database using environment variables or via another means?  I'm hoping that I missed something in the documentation that can help me avoid needing to run another script that uses SQL to create a database.

Thanks again 🙏🏻

**Comment by amvin87** [comment]
Thank you for the feedback, we are discussing this [here](https://github.com/microsoft/mssql-docker/issues/2)): and working on something and will update the thread when it is available
