### ISSUE TITLE
Unable to access internet after using OpenVPN docker container with mssql

### ISSUE THREAD

**Issue by nolramnat** [microsoft/mssql-docker#687]
Hello! I have a mssql db that i need to query through an openvpn and i have used the following commands to access it.

With this, i am able to query the relevant tables that i need with the credentials in openvpn, but i am not able to connect to the internet. This is all done on ubuntu.

This is the command i used for the docker (vpn being the name i created for the openvpn container):
docker run -it --net=container:vpn mcr.microsoft.com/mssql-tools

Connection tests i used are curl ipinfo.io & curl google.com, both showing timeout or unable to resolve host.

Can any kind soul point me in the right direction? Or should i be asking this question in the openvpn forum instead

**Comment by amvin87** [comment]
Hi @nolramnat , if you are able to connect to the SQL Server and query data then regarding why you cannot access the internet for this you might have to reach out to the VPN vendor that has been deployed as contianer. Also can you give the complete command using which you deployed the SQL containers.
