### ISSUE TITLE
Create Table ... As Node.  gives incorrect syntax error

### ISSUE THREAD

**Issue by sasiezilmadhavan** [Microsoft/mssql-docker#69]
Using the sample script from [https://docs.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-sample](url)  to create a graph table using latest SSMS RC3.  But it throws Incorrect syntax near ')' while executing the below statement.  

CREATE TABLE Person (ID INTEGER PRIMARY KEY, name VARCHAR(100)) AS NODE;

Tried with SQLCMD from the docker, gives the same error.

**Comment by twright-msft** [comment]
I tried this against CTP 2.1 using the VS code extension and sqlcmd inside the container.  Seems to work OK.  What version of SQL Server are you using?  SELECT @@VERSION

**Comment by perrysk-msft** [comment]
@sasiezilmadhavan - Please reopen if you arte still having this issue with the latest version sof the sql images:

- [Linux](https://hub.docker.com/r/microsoft/mssql-server-linux/)
- [Windows Developer Edition](https://hub.docker.com/r/microsoft/mssql-server-windows-developer/)
- [Windows Express Edition](https://hub.docker.com/r/microsoft/mssql-server-windows-express/)
