### ISSUE TITLE
podman add volume Permission denied 

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [microsoft/mssql-docker#693]
hi 
mcr.microsoft.com/mssql/server:2019-latest
podman add volume /volume/mssql = > /var/opt/mssql 

`
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
/opt/mssql/bin/sqlservr: Error: The system directory [/.system] could not be created. File: LinuxDirectory.cpp:420 [Status: 0xC0000022 Access Denied errno = 0xD(13) Permission denied]
Streaming disconnected
`

**Comment by amvin87** [comment]
This looks to be a issue with the permission on the host folder /volume/mssql do you have Selinux or any other LSM enabled, if so try using the :z or :Z options as documented here: https://www.redhat.com/sysadmin/behind-scenes-podman
