### ISSUE TITLE
mcr.microsoft.com/mssql/server support alpine docker image? 

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [microsoft/mssql-docker#694]
hi, 
Hello.
There is an image with alpine linux ?

**Comment by amvin87** [comment]
Hi @EvgenyPrikhodko, no for now we don't have an image shipped on alpine linux, but you can build this with your own custom docker, like we do for SLES here is a sample : https://github.com/microsoft/mssql-docker/blob/master/linux/preview/SLES/dockerfile, but please be aware this will not be supported for production workload.
