### ISSUE TITLE
What is the minimum volume size to run linux SQL server 2017 container?

### ISSUE THREAD

**Issue by myunghojung** [microsoft/mssql-docker#706]
Hello,

We are running a SQL server 2017 container on Linux. We only have a small size of data less than 100 MB but we observed an issue that there is no free space left on disk. How big the mounted volume should be?

Thanks,
Myungho

**Comment by myunghojung** [comment]
Is there a configuration that we can set for the maximum size of logs and temp files so that the size of files would not keep growing up?

**Comment by amvin87** [comment]
Yes, this is same as it is for SQL Server on Windows. Here is an article that explains how to manage the log file size and temp files:
https://docs.microsoft.com/en-us/sql/relational-databases/logs/manage-the-size-of-the-transaction-log-file?view=sql-server-ver15
you can follow the same recommendations and then pre-set the size of the tempdb and log using the alter database modify file size commands. Refer this for more information https://docs.microsoft.com/en-us/sql/relational-databases/databases/increase-the-size-of-a-database?view=sql-server-ver15

**Comment by myunghojung** [comment]
@amvin87 Thank you!
