### ISSUE TITLE
Windows Container Image: microsoft/mssql-server-windows-express does not exist anymore

### ISSUE THREAD

**Issue by nfMalde** [microsoft/mssql-docker#716]
Hi!

I just found out after an fresh install of my pc that the image microsoft/mssql-server-windows-express for windows containers does not exist anymore.

`>Error response from daemon: pull access denied for microsoft/mssql-server-windows-express, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

Is there any replacement for windows containers? Couldnt find anything ...

best,

Malte

**Comment by amvin87** [comment]
SQL Server on windows container is not supported for production workloads and no support is available for them. If you still want to use SQL Server on windows container for development and test purpose, you can create your own custom dockerfile here is a sample for the same: https://github.com/microsoft/mssql-docker/blob/master/windows/mssql-server-windows-developer/dockerfile_1

Here is a blog where the suspension of the SQL Server on Windows container was announced: https://techcommunity.microsoft.com/t5/sql-server/update-beta-program-for-sql-server-on-windows-container-is/ba-p/2516639
