### ISSUE TITLE
HTTP 404: Docker Images for Windows missing

### ISSUE THREAD

**Issue by jeeteshm** [microsoft/mssql-docker#718]
When I go to https://hub.docker.com/_/microsoft-mssql-server and click on the links (mentioned below) for `SQL Server for Windows Container` and `SQL Server Express for Windows Containers`, I am shown the HTTP 404 pages (attached). Can you please fix these links?

https://hub.docker.com/r/microsoft/mssql-server-windows-express
https://hub.docker.com/r/microsoft/mssql-server-windows-developer

![001](https://user-images.githubusercontent.com/5015172/133757832-72da0f84-b59c-495e-b6f0-077faf41664b.JPG)
![002](https://user-images.githubusercontent.com/5015172/133757921-c4c01eb6-10da-4c9e-98e4-97923c482ddd.JPG)

**Comment by m82labs** [comment]
The SQL Server on Windows Containers program was suspended and these images were removed:

https://techcommunity.microsoft.com/t5/sql-server/update-beta-program-for-sql-server-on-windows-container-is/ba-p/2516639

**Comment by amvin87** [comment]
Refer this sample dockerfile for reference to build own images for test and SQL on Windows container is not supported and only available for test and development: https://github.com/microsoft/mssql-docker/blob/master/windows/mssql-server-windows-developer/dockerfile_1
