### ISSUE TITLE
Provide the instructions to install SQLCMD on `FROM mcr.microsoft.com/dotnet/aspnet:6.0`

### ISSUE THREAD

**Issue by cilerler** [microsoft/mssql-docker#736]
Especially for troubleshooting purposes, mssqltools are vital to install to see if a container can connect to the SQL properly.
Unfortunately I couldn't install it on Debian 11, and I appreciate if you may provide necessary steps to install it.

**Comment by amvin87** [comment]
Hi @cilerler! If you deploy and run the mssql-server container by default it also installs the mssql tools. We dont have a package available on mcr only to install tools, but you can build a custom image which only has mssql tools and a sample dockerfile is available here for reference https://github.com/microsoft/mssql-docker/blob/master/linux/mssql-tools/Dockerfile

**Comment by cilerler** [comment]
That is not working, that is the reason, I'm asking for updated
documentation, please.

**Comment by cilerler** [comment]
@amvin87, please do not close it.
I'm already aware of it that mssql-server comes with it, and already tested to do it the way that Dockerfile does, and it didn't work, and that is the reason I posted it here.

Just change the first line `FROM Ubuntu:16.04` to `FROM mcr.microsoft.com/dotnet/aspnet:6.0` and you will see that it won't work due to https://github.com/microsoft/mssql-docker/blob/37532c96cd71e95b5c93747669bd1fa606019ad7/linux/mssql-tools/Dockerfile#L12
