### ISSUE TITLE
Mac M1 Docker and Azure SQL setup error

### ISSUE THREAD

**Issue by aiethics95** [microsoft/mssql-docker#743]
Hi guys, I'm new to this. I've spent around two weeks trying to resolve this issue and it's not working... I have a Mac M1 laptop. I installed Azure Data Studio and Docker so I can setup an SQL server. I followed all the instructions from different sites/videos online on how to set up the SQL server  for Mac M1 and I just keep getting this error:

--------------------
The SQL Server End-User License Agreement (EULA) must be accepted before SQL
Server can start. The license terms for this product can be downloaded from
https://go.microsoft.com/fwlink/?linkid=2139274....
--------------------

For example, I tried *********double and single quotes********* around the Accept Eula and password. I also tried 1 and Y. This was done to both examples below.

Here is a sample of some of the commands I have tried (I tried SO MANY others too...):

--------------------
docker run --cap-add SYS_PTRACE -e "ACCEPT_EULA=1" -e "MSSQL_SA_PASSWORD=reallyStrongPwd123@" -p 1433:1433 --name SQLServer -d mcr.microsoft.com/azure-sql-edge
--------------------

--------------------
docker run -d -p 1433:1433 -e ‘ACCEPT_EULA=Y’ -e ‘SA_PASSWORD=********’ --platform linux/arm64 --name sqlserver mcr.microsoft.com/azure-sql-edge
--------------------

I appreciate your help!

**Comment by thesqlsith** [comment]
Using the double-quotes is correct, however, you will need to specify Y and not 1 as the option.  "ACCEPT_EULA=Y"   https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash#pullandrun2019.

We are aware of the feedback regarding support for the ARM M1 chipset and we are evaluating ways to support this scenario.  Please visit our feedback site - aka.ms/sqlfeedback and upvote this feedback request - https://feedback.azure.com/d365community/idea/949650e5-3248-ec11-a819-0022484bf651.

While this is not an endorsement in any way by Microsoft or Microsoft's' affiliates, as an alternative until we fully support the ARM M1 chipset and if you find any of the features that you are interested in exploring with SQL Server missing from SQL Edge, you can try running podman (or docker) in a UTM VM.  Kit Loong has blogged the required steps - https://kitloong.medium.com/how-to-run-sql-server-2019-on-macbook-pro-m1-d1448525f805.  I only mentioned podman as an alternative as it can be installed a bit quicker on Debian 11 or higher, Ubuntu 22.04+, or any of the many distributions that are listed on the Podman.io site (https://podman.io/getting-started/installation) with a single command.

**Comment by aiethics95** [comment]
@thesqlsith Thank you for letting me know this is a limitation! I appreciate it.

**Comment by dzsquared** [comment]
Looks like everything raised here has been touched on in this thread and [here](https://github.com/microsoft/mssql-docker/issues/734#issuecomment-1382576843) - if you have other items I've missed please feel free to follow up!
