### ISSUE TITLE
no way to upgrade base packages in container

### ISSUE THREAD

**Issue by thetuxinator** [microsoft/mssql-docker#745]
Hi,

As there is no way to run anything as root in the containers provided for Linux, its impossible to do apt-get -y update and apt-get -y upgrade as a "Docker run" command. This is actually many times ignored but really important, as else the Container base is not using the latest Ubuntu Packages containing bugfixes and security updates of the base system! Thats for the reason as containers don't use netinstall and take the latest packages from Ubuntu's mirrors. What is the intended way to stay up2date? 

your images are dated 27.1.2022 which is quite old!

regards

Mike

**Comment by thetuxinator** [comment]
What about this?

**Comment by maxtortime** [comment]
I had a similar problem.

When I run `apt-get update` with mssql-docker image, there is an error below.

`E: The repository 'https://packages.microsoft.com/ubuntu/20.04/prod focal Release' does not have a Release file.`

You shoud add packages.microsoft.com
https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#examples

**Comment by thetuxinator** [comment]
Well i want to upgrade all the distro packages not the microsoft ones, else how do i get for example an up2date library inside the container without doing apt upgrade before launching my app in the container?

**Comment by tracker1** [comment]
Create your own Dockerfile, inherit the MS file... set the user to root, do your updates, then set the user back to sql/mssql (whatever the ms default user is).
