### ISSUE TITLE
Project Status/Maintenance?

### ISSUE THREAD

**Issue by thetuxinator** [microsoft/mssql-docker#764]
As many important issues raised here are uncommented, let me ask if this project and the resulting containers are still under maintenance or not!

Please clarify.

regards
Tuxinator

**Comment by thetuxinator** [comment]
Well, 12 days no reply even to this question, lets "mark" this Project as dead!

**Comment by SuperFola** [comment]
You can not label a project as dead just because nobody answered you. Latest commit was 28 days ago, it is still being worked on.

**Comment by amvin87** [comment]
for support and assistance please open support ticket. SQL Server containers on Linux are supported for production workload, and if there are issues that you are looking for immediate assistance.
