### ISSUE TITLE
`latest` isn't the latest, but is the same as `2017-latest`?

### ISSUE THREAD

**Issue by markhiveit** [microsoft/mssql-docker#771]
When pulling the latest image today, we got this error when starting the db:

```
2022-07-14 12:56:56.72 Server      Software Usage Metrics is disabled.
2022-07-14 12:56:56.73 spid5s      Starting up database 'master'.
2022-07-14 12:56:56.94 spid5s      Error: 948, Severity: 20, State: 1.
2022-07-14 12:56:56.94 spid5s      The database 'master' cannot be opened because it is version 904. This server supports version 869 and earlier. A downgrade path is not supported.
```

It seems like when someone pushed to `2017-latest` yesterday, they've also accidentally pushed to `latest`.

https://hub.docker.com/_/microsoft-mssql-server
![image](https://user-images.githubusercontent.com/44812484/178992282-dd008dd7-9ab6-498c-8fae-4a35db121fc7.png)

We checked the OS of `latest`, and it is Ubuntu 18.04, not 20.04 as listed:
```
SELECT @@VERSION AS 'SQL Server Version';

Microsoft SQL Server 2017 (RTM-CU30) (KB5013756) - 14.0.3451.2 (X64)  	Jun 22 2022 18:20:15  	Copyright (C) 2017 Microsoft Corporation 	Developer Edition (64-bit) on Linux (Ubuntu 18.04.6 LTS)
```

My thoughts go out to the poor soul who made the mistake -- we've all been there :)

**Comment by akatakritos** [comment]
This is hitting us too, I was able to figure out what version we actually had been previously using and pinned our docker-compose files to that tag. In our case most of our developers had cached `latest` at something around `:2019-CU12-ubuntu-20.04`. I'm learning the hard-way not to use `latest` on docker-compose files :)

**Comment by DaleyKD** [comment]
Went to go start up my microservices project that I haven't touched since Q1, and was met with `The database 'master' cannot be opened because it is version 904. This server supports version 869 and earlier. A downgrade path is not supported.`

I thought "WHY!? are you wanting SQL 2017!?"  Glad to know I'm not alone. I guess I can pin 2022-latest to update.

Sure hope MSFT fixes this soon.

**Comment by dzsquared** [comment]
The latest tag now reflects SQL Server 2022, apologies for the confusion.
