### ISSUE TITLE
SQL Server 2022 CTP 2.1 availability

### ISSUE THREAD

**Issue by MaceWindu** [microsoft/mssql-docker#777]
Any estimate on when `2022-latest` will be updated to CTP 2.1? It was released 27 Jul, but docker image still offer CTP 2.0

**Comment by thesqlsith** [comment]
Due to a few unexpected issues, we have had to delay the release of the SQL Server 2022 CTP 2.1 container images.  We do apologize for the delay; however, we are planning to release updated images with the next CTP for SQL Server 2022 which may be available by the end of this month.
