### ISSUE TITLE
SQL serve install on Mac 

### ISSUE THREAD

**Issue by teddybear415** [microsoft/mssql-docker#784]
I have been trying for days to install SQL Server and SQL Server Management Studio on Mac with Apple Chip. I have the Microsoft SQL edge running in docker.

Here is my terminal code:
myname@name-Air ~ % docker pull mcr.microsoft.com/azure-sql-edge
Using default tag: latest
latest: Pulling from azure-sql-edge
Digest: sha256:dfce05471e259d330e00bc9e66904254d75b714b35edc81495b4faee4a2dba96
Status: Image is up to date for mcr.microsoft.com/azure-sql-edge:latest
mcr.microsoft.com/azure-sql-edge:latest
myname@name-Air ~ % docker run -e "ACCEPT_EULA=1" -e "MSSQL_SA_PASSWORD=mystrongpassword" -e "MSSQL_PID=Developer" -e "MSSQL_USER=SA" -p 1433:1433 -d --name=sql mcr.microsoft.com/azure-sql-edge
dquote> 

Why do I get dquote> in return? When I attempted to create a connection in Azure data studio I receive: Login failed for user 'sa'.

<img width="1440" alt="Screen Shot 2022-09-24 at 8 41 48 PM" src="https://user-images.githubusercontent.com/100810788/192124720-4c0b4930-7f69-4337-9a61-81cd185e7003.png">

**Comment by bishrest-msft** [comment]
Provided you can ping to/from container and the local machine and telnet from your MacBook (telnet <ip_of_the_container> 1433) and that you see the container up and running, please try logging in with lowercase "sa" instead of SA. Also, try connecting with an ip address of the container (as a test) instead of "localhost".

**Comment by tracker1** [comment]
What do the output logs say?  If your password complexity isn't enough, it won't take it...  Also, as mentioned above, try the ip for the docker environment directly.  You didn't mention how you are running Docker, but docker desktop *should* setup the port redirects from "localhost", but this sometimes has issues.  If you're running Docker via another means, such as a full VM, then you definitely need to use the IP for the container/machine in question.

**Comment by dzsquared** [comment]
> Why do I get dquote> in return?

The highest probability is that you had a special character in your SA password that escaped the enclosing quotes.  Given the passing of time I'm assuming you got your container running and connected, but if you're still stuck please let us know!
