### ISSUE TITLE
mssql docker crashing in mac m1(arm processor)

### ISSUE THREAD

**Issue by prashant3167** [microsoft/mssql-docker#787]
Hi Everyone, I am trying to start mysql server in docker. It is crashing in arm processor with below error

`/opt/mssql/bin/permissions_check.sh: line 4: [: : integer expression expected
/opt/mssql/bin/permissions_check.sh: line 59: [: : integer expression expected
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
/opt/mssql/bin/sqlservr: Invalid mapping of address 0x4003918000 in reserved address space below 0x400000000000. Possible causes:
1) the process (itself, or via a wrapper) starts-up its own running environment sets the stack size limit to unlimited via syscall setrlimit(2);
2) the process (itself, or via a wrapper) adjusts its own execution domain and flag the system its legacy personality via syscall personality(2);
3) sysadmin deliberately sets the system to run on legacy VA layout mode by adjusting a sysctl knob vm.legacy_va_layout.`

Docker command: `docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Secret" \
   -p 1433:1433 --name sql1 --hostname sql1 \
   -d \
   mcr.microsoft.com/mssql/server:2022-latest`

**Comment by davidhenley** [comment]
You have to use https://hub.docker.com/_/microsoft-azure-sql-edge on M1 macs

**Comment by dzsquared** [comment]
To use the SQL Server images on M1/M2 Macs, you will need to use Rosetta emulation in Docker Desktop (https://devblogs.microsoft.com/azure-sql/development-with-sql-in-containers-on-macos/) or Colima.
