### ISSUE TITLE
Container disapear when mounting volume for persistent data

### ISSUE THREAD

**Issue by rocklee44** [microsoft/mssql-docker#790]
Hi all,
My server : Ubuntu 22.10, I want to run MSSQL server container with persistent data
I run this command
`docker run --rm -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=******" -e "MSSQL_PID=Express" -p 1433:1433 -v /path/mssql/data:/var/opt/mssql/data -v /path/mssql/log:/var/opt/mssql/log -v /path/mssql/secrets:/var/opt/mssql/secrets -d mcr.microsoft.com/mssql/server:2019-latest`
/path/mssql/data , /path/mssql/log , /path/mssql/secrets are empty folders.
```
docker ps -a
CONTAINER ID   IMAGE                                        COMMAND                  CREATED         STATUS         PORTS                                       NAMES
6cd5db571948   mcr.microsoft.com/mssql/server:2019-latest   "/opt/mssql/bin/perm…"   4 seconds ago   Up 2 seconds   0.0.0.0:1433->1433/tcp, :::1433->1433/tcp   sad_gates
```
But after afew seconds the container gone , what I did wrong ?
If I try mcr.microsoft.com/mssql/server:2017-latest it will works fine.

**Comment by tracker1** [comment]
What do your logs say?  Would give the instance a name when running (`--name sqlserver`), then you can use `docker logs sqlserver` to get the output...

**Comment by rocklee44** [comment]
Hi @tracker1 
```
docker ps -a
CONTAINER ID   IMAGE                                        COMMAND                  CREATED         STATUS         PORTS                                       NAMES
0e895efcec99   mcr.microsoft.com/mssql/server:2019-latest   "/opt/mssql/bin/perm…"   7 seconds ago   Up 4 seconds   0.0.0.0:1433->1433/tcp, :::1433->1433/tcp   sqlserver
docker logs -f sqlserver
docker logs -f sqlserver
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2022-11-17 01:39:48.84 Server      The licensing PID was successfully processed. The new edition is [Express Edition].
2022-11-17 01:39:49.14 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2022-11-17 01:39:49.15 Server      ERROR: Setup FAILED copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf':  5(Access is denied.)
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070005)
```
Then it's gone
```
docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Comment by rocklee44** [comment]
After googling the error I figure out that SQL Server 2019 by default runs as a non root container (user mssql) but the database itnit process need root permission so I add "--user=root" and it works now, thank you very much.
`docker run --rm --user=root -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=********" -e "MSSQL_PID=Express" -p 1433:1433 -v /path/data:/var/opt/mssql/data -v /path/log:/var/opt/mssql/log -v /path/secrets:/var/opt/mssql/secrets --name sqlserver -d mcr.microsoft.com/mssql/server:2019-latest`
