### ISSUE TITLE
RHEL based image for 2022 RTM

### ISSUE THREAD

**Issue by vg** [microsoft/mssql-docker#792]
Considering that the ubuntu based image is updated for 2022 RTM at https://hub.docker.com/_/microsoft-mssql-server please release the RHEL based image for 2022 RTM at https://catalog.redhat.com/software/containers/mssql/rhel/server/61f2f612f385723914ed60bc. 

Preferably based on RHEL 9.1 UBI or RHEL 8.7 UBI

**Comment by thesqlsith** [comment]
Thank you for the feedback. The RHEL and Ubuntu based images for SQL Server 2022 are available on the Microsoft Artifact Registry (formerly known as the Microsoft Container Registry) - https://mcr.microsoft.com/catalog?search=sql%20server

The catalog entry updates on Docker Hub and the Red Hat container catalog site that were mentioned are still in progress for SQL Server 2022. Both sites ultimately point back to the Microsoft Artifact Registry where the container images are actually hosted.

Depending on the container runtime that is preferred, executing something similar to what can be seen below will work and will be similar to what the updated catalog entries will look like as soon as those updates are published:

//Ubuntu 20.04
docker run -e "ACCEPT_EULA=Y" -e "MSSQL_AGENT_ENABLED=TRUE" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest

//RHEL 8.5 (as of the time of this reply)
docker run -e "ACCEPT_EULA=Y" -e "MSSQL_AGENT_ENABLED=TRUE" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 mcr.microsoft.com/mssql/rhel/server:2022-latest

or

//Ubuntu 20.04
podman run -e "ACCEPT_EULA=Y" -e "MSSQL_AGENT_ENABLED=TRUE" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest

//RHEL 8.5 (as of the time of this reply)
podman run -e "ACCEPT_EULA=Y" -e "MSSQL_AGENT_ENABLED=TRUE" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 mcr.microsoft.com/mssql/rhel/server:2022-latest

**Comment by amitkh-msft** [comment]
Hi Venu, the RHEL based https://catalog.redhat.com/software/containers/mssql/rhel/server/61f2f612f385723914ed60bc?container-tabs=overview is now updated with the preview release for RHEL 9. with this, I am closing this issue as resolved.

**Comment by vg** [comment]
Thanks @amitkh-msft, when can we expect the RHEL9 release to be out of preview?

**Comment by coderspb** [comment]
Bump.
Looking to deploy a server with RHEL9 instead of 8 soon, and this threw a wrench in the whole project.
