### ISSUE TITLE
Tools are not installed in the container

### ISSUE THREAD

**Issue by LuisBosquez** [Microsoft/mssql-docker#8]
There are multiple requests for having mssql-tools in the container to do data import and export and quick management of databases.

**Comment by cachurero** [comment]
If you don't add en_US.utf 8 as a dependency you will get this error:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid`

You should be add in the Dockerfile the next lines:
`locale-gen en_US.utf8  &&  update-locale`

**Comment by twright-msft** [comment]
Adding tools in the image increases the size by about 100 MB.  Any concerns with that?

**Comment by metaskills** [comment]
None here!

**Comment by twright-msft** [comment]
We have added the mssql-tools package to the mssql-server-linux image in the CTP 1.4 release that was posted today.

I've updated my example that used to use the Dockerfile to install the tools to now just expect the tools to already be in the image.
https://github.com/twright-msft/mssql-node-docker-demo-app

For now people can use an approach like that to do things like create (#2) or attach (#4) DBs, create logins (#18,#49), or whatever else needs to be done (#11) at `docker run `time.

In the end, it only increased the image size by about 20-30 MB not the 100 MB we thought it would be at first.

Please give it a try and let us know what you think!

**Comment by metaskills** [comment]
Thanks! This simplified the setup we have to do for the TInyTDS and Rails SQL Server testing.
