### ISSUE TITLE
Wrong Image Tag: `latest` refers to `2017`instead of `2022`

### ISSUE THREAD

**Issue by johannesheinz** [microsoft/mssql-docker#809]
Since today's update the Docker Image `mcr.microsoft.com/mssql/server:latest` seems to refer to `mcr.microsoft.com/mssql/server:2017-latest`. I expected `mcr.microsoft.com/mssql/server:2022-latest` as it was before. This leads to breking CI pipelines and is rather important/critical.

**Steps to reproduce:**

```
docker images
...
REPOSITORY                                                TAG                      IMAGE ID       CREATED         SIZE
mcr.microsoft.com/mssql/server                            2017-latest              fa4c9a7ae374   2 weeks ago     1.33GB
mcr.microsoft.com/mssql/server                            latest                   fa4c9a7ae374   2 weeks ago     1.33GB
mcr.microsoft.com/mssql/server                            2022-latest              001b5387b97c   2 weeks ago     1.6GB
```
The `IMAGE ID` of `latest` and `2017-latest`is the same.

**OR**

```
docker run mcr.microsoft.com/mssql/server:latest
```

This shows an error message of the 2017 version:

```
SQL Server 2017 will run as non-root by default.
```

When I specify the version, I get the expected 2022 error message:

```
docker run mcr.microsoft.com/mssql/server:2022-latest
...
SQL Server 2022 will run as non-root by default.
```

Thanks for your support and the continous updates. Please fix this issue soon. Thanks

**Comment by thesqlsith** [comment]
Thank you @johannesheinz for reporting this issue. We are working to correct the tags on the MCR. 

Not that this is your particular use case, the Red Hat based image does have the correct redirect for latest to SQL Server 2022, however the Ubuntu based image will be corrected.

**Comment by johannesheinz** [comment]
Thanks for your support and the suggestion! I used the opportunity to switch to a hard-coded CU version of the mssql Ubuntu image instead which works fine.
