### ISSUE TITLE
MSSQL returning wrong timezone info for Iran after DST stopped

### ISSUE THREAD

**Issue by mostafa8026** [microsoft/mssql-docker#819]
Iran has recently stopped Daylight Saving Time (DST) for its timezone. However, I'm facing an issue while using mssql with docker 2019-latest and using the TZ=Asia/Tehran timezone.

When I check the `date` command inside the container, it returns the correct response as `Wed Mar 22 16:05:15 +0330 2023`. However, the `select getdate()` command in the SQL Server returns the wrong response, as it still considers Iran to have DST enabled.

I tried running the following query to check the time zone information in SQL:

```
SELECT name, current_utc_offset, is_currently_dst
FROM sys.time_zone_info
WHERE name like '%iran%'
```

It returned the following response:

```
Iran Standard Time +04:30 1
```

And also it's weird that the value of `select CURRENT_TIMEZONE()` is `(UTC+03:30) Tehran`

It seems that MSSQL is not properly updating its time zone information for Iran after DST has been stopped. Can anyone please suggest a solution or workaround for this issue? Thanks in advance!

**Comment by tejasaks** [comment]
Can you please file a support request for this? We will be happy to look into this for you and make necessary updates if required.

**Comment by mostafa8026** [comment]
To submit a request through the [Microsoft Support for Business](https://support.microsoft.com/en-us/hub/4343728/support-for-business) portal, a licenseId is required. Since I am utilizing the complimentary features and do not possess a licenseId, is there an alternative location where I can submit my inquiry?

**Comment by mostafa8026** [comment]
Thank you for your response, @thesqlsith. I have submitted a bug report via the Ideas system as recommended (https://feedback.azure.com/d365community/idea/20f5a3c9-7fc9-ed11-a81b-00224850345d). This issue is causing significant disruption to our operations, and I would greatly appreciate any help or attention that can be given to resolve it as quickly as possible. Thank you for your assistance

**Comment by mostafa8026** [comment]
Any update?

**Comment by mostafa8026** [comment]
Steps to reproduce the bug:

Step 1: Run a Docker container with SQL Server 2022 image:

```
docker run --rm -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=MyPassword123' -e 'TZ=Asia/Tehran' --name mssql-temp -d mcr.microsoft.com/mssql/server:2022-latest
```

This will download and start a new Docker container with SQL Server 2022 image. The -e options are used to set environment variables for the container, including the SA password and the time zone to be used.

Step 2: Connect to the running container:

```
docker exec -it mssql-temp bash
```
This will open a new terminal session inside the container.

Step 3: Run a SQL query using sqlcmd:

```
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P MyPassword123 -Q "SELECT name, current_utc_offset, is_currently_dst FROM sys.time_zone_info WHERE name like '%iran%'"
```
This command will execute the SQL query against the SQL Server instance running in the container and here is the buggy output:

```
name                current_utc_offset  is_currently_dst
---------------------------------------------------------
Iran Standard Time  +04:30              1
```

**Comment by Jafar313** [comment]
Hello,
I encountered the same issue as described by @mostafa8026 in this GitHub issue regarding SQL Server and the timezone in Iran after DST has been stopped. It seems that MSSQL is not properly updating its time zone information for Iran after DST has been stopped.

As this is causing significant disruption to our operations, I kindly request the developers to find a solution or propose a hotfix as soon as possible. This is an urgent matter for me, and I would greatly appreciate any help or attention that can be given to resolve it as quickly as possible.

Thank you for your assistance.

**Comment by thesqlsith** [comment]
Thank you @Jafar313.

We are looking into the issue, and do not have an updated timeline when a fix for the SYSDATETIMEOFFSET function will be addressed. That function is part of what the sys.time_zone_info view uses to determine the time zone offset. You can use the "old school" sp_helptext to see the definition of this catalog view if interested:

exec sp_helptext 'sys.time_zone_info'

This is why you are seeing an incorrect offset.
SELECT (SYSDATETIMEOFFSET() AT TIME ZONE name) AS AT_TIMEZONE, name as TimeZoneName
FROM sys.time_zone_info WHERE name like 'Iran%';

The other date/time related system function are correctly reading the offset from the operating system. For example, CURRENT_TIMEZONE, GETDATE, GETUTCDATE, and SYSDATETIME as can be seen if you run the following query:

SELECT
    CURRENT_TIMEZONE() AS CURRENT_TIMEZONE,
    GETDATE() AS GET_DATE,
    GETUTCDATE() AS GET_UTC_DATE,
    SYSDATETIME() AS SYS_DATE_TIME,
    SYSDATETIMEOFFSET () AS SYS_DATE_TIMEOFFSET;

As a workaround until we can address the issue with the SYSDATEIMEOFFSET function, we would recommend that you use one of the four functions that were mentioned above in your deployment process if the time zone offset information is needed in your pipeline.

The team is aware of the problem, and we will keep you updated via the Ideas Feedback item that was opened by @mostafa8026. 

https://feedback.azure.com/d365community/idea/20f5a3c9-7fc9-ed11-a81b-00224850345d

**Comment by mostafa8026** [comment]
Thanks @thesqlsith for your reponse.
But My main problem is with the getdate() itself. It should return the time for TZ=Asia/Tehran without DST. Take a look at the following step by step example:
**step1:** run the mssql docker:
```
docker run --rm -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=MyPassword123' -e 'TZ=Asia/Tehran' --name mssql-temp -d mcr.microsoft.com/mssql/server:2022-latest
```

**step2:** enter inside the docker:
```
docker exec -it mssql-temp bash
```

**step3:** the docker runtime date
```
$ date
date
Fri Apr  7 20:54:38 +0330 2023
```

**step4:** But the getdate() return 1 hour ahead
```
$ /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P MyPassword123 -Q "SELECT getdate()"
-----------------------
2023-04-07 21:54:40.727
```

**and other related function:**
```
$ /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P MyPassword123 -Q "SELECT CURRENT_TIMEZONE() AS CURRENT_TIMEZONE, GETDATE() AS GET_DATE, GETUTCDATE() AS GET_UTC_DATE, SYSDATETIME() AS SYS_DATE_TIME, SYSDATETIMEOFFSET () AS SYS_DATE_TIMEOFFSET;"
-----------------------------------------------------------------------------------
(UTC+03:30) Tehran
2023-04-07 21:56:48.607
2023-04-07 17:26:48.607
2023-04-07 21:56:48.6085090
2023-04-07 21:56:48.6085090
+04:30
```

**Comment by thesqlsith** [comment]
Understood and thank you. Would you be able to just use either SYSUTCDATETIME() or GETUTCDATE() instead of GETDATE()? That should return the proper time with the appropriate offset since both are derived from the current local time and time zone settings of the OS where SQL Server is running (i.e. the host of the container in your case).

**Comment by mostafa8026** [comment]
Thank you for your suggestion, @thesqlsith. Unfortunately, using `SYSUTCDATETIME()` or `GETUTCDATE()` instead of `GETDATE()` is not possible in our case as it would require significant changes to our legacy program and may introduce new bugs. We are hoping for a solution to the issue with `getdate()` itself.

**Comment by mostafa8026** [comment]
Any news? I've seen that there is a new update (04/13/2023), but the issue remains unfortunately.

**Comment by thesqlsith** [comment]
Good day @mostafa8026, as an update to this thread, the time zone change for Iran should be available in the next CU for SQL Server 2022. We had released CU 5 for SQL Server 2022 (https://techcommunity.microsoft.com/t5/sql-server-blog/cumulative-update-5-for-sql-server-2022-rtm/ba-p/3849524) on June 15, 2023, so the next CU should contain the requested update.

**Comment by MoRooz** [comment]
I also had this issue and temporarily fixed it with this change:

GETDATE() =>  SWITCHOFFSET(GETUTCDATE(), '+03:30')

**Comment by thesqlsith** [comment]
**Update** Cumulative Update 6 for SQL Server 2022 has been released (a few hours ago from the date/time of this post). The IRST issue has been resolved for SQL Server 2022. Please feel free to pull the latest docker image from our repo (i.e. mcr.microsoft.com/mssql/server:2022-latest).

**Comment by mostafa8026** [comment]
Thanks, I've tested it and it was ok. Is there any update plan for sql 2019?

**Comment by thesqlsith** [comment]
Thanks for the confirmation @mostafa8026. Since our release cadence is longer for SQL Server 2019 versus SQL Server 2022, the LibOS updates should be in the next CU (CU 22) for SQL Server 2019. You can view the historical release cadence for SQL Server 2019 here - https://learn.microsoft.com/troubleshoot/sql/releases/sqlserver-2019/build-versions#sql-server-2019-cumulative-update-cu-builds. This should provide you with a rough estimate as to when the next CU will be available.

We have had to occasionally delay the release when unexpected events occur, but the link above should provide you with a relatively good idea when to expect CU 22 for SQL Server 2019.
