### ISSUE TITLE
microsoft/mssql-server-linux:latest doesn't contain /opt/mssql-tools/bin/sqlcmd

### ISSUE THREAD

**Issue by danpoltawski** [Microsoft/mssql-docker#82]
When using microsoft/mssql-server-linux:latest the mssql tools seems to be missing (this seems to be a recent change).

```
root@748ffa458524:/opt# ls -al /opt/ 
total 12
drwxrwxr-x  4 root root 4096 Apr 27 12:33 .
drwxr-xr-x 52 root root 4096 May  1 09:02 ..
drwxrwxr-x  5 root root 4096 Apr 27 12:33 mssql
root@748ffa458524:/opt#
```

When using microsoft/mssql-server-linux:ctp-2.0 the tools are present:
```
root@42ef03136154:/# ls -al /opt/ 
total 20
drwxrwxr-x  5 root root 4096 Apr 20 16:52 .
drwxr-xr-x 56 root root 4096 May  1 09:06 ..
drwxr-xr-x  3 root root 4096 Apr 20 16:52 microsoft
drwxrwxr-x  4 root root 4096 Apr 20 16:50 mssql
drwxrwxr-x  4 root root 4096 Apr 20 16:52 mssql-tools
```

**Comment by twright-msft** [comment]
There was an issue with our build process for CTP 2.0 that resulted in the tools not being included in the image when we first released it.  The next day we re-released the CTP 2.0 image and that one has the tools in it.  Please grab the :latest and try again.

**Comment by danpoltawski** [comment]
Confirmed - thanks. Sorry for not trying that earlier.

**Comment by danpoltawski** [comment]
Hi @twright-msft this seems to have reappeared with :latest and ctp2-1

**Comment by twright-msft** [comment]
Hmm... I'm not seeing that @danpoltawski .  Can you please double check on your side?  I pulled down latest and am running it and have /opt/mssql-tools/bin/sqlcmd and bcp present and functional.

**Comment by danpoltawski** [comment]
Sigh, pulling and running again and I am not seeing the issue. Don't know how I managed it.

Really sorry for wasting your time!
