### ISSUE TITLE
What happens when the license expires?

### ISSUE THREAD

**Issue by spinningarrow** [Microsoft/mssql-docker#83]
I'm using the `mssql-server-linux` image during development (for an app that is hosted on Azure and uses Azure's SQL Database). When the docker image starts, it prints how many days are remaining. I was wondering, what options do I have once the evaluation license expires? How can I continue to use the docker image for development?

**Comment by twright-msft** [comment]
Hi @spinningarrow 
We put out a new image release each month.  You can pull and run it, remounting to the same database files to "upgrade" each month and that will reset the 180 day countdown.  Once we get to General Availability later this year you will be able to choose an edition of SQL Server to run perpetually - Developer Edition for development or other editions like Standard or Enterprise for production.

**Comment by spinningarrow** [comment]
I see. Thanks for the clarification!

**Comment by frenzyashru** [comment]
Hi twright-msft,
I am working on mac and faced the same issue. Can you please elaborate on the following.
"remounting to the same database files to "upgrade" each month and that will reset the 180 day countdown

**Comment by twright-msft** [comment]
@frenzyashru - Do you have data that you want to preserve?  Or do you just need to get a new non-expiring container?

**Comment by qwervo** [comment]
Hi @twright-msft , same problem here, already expired. I would like to renew it preserving all the data. Could you please help with the steps?

Thanks in advance

**Comment by twright-msft** [comment]
If you ran your container initially by using -v to mount the /var/opt/mssql directory to a directory on the host or to a volume container then you just need to pull the latest image again and do a docker run -v to mount to the _same_ host directory or volume container.

If you did a docker run and did not mount your volume then you need to backup your database, copy the backup file out of your container to the host or network location.  Then pull the new image and run a new container using -v to point to the location of the backup file and restore it in the new container.  Remember this time to also use a -v to mount /var/opt/mssql.

Please make sure to read the documentation on volume mounting to fully understand how to make sure you are safeguarding your data.  https://docs.docker.com/storage/volumes/
