### ISSUE TITLE
Issue with Docker 24.0 and 2022-latest

### ISSUE THREAD

**Issue by mpn-peter-smith** [microsoft/mssql-docker#836]
Updated to Docker 24.0 build 98fdcd7 from 23 and now getting start-up errors with my 2022-latest container. Tried re-creating the container and even different servers but with the same issue. 

```
Last errno text: Permission denied
Capturing a dump of 10
Executing: /opt/mssql/bin/handle-crash.sh with parameters
     handle-crash.sh
     /opt/mssql/bin/sqlservr
     10
     /opt/mssql/bin
     /var/opt/mssql/log/

FAILED to capture a dump. Details in paldumper log.

Ubuntu 20.04.6 LTS
Capturing core dump and information to /var/opt/mssql/log...
/bin/cat: /proc/10/maps: Permission denied
```

Starting with a fresh container from scratch with the command 

```
docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=myStrongPassword" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest
```

Gives the same error.

Thanks

**Comment by xrow** [comment]
@mpn-peter-smith 

How did oyu fix yours? Maybe mine is related.

https://github.com/microsoft/mssql-docker/issues/838

**Comment by Run-c0de** [comment]
╰─
─╯
docker compose up --build

[+] Running 1/0
 ✔ Container db_sqlserver  Created                                            0.0s
Attaching to db_sqlserver
db_sqlserver  | SQL Server 2022 will run as non-root by default.
db_sqlserver  | This container is running as user mssql.
db_sqlserver  | Your master database file is owned by mssql.
db_sqlserver  | To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
db_sqlserver  | This program has encountered a fatal error and cannot continue running at Fri Feb 23 14:30:20 2024
db_sqlserver  | The following diagnostic information is available:
db_sqlserver  |
db_sqlserver  |          Reason: 0x00000001
db_sqlserver  |          Signal: SIGABRT - Aborted (6)
db_sqlserver  |           Stack:
db_sqlserver  |                  IP               Function
db_sqlserver  |                  ---------------- --------------------------------------
db_sqlserver  |                  0000587ffe5edce1 std::__1::bad_function_call::~bad_function_call()+0x96661
db_sqlserver  |                  0000587ffe5ed6a6 std::__1::bad_function_call::~bad_function_call()+0x96026
db_sqlserver  |                  0000587ffe5ecc2f std::__1::bad_function_call::~bad_function_call()+0x955af
db_sqlserver  |                  00007c1410e60520 __sigaction+0x50
db_sqlserver  |                  00007c1410eb49fc pthread_kill+0x12c
db_sqlserver  |                  00007c1410e60476 raise+0x16
db_sqlserver  |                  00007c1410e467f3 abort+0xd3
db_sqlserver  |                  0000587ffe5bed96 std::__1::bad_function_call::~bad_function_call()+0x67716
db_sqlserver  |                  0000587ffe5fb5b4 std::__1::bad_function_call::~bad_function_call()+0xa3f34
db_sqlserver  |                  0000587ffe629318 std::__1::bad_function_call::~bad_function_call()+0xd1c98
db_sqlserver  |                  0000587ffe6290fa std::__1::bad_function_call::~bad_function_call()+0xd1a7a
db_sqlserver  |                  0000587ffe5c520a std::__1::bad_function_call::~bad_function_call()+0x6db8a
db_sqlserver  |                  0000587ffe5c4e80 std::__1::bad_function_call::~bad_function_call()+0x6d800
db_sqlserver  |         Process: 10 - sqlservr
db_sqlserver  |          Thread: 114 (application thread 0x1b8)
db_sqlserver  |     Instance Id: 881de2ac-8c44-4885-87a4-60dee0e042c2
db_sqlserver  |        Crash Id: 5f3cbba4-1177-478a-8f69-0f7080003b2b
db_sqlserver  |     Build stamp: a9299dd605c652a3cea4246273441bcfaf48afb4b482ab9dc43771eecaf6600b
db_sqlserver  |    Distribution: Ubuntu 22.04.3 LTS
db_sqlserver  |      Processors: 12
db_sqlserver  |    Total Memory: 16617865216 bytes
db_sqlserver  |       Timestamp: Fri Feb 23 14:30:20 2024
db_sqlserver  |      Last errno: 2
db_sqlserver  | Last errno text: No such file or directory
db_sqlserver  | Capturing a dump of 10
db_sqlserver  | Successfully captured dump: /var/opt/mssql/log/core.sqlservr.2_23_2024_14_30_21.10
db_sqlserver  | Executing: /opt/mssql/bin/handle-crash.sh with parameters
db_sqlserver  |      handle-crash.sh
db_sqlserver  |      /opt/mssql/bin/sqlservr
db_sqlserver  |      10
db_sqlserver  |      /opt/mssql/bin
db_sqlserver  |      /var/opt/mssql/log/
db_sqlserver  |
db_sqlserver  |      881de2ac-8c44-4885-87a4-60dee0e042c2
db_sqlserver  |      5f3cbba4-1177-478a-8f69-0f7080003b2b
db_sqlserver  |
db_sqlserver  |      /var/opt/mssql/log/core.sqlservr.2_23_2024_14_30_21.10
db_sqlserver  |
db_sqlserver  | Ubuntu 22.04.3 LTS
db_sqlserver  | Capturing core dump and information to /var/opt/mssql/log...
db_sqlserver  | /bin/cat: /proc/10/maps: Permission denied
