### ISSUE TITLE
Docker images are not updated with new Windows releases

### ISSUE THREAD

**Issue by sixeyed** [Microsoft/mssql-docker#84]
The SQL Server images based on Windows Server Core aren't being updated when a new release of the Windows Server Core image is published. 

This means users need multiple versions of Windows base images - e.g. the latest for ASP.NET and older ones for SQL Server. It also means the SQL images aren't using the latest patches.

Currently Server Core is at version `10.0.14393.1066`. The [Developer edition image](https://hub.docker.com/r/microsoft/mssql-server-windows-developer/tags/) and the [Express edition](https://hub.docker.com/r/microsoft/mssql-server-windows-express/tags/) are at `10.0.14393.693`.

**Comment by sixeyed** [comment]
There's a new release of the Server Core base image. Now the base image is at version `10.0.14393.1198`. The Developer edition image and the Express edition are both still at `10.0.14393.693`.

**Comment by perrysk-msft** [comment]
Thanks @sixeyed! All the Windows SQL Server Docker images (Express, Developer, vNext-CTP2.1) have now been updated to use the latest version of the Server core base image: 10.0.14393.1198.
