### ISSUE TITLE
@@servername does not reflect --hostname used when creating container

### ISSUE THREAD

**Issue by suresh-kandoth** [Microsoft/mssql-docker#85]
When creating the container I can specify --hostname option. I am able to use that hostname to connect to the container using sqlcmd. But when I query "select @@servername" or "select name from sys.servers" I get back a different value.

When I attach to the container and execute hostname command, I get the right value.

This happens with all three Windows container images of SQL.

**Comment by SMelnykov** [comment]
+1 Same issue. Can not configure replication while real server (hostname) name is differ with @@servername
microsoft/mssql-server-linux - working fine

**Comment by SMelnykov** [comment]
It should be fixed in Docker windows engine or SQL server?
When it will be fixed if possible?

**Comment by twright-msft** [comment]
It's a SQL Server bug.  Plan is to fix it in the next release that comes out later this month.

**Comment by SMelnykov** [comment]
As workaround

**Comment by jacargentina** [comment]
Is this related also with `SELECT SERVERPROPERTY('Edition')` not working? I'm using it both on Docker for Mac, and Docker for Linux

**Comment by twright-msft** [comment]
Edition wont work properly until GA.

**Comment by aleks091** [comment]
👍 @twright-msft  any update on this issue ?

**Comment by roncansan** [comment]
Please let the community know about any update!

**Comment by schan-tin-guidewire** [comment]
Are there any plans to have this fixed? It seems there was a plan to fix this -- did it happen?

**Comment by twright-msft** [comment]
Yes, sorry we are a bit behind on the housekeeping here.  This was fixed already.  

$ docker run -e ACCEPT_EULA=Y -e SA_PASSWORD=XXXXXXXXX -p 1433:1433 -d --hostname foo microsoft/mssql-server-linux:latest

$ sqlcmd -S 127.0.0.1 -U sa -P XXXXXXXXXX
1> select @@servername
2> go
                                                                                                                                
--------------------------------------------------------------------------------------------------------------------------------
foo                                                                                                                             

(1 rows affected)

**Comment by mrvaghani** [comment]
Apologies for commenting on an old issue, but is there any documentation on how to set hostname using any other methods? Maybe something like setting up environment variables instead of passing --hostname? Or is that still the only option?
