### ISSUE TITLE
Current database reverts to Master after a short time passes

### ISSUE THREAD

**Issue by julielerman** [Microsoft/mssql-docker#86]
I'm not sure where this problem is coming from so I'll describe it and maybe someone has a clue!

On Mac.
Using Docker for Mac.
I'm running a container from the linux image.
I then start up ~~sqlcmd via mssql~~ sql-cli. By default it points to master.
I use a different database. Run some commands (.tables, a sql query). 
If I let it sit for about one minute it has reverted to master. For example if I re run the tsql query, it says the table I'm querying doesn't exist. Then I do some commands to discover I'm back on master.

I don't know if this is coming from the image or from sql-cli.

Thanks

**Comment by twright-msft** [comment]
At the beginning you say 'sqlcmd'. At the end you say sql-cli.  Can you please clarify which tool this is happening with?  And when you say 'start up sqlcmd via mssql' - what does that mean?  You mean you are running sqlcmd _inside_ the container?

**Comment by julielerman** [comment]
sorry, that was messy. I've edited the original comment. Using sql-cli from outside the container. HTH

**Comment by twright-msft** [comment]
@julielerman - I tried this just now on my mac.  Was able to repro.  Here's what I tried.  docker run a mssql-server-linux.  Connect using mssql (sql-cli) from the host to the container - i.e. mssql -s localhost and dont pass a specific database name.  Run select @@version and select name from sys.databases.  Use a simple user database i have on the container.  Run .tables and it shows me the tables in the user db.  Run a couple of select queries.  Let it sit for a couple of minutes.  Run the select query again.  Table could not be found.  I'd suggest opening an issue on the sql-cli project and see if this is something they have heard of before.  Seems to be pretty easy to reproduce.  https://github.com/hasankhan/sql-cli

**Comment by julielerman** [comment]
thanks Travis. submitted here: https://github.com/hasankhan/sql-cli/issues/44
Also happening on Windows. 
When I first saw this, I was so new to all of these tools SQL at command line, docker, and sql for linux) that I wasn't sure where to look for the source of the problem. I'm feeling a little more savvy now though. Thanks for your patience :)
