### ISSUE TITLE
Include bash files for linux image in this repository

### ISSUE THREAD

**Issue by julielerman** [Microsoft/mssql-docker#87]
I see that the windows images have their start.ps1 files included , but you don't have the bash files for the linux image. For example, I wanted to see what is in sqlserver.sh and had to drill into the container in order to run cat on it. Is there a reason or was it just an oversight? Thanks!

**Comment by twright-msft** [comment]
No particular reason.  We are removing it in the 2.1 release coming out this month though.  All of that logic has been moved inside of the startup routine of sqlservr.
