### ISSUE TITLE
Path to sqlcmd tools are different on windows and on Mac

### ISSUE THREAD

**Issue by CarlSargunar** [microsoft/mssql-docker#901]
I'm building a container running SQL 2022 : latest, and trying to execute a script using sqlcmd, but I've noticed the path of sqlcmd is different on windows vs on Arm (Apple M1)

On the windows image the path is /opt/mssql-tools/bin/sqlcmd, but on the m1 the path is /opt/mssql-tools18/bin/sqlcmd

It's the same container I'm building and running on both, my dockerfile is below. Is there any reason these paths are different on both these containers?

```
  FROM mcr.microsoft.com/mssql/server:2022-latest
  
  ENV ACCEPT_EULA=Y
  ENV SA_PASSWORD=xxxxxxx
  
  USER root
   
  RUN mkdir /var/opt/sqlserver
   
  RUN chown mssql /var/opt/sqlserver
   
  ENV MSSQL_BACKUP_DIR="/var/opt/mssql"
  ENV MSSQL_DATA_DIR="/var/opt/mssql/data"
  ENV MSSQL_LOG_DIR="/var/opt/mssql/log"
  
  EXPOSE 1433/tcp
  
  # Copy Setup SQL script
  COPY setup.sql /
  COPY startup.sh /
  
  ENTRYPOINT [ "/bin/bash", "startup.sh" ]
  CMD [ "/opt/mssql/bin/sqlservr" ]
```

**Comment by CarlSargunar** [comment]
To workaround the issue, I've had to add a check for the path on my startup.sh script as follows. This script essentially waits until it can connect, then runs the SQL script to create a seeded database for testing

```
#!/bin/bash
set -e

# Function to find sqlcmd in either of the possible paths
find_sqlcmd() {
  if [ -x "/opt/mssql-tools/bin/sqlcmd" ]; then
    echo "/opt/mssql-tools/bin/sqlcmd"
  elif [ -x "/opt/mssql-tools18/bin/sqlcmd" ]; then
    echo "/opt/mssql-tools18/bin/sqlcmd"
  else
    echo "sqlcmd not found" >&2
    exit 1
  fi
}

SQLCMD=$(find_sqlcmd)

if [ "$1" = '/opt/mssql/bin/sqlservr' ]; then
  # If this is the container's first run, initialize the application database
  if [ ! -f /tmp/app-initialized ]; then
    # Initialize the application database asynchronously in a background process.
    function initialize_app_database() {
      # Wait for SQL Server to start
      sleep 15s

      # Run the setup script to create the DB and the schema in the DB
      "$SQLCMD" -C -S localhost -U sa -P xxxxxxx -d master -i setup.sql

      # Note that the container has been initialized so future starts won't wipe changes to the data
      touch /tmp/app-initialized
    }
    initialize_app_database &
  fi
fi

exec "$@"
```

**Comment by stevenobird** [comment]
This is totally unrelated to macOS or Docker Desktop - Microsoft just changed the tooling shipped with the images as stated [here](https://learn.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&tabs=cli&pivots=cs1-bash):
> Starting with SQL Server 2022 (16.x) CU 14 and SQL Server 2019 (15.x) CU 28, the container images include the [new mssql-tools18](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver16#install-tools-on-linux) package. The previous directory /opt/mssql-tools/bin is being phased out. The new directory for Microsoft ODBC 18 tools is /opt/mssql-tools18/bin, aligning with the latest tools offering.

If you pull in `mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04`, the path should be `/opt/mssql-tools/bin` again.

**Comment by CarlSargunar** [comment]
Thanks for the info - I guess I must have pulled the "latest" image when the windows version had not yet been updated, but the mac version had.
