### ISSUE TITLE
Broken Docker image

### ISSUE THREAD

**Issue by JerryUrena** [Microsoft/mssql-docker#903]
## Image 
I have been using this image for months with no issues until today: `mcr.microsoft.com/mssql/server:2022-latest`  

To replicate this error run `docker pull mcr.microsoft.com/mssql/server:2022-latest` and the error message is:

```bash
docker pull mcr.microsoft.com/mssql/server:2022-latest
2022-latest: Pulling from mssql/server

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview mcr.microsoft.com/mssql/server:2022-latest
failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://eastus.data.mcr.microsoft.com/aba285c624a04409823b708c7a50e7b9-jttfjm99vo//docker/registry/v2/blobs/sha256/b2/b2761593c69305fb6e0fe9489be43a369c7aae434178f6d516aced84c41c7136/data?se=2024-10-22T15%3A06%3A10Z&sig=mgdpToHsbWa0Zfa34nqnuW2uAiAARcDckj5UiNb0CpY%3D&sp=r&spr=https&sr=b&sv=2018-03-28&regid=aba285c624a04409823b708c7a50e7b9": EOF
```

Same error occur when I do `docker pull mcr.microsoft.com/mssql/server:latest` and so on I tried about 10 different images. from the documentation [here](https://hub.docker.com/r/microsoft/mssql-server)

can someone please update the documentation and or fix the bug if any ? Please help.

**Comment by stevenobird** [comment]
I've been just pulling a newer version of 2022-latest, no issues here.

Did you try to open the URL printed out in a browser? If yes, does it show some kind of JSON object?  
If not, what kind of error is shown? What is the HTTP status code?

The issue could be related to a VPN being used, a firewall intercepting, ...
