### ISSUE TITLE
AD Authentication in SQL Server on Windows

### ISSUE THREAD

**Issue by cwoolum** [Microsoft/mssql-docker#92]
I am trying to deploy Sql Server to my windows docker host but one of the requirements I have is that users need to be able to sign in with ActiveDirectory. I've tried deploying my container using a gMSA but it still doesn't seem to connect to the domain. 

Is there any way to configure this?

**Comment by cwoolum** [comment]
Figured it out! I happened to be sitting at the Docker Session and the presenter mentioned that the host name needs to match the gMSA name. Adding ```-h <account_name> --name <account_name>``` fixed my problems.

**Comment by eeevans** [comment]
Were users able to login using domain credentials after that? Were the domain users already added to the database before attach?
