### ISSUE TITLE
Include netcat in the linux images

### ISSUE THREAD

**Issue by krancour** [Microsoft/mssql-docker#93]
Can I suggest including netcat in both the Ubuntu and RHEL-based images?

It seems there are longer-term plans for a more sophisticated entrypoint script to be built in and maybe it will be able to wait until the server is ready and then automatically apply some user-provided SQL, but until then, users are left creating their own custom entrypoint scripts...

As part of such a script, it's really quite reasonable to want to wait for SQL Server to be ready. `nc` is a great way of facilitating that and that would be made much easier if the image _included_ it.

For reference, here is what I am currently doing:

entrypoint.sh:
```
#!/usr/bin/env bash

# Start the setup script in the background
/root/scripts/setup.sh &

# Replace THIS process with the SQL Server process
exec /opt/mssql/bin/sqlservr.sh
```

setup.sh:
```
#!/usr/bin/env bash

# I would like to be able to eliminate these next two commands by
# baking this into the image-- they are really slowing down startup
apt-get update &> /dev/null
apt-get install -y netcat &> /dev/null

# Wait for SQL Server to be ready
while ! nc -z localhost 1433
do
  echo "setup.sh is waiting for mssql to be listening on port 1433"
  sleep 10
done

# Execute custom SQL to complete setup
/opt/mssql-tools/bin/sqlcmd \
  -S localhost -U SA -P '${SA_PASSWORD}' \
  -d master -i /root/scripts/setup.sql
```

Longer term, I think this very strategy could prove useful in a more sophisticated, built-in entrypoint script, so adding netcat now will set us up for that while also making it easier to get by in the meantime.

**Comment by twright-msft** [comment]
Can you please tell us more about your use case for waiting for SQL Server to come up?
here is on approach for handling waiting for Sql server to come up.
https://github.com/twright-msft/mssql-aspnet-docker-demo-app/blob/master/webapp/entrypoint.sh

It does the command in a do until loop waiting for it to successfully execute.
Would something like this work for your scenario?  Any pros/cons to that approach?

**Comment by krancour** [comment]
> Can you please tell us more about your use case for waiting for SQL Server to come up?

Sure. After it's up, I want to run some some SQL to create a non SA user and a database, and make that user the owner of that database. fwiw, I imagine this to be a common case, so it would be nice if such options could just be specified through environment variables. In the absence of this, checking that mssql is listening on 1433 has seemed a reliable approach.

I'm not opposed to changing my approach to loop/block until some command succeeds. I cannot figure out, realistically, what that command would be. I was hoping that, perhaps, I could do something with `sqlcmd` that would just test the connection and nothing more, but I haven't been able to make that work. fwiw, I do _not_ want the command I use in the loop to be the command that runs my SQL, because I want that command to be able to fail without causing an infinite loop.

**Comment by twright-msft** [comment]
Continuing our conversation here.  I tested using sqlcmd to probe for availability.  Here's what I tried.
Container running, executing command from my host.
$ sqlcmd -S 127.0.0.1 -U sa -P <my password> -Q "SELECT 1"
$ echo $?
results in 0  (zero) exit code indicating successful completion.
Stopped container
Did the same thing
results in 1 exit code indicating failure
I think if you do a loop on this testing for 0 then you could effectively use sqlcmd to test not only for port responses but SQL Server actually being fully up and ready to do something.
Please give that a try and see what you think....

**Comment by krancour** [comment]
Hi @twright-msft. Independently, I arrived at something pretty similar:

```
while ! /opt/mssql-tools/bin/sqlcmd \
  -S localhost -U SA -P "$SA_PASSWORD" \
  -d master -i /dev/null -l 5 &> /dev/null
do
  echo "setup.sh is waiting for mssql to be listening on port 1433"
  sleep 5
done
```

**Comment by twright-msft** [comment]
Yeah, that should work.  can we close out this specific issue then?

**Comment by krancour** [comment]
We sure can. Thanks for the help!
