### ISSUE TITLE
Older versions of mssql on a container, or not

### ISSUE THREAD

**Issue by bizmate** [Microsoft/mssql-docker#96]
As part of a specific software I am using the mssql version 11.0.3.3128 (I guess any 11) is required because in the version 14 of mssql I am currently running locally I get syntax errors with some of the queries that run perfectly fine otherwise on version 11 (or even 12 is fine as far as we noticed)

As we use containers and linux(ubuntu 16/debian jessie)/mac on development I was looking for a way to install the old version and see if the query still fails on the container. I have looked at microsoft/mssql-server-linux but this is only version 14 (not sure what the cpt version means). 

Any suggestions? Either dockerised or not

**Comment by twright-msft** [comment]
SQL Server is only supported on Linux starting with version 14.  If you need to use version 11, you'll need to install that natively on a Windows host or Windows VM.

**Comment by bizmate** [comment]
@twright-msft thank you for the reply. Do you know if there are any VM like virtual box solutions available? Would it be ok to install it on a VM from a license point of view? 
We have the actual license on the servers but I am wondering what can I do to replicate it on dev

**Comment by twright-msft** [comment]
You could look around on Atlas for a Vagrant box that has SQL 2012 (v11) installed in it or at least ready to be installed.  Like this one:
https://atlas.hashicorp.com/nkavadias/boxes/win2008r2-sql2012

There are two editions of SQL Server that you might interested in using in this scenario.  One is Express Edition which is free, has some feature limitations, and is limited in terms of the CPU/memory/DB size.  If you can work within those limits then you can use Express Edition in dev/test or production.
Developer Edition is full featured, unlimited resource utilization, but is disallowed for use in production.  If you are just doing dev/test then this would be your best bet.

If you just need it for a short time (less  than 180 days) you could use an Evaluation Edition too if you can find it around.
Hope that helps!

**Comment by bizmate** [comment]
That is very helpful. Thank you again I will close the ticket for now and I will give the images a try.
