### ISSUE TITLE
sp_readerrorlog CTP2.1 (Ubuntu): The log file is not using Unicode format

### ISSUE THREAD

**Issue by mhaywardhill** [Microsoft/mssql-docker#98]
Has the format of the SQL Server errorlog changed in the docker image microsoft/mssql-server-linux:ctp2.1 from ctp1.4 (not checked ctp2.0)? 

Running sp_readerrorlog from SSMS v17 returns the following error "The log file is not using Unicode format" when connected to:

Microsoft SQL Server 2017 (CTP2.1) - 14.0.600.250 (X64) 
    May 10 2017 12:21:23 
    Copyright (C) 2017 Microsoft Corporation. All rights reserved.
    Developer Edition (64-bit) on Linux (Ubuntu 16.04.2 LTS)

Running file -bi errorlog in bash on ctp2.1 returns charset=us-ascii, whereas in ctp1.4 charse= utf-161e

**Comment by twright-msft** [comment]
Yes it has.  sp_readerrorlog will be modified to handle this in CTP 2.2 next month.
